<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <!-- Suppressed warnings (please sort alphabetically!) -->
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Api.Contracts\Api.Contracts.csproj"/>
    <ProjectReference Include="..\UI\UI.csproj"/>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Services\" />
  </ItemGroup>

</Project>
