// <auto-generated>
// This file is generated by App.AotHelper -g. Do not edit manually.
// </auto-generated>

#pragma warning disable CS0618 // Obsolete types are still needed for AOT retention

using ActualChat.Aot;

namespace ActualChat.Internal;

internal partial class ApiAotSource : IAotSource
{
    public void KeepTypes()
    {
        if (CodeKeeper.AlwaysTrue)
            return;

        CodeKeeper.KeepSerializable<global::ActualChat.AliasId>();
        CodeKeeper.KeepSerializable<global::ActualChat.Audio.AudioFormat>();
        CodeKeeper.KeepSerializable<global::ActualChat.Audio.AudioFrame>();
        CodeKeeper.KeepSerializable<global::ActualChat.AuthorId>();
        CodeKeeper.KeepSerializable<global::ActualChat.AvatarQuery>();
        CodeKeeper.KeepSerializable<global::ActualChat.Chat.AddChatMembersBannerUserSettings>();
        CodeKeeper.KeepSerializable<global::ActualChat.Chat.Author>();
        CodeKeeper.KeepSerializable<global::ActualChat.Chat.AuthorDiff>();
        CodeKeeper.KeepSerializable<global::ActualChat.Chat.AuthorFull>();
        CodeKeeper.KeepSerializable<global::ActualChat.Chat.AuthorReadPosition>();
        CodeKeeper.KeepSerializable<global::ActualChat.Chat.AuthorRules>();
        CodeKeeper.KeepSerializable<global::ActualChat.Chat.Chat>();
        CodeKeeper.KeepSerializable<global::ActualChat.Chat.ChatCopyState>();
        CodeKeeper.KeepSerializable<global::ActualChat.Chat.ChatCopyStateDiff>();
        CodeKeeper.KeepSerializable<global::ActualChat.Chat.ChatDiff>();
        CodeKeeper.KeepSerializable<global::ActualChat.Chat.ChatEntry>();
        CodeKeeper.KeepSerializable<global::ActualChat.Chat.ChatEntryAttachment>();
        CodeKeeper.KeepSerializable<global::ActualChat.Chat.ChatEntryAudio>();
        CodeKeeper.KeepSerializable<global::ActualChat.Chat.ChatEntryDiff>();
        CodeKeeper.KeepSerializable<global::ActualChat.Chat.ChatEntryForwarded>();
        CodeKeeper.KeepSerializable<global::ActualChat.Chat.ChatEntryLanguage>();
        CodeKeeper.KeepSerializable<global::ActualChat.Chat.ChatEntryRangeMeta>();
        CodeKeeper.KeepSerializable<global::ActualChat.Chat.ChatLanguageTile>();
        CodeKeeper.KeepSerializable<global::ActualChat.Chat.ChatListSettings>();
        CodeKeeper.KeepSerializable<global::ActualChat.Chat.ChatNews>();
        CodeKeeper.KeepSerializable<global::ActualChat.Chat.ChatRangeMeta>();
        CodeKeeper.KeepSerializable<global::ActualChat.Chat.ChatTile>();
        CodeKeeper.KeepSerializable<global::ActualChat.Chat.ChatUserSettings>();
        CodeKeeper.KeepSerializable<global::ActualChat.Chat.Conversation>();
        CodeKeeper.KeepSerializable<global::ActualChat.Chat.ConversationDiff>();
        CodeKeeper.KeepSerializable<global::ActualChat.Chat.ConversationRangeMeta>();
        CodeKeeper.KeepSerializable<global::ActualChat.Chat.LegacyChatEntry>();
        CodeKeeper.KeepSerializable<global::ActualChat.Chat.LegacyChatNews>();
        CodeKeeper.KeepSerializable<global::ActualChat.Chat.LegacyChatTile>();
        CodeKeeper.KeepSerializable<global::ActualChat.Chat.MembersChangedOption>();
        CodeKeeper.KeepSerializable<global::ActualChat.Chat.Mention>();
        CodeKeeper.KeepSerializable<global::ActualChat.Chat.MentionMarkup>();
        CodeKeeper.KeepSerializable<global::ActualChat.Chat.MentionSearchResult>();
        CodeKeeper.KeepSerializable<global::ActualChat.Chat.NotifyMembersOption>();
        CodeKeeper.KeepSerializable<global::ActualChat.Chat.Place>();
        CodeKeeper.KeepSerializable<global::ActualChat.Chat.PlaceDiff>();
        CodeKeeper.KeepSerializable<global::ActualChat.Chat.PlaceRules>();
        CodeKeeper.KeepSerializable<global::ActualChat.Chat.Reaction>();
        CodeKeeper.KeepSerializable<global::ActualChat.Chat.ReactionSummary>();
        CodeKeeper.KeepSerializable<global::ActualChat.Chat.ReadPositionsStat>();
        CodeKeeper.KeepSerializable<global::ActualChat.Chat.Role>();
        CodeKeeper.KeepSerializable<global::ActualChat.Chat.RoleDiff>();
        CodeKeeper.KeepSerializable<global::ActualChat.Chat.SystemEntry>();
        CodeKeeper.KeepSerializable<global::ActualChat.Chat.Translation>();
        CodeKeeper.KeepSerializable<global::ActualChat.Chat.TranslationDiff>();
        CodeKeeper.KeepSerializable<global::ActualChat.ChatEntryId>();
        CodeKeeper.KeepSerializable<global::ActualChat.ChatId>();
        CodeKeeper.KeepSerializable<global::ActualChat.ContactId>();
        CodeKeeper.KeepSerializable<global::ActualChat.Contacts.Contact>();
        CodeKeeper.KeepSerializable<global::ActualChat.Contacts.ContactSubset>();
        CodeKeeper.KeepSerializable<global::ActualChat.Contacts.ExternalContact>();
        CodeKeeper.KeepSerializable<global::ActualChat.Contacts.ExternalContactFull>();
        CodeKeeper.KeepSerializable<global::ActualChat.Contacts.ExternalContactsHash>();
        CodeKeeper.KeepSerializable<global::ActualChat.Contacts.HashedExternalContact>();
        CodeKeeper.KeepSerializable<global::ActualChat.Contacts.ThreadContact>();
        CodeKeeper.KeepSerializable<global::ActualChat.ContentId>();
        CodeKeeper.KeepSerializable<global::ActualChat.ContentLinkInfo>();
        CodeKeeper.KeepSerializable<global::ActualChat.ConversationId>();
        CodeKeeper.KeepSerializable<global::ActualChat.Country>();
        CodeKeeper.KeepSerializable<global::ActualChat.Email>();
        CodeKeeper.KeepSerializable<global::ActualChat.Emoji>();
        CodeKeeper.KeepSerializable<global::ActualChat.ExplicitNotificationId>();
        CodeKeeper.KeepSerializable<global::ActualChat.ExternalContactId>();
        CodeKeeper.KeepSerializable<global::ActualChat.FakeDeviceContactOptions>();
        CodeKeeper.KeepSerializable<global::ActualChat.GroupChatId>();
        CodeKeeper.KeepSerializable<global::ActualChat.Interest>();
        CodeKeeper.KeepSerializable<global::ActualChat.Invite.ChatInviteOption>();
        CodeKeeper.KeepSerializable<global::ActualChat.Invite.ChatInviteSettings>();
        CodeKeeper.KeepSerializable<global::ActualChat.Invite.Invite>();
        CodeKeeper.KeepSerializable<global::ActualChat.Invite.InviteChatLinkPreview>();
        CodeKeeper.KeepSerializable<global::ActualChat.Invite.InviteDetails>();
        CodeKeeper.KeepSerializable<global::ActualChat.Invite.PlaceInviteOption>();
        CodeKeeper.KeepSerializable<global::ActualChat.Invite.UserInviteOption>();
        CodeKeeper.KeepSerializable<global::ActualChat.Language>();
        CodeKeeper.KeepSerializable<global::ActualChat.Live.LiveAudioFrame>();
        CodeKeeper.KeepSerializable<global::ActualChat.Live.LiveStreamEnd>();
        CodeKeeper.KeepSerializable<global::ActualChat.Live.LiveStreamInfo>();
        CodeKeeper.KeepSerializable<global::ActualChat.Live.LiveStreamReset>();
        CodeKeeper.KeepSerializable<global::ActualChat.Live.LiveStreamSettings>();
        CodeKeeper.KeepSerializable<global::ActualChat.Live.LiveStreamStart>();
        CodeKeeper.KeepSerializable<global::ActualChat.LocalAppSettings>();
        CodeKeeper.KeepSerializable<global::ActualChat.LocalOnboardingSettings>();
        CodeKeeper.KeepSerializable<global::ActualChat.LocalUrl>();
        CodeKeeper.KeepSerializable<global::ActualChat.Media.GrabStatus>();
        CodeKeeper.KeepSerializable<global::ActualChat.Media.LinkPreview>();
        CodeKeeper.KeepSerializable<global::ActualChat.Media.Media>();
        CodeKeeper.KeepSerializable<global::ActualChat.Media.MediaFull>();
        CodeKeeper.KeepSerializable<global::ActualChat.Media.MediaProgress>();
        CodeKeeper.KeepSerializable<global::ActualChat.Media.MediaRef>();
        CodeKeeper.KeepSerializable<global::ActualChat.Media.RecordingPart>();
        CodeKeeper.KeepSerializable<global::ActualChat.Media.Upload>();
        CodeKeeper.KeepSerializable<global::ActualChat.MediaId>();
        CodeKeeper.KeepSerializable<global::ActualChat.MentionId>();
        CodeKeeper.KeepSerializable<global::ActualChat.Notification.ChatEntryNotificationOption>();
        CodeKeeper.KeepSerializable<global::ActualChat.Notification.ChatNotificationOption>();
        CodeKeeper.KeepSerializable<global::ActualChat.Notification.GetAttentionNotificationOption>();
        CodeKeeper.KeepSerializable<global::ActualChat.Notification.Notification>();
        CodeKeeper.KeepSerializable<global::ActualChat.NotificationId>();
        CodeKeeper.KeepSerializable<global::ActualChat.PeerChatId>();
        CodeKeeper.KeepSerializable<global::ActualChat.Phone>();
        CodeKeeper.KeepSerializable<global::ActualChat.Picture>();
        CodeKeeper.KeepSerializable<global::ActualChat.PlaceChatId>();
        CodeKeeper.KeepSerializable<global::ActualChat.PlaceId>();
        CodeKeeper.KeepSerializable<global::ActualChat.PrincipalId>();
        CodeKeeper.KeepSerializable<global::ActualChat.RoleId>();
        CodeKeeper.KeepSerializable<global::ActualChat.Search.ContactSearchQuery>();
        CodeKeeper.KeepSerializable<global::ActualChat.Search.ContactSearchResult>();
        CodeKeeper.KeepSerializable<global::ActualChat.Search.ContactSearchResultPage>();
        CodeKeeper.KeepSerializable<global::ActualChat.Search.EntrySearchQuery>();
        CodeKeeper.KeepSerializable<global::ActualChat.Search.EntrySearchResult>();
        CodeKeeper.KeepSerializable<global::ActualChat.Search.EntrySearchResultPage>();
        CodeKeeper.KeepSerializable<global::ActualChat.StreamId>();
        CodeKeeper.KeepSerializable<global::ActualChat.Streaming.VideoStreamInfo>();
        CodeKeeper.KeepSerializable<global::ActualChat.ThreadChatId>();
        CodeKeeper.KeepSerializable<global::ActualChat.Transcription.StringDiff>();
        CodeKeeper.KeepSerializable<global::ActualChat.Transcription.Transcript>();
        CodeKeeper.KeepSerializable<global::ActualChat.Transcription.TranscriptDiff>();
        CodeKeeper.KeepSerializable<global::ActualChat.TranslationId>();
        CodeKeeper.KeepSerializable<global::ActualChat.TranslationSourceId>();
        CodeKeeper.KeepSerializable<global::ActualChat.UploadId>();
        CodeKeeper.KeepSerializable<global::ActualChat.UserDeviceId>();
        CodeKeeper.KeepSerializable<global::ActualChat.UserId>();
        CodeKeeper.KeepSerializable<global::ActualChat.Users.Account>();
        CodeKeeper.KeepSerializable<global::ActualChat.Users.AccountFull>();
        CodeKeeper.KeepSerializable<global::ActualChat.Users.Avatar>();
        CodeKeeper.KeepSerializable<global::ActualChat.Users.AvatarFull>();
        CodeKeeper.KeepSerializable<global::ActualChat.Users.ChatPosition>();
        CodeKeeper.KeepSerializable<global::ActualChat.Users.DigestPreview>();
        CodeKeeper.KeepSerializable<global::ActualChat.Users.DigestPreviewChat>();
        CodeKeeper.KeepSerializable<global::ActualChat.Users.GuestIdOption>();
        CodeKeeper.KeepSerializable<global::ActualChat.Users.LegacySessionInfo>();
        CodeKeeper.KeepSerializable<global::ActualChat.Users.SessionInfo>();
        CodeKeeper.KeepSerializable<global::ActualChat.Users.SessionInfoFull>();
        CodeKeeper.KeepSerializable<global::ActualChat.Users.TimeZone>();
        CodeKeeper.KeepSerializable<global::ActualChat.Users.UserAppSettings>();
        CodeKeeper.KeepSerializable<global::ActualChat.Users.UserAvatarSettings>();
        CodeKeeper.KeepSerializable<global::ActualChat.Users.UserBubbleSettings>();
        CodeKeeper.KeepSerializable<global::ActualChat.Users.UserChatRecordingDetectedLanguage>();
        CodeKeeper.KeepSerializable<global::ActualChat.Users.UserEmailsSettings>();
        CodeKeeper.KeepSerializable<global::ActualChat.Users.UserIdentity>();
        CodeKeeper.KeepSerializable<global::ActualChat.Users.UserLanguageSettings>();
        CodeKeeper.KeepSerializable<global::ActualChat.Users.UserListeningSettings>();
        CodeKeeper.KeepSerializable<global::ActualChat.Users.UserNavbarSettings>();
        CodeKeeper.KeepSerializable<global::ActualChat.Users.UserOnboardingSettings>();
        CodeKeeper.KeepSerializable<global::ActualChat.Users.UserReactionSettings>();
        CodeKeeper.KeepSerializable<global::ActualChat.Users.UserReplaySettings>();
        CodeKeeper.KeepSerializable<global::ActualChat.Users.UserSettings_Set>();
        CodeKeeper.KeepSerializable<global::ActualChat.Users.UserTranscodingTestSettings>();
        CodeKeeper.KeepSerializable<global::ActualChat.Users.UserTranscriptionEngineSettings>();
        CodeKeeper.KeepSerializable<global::ActualChat.Video.VideoFormat>();
        CodeKeeper.KeepSerializable<global::ActualChat.Video.VideoFrame>();
        CodeKeeper.KeepSerializable<global::ActualChat.Video.VideoQualityPreset>();
    }

    public (Type, AotTypeKind)[] ListTypes()
        => [
            (typeof(global::ActualChat.AliasId), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Audio.AudioFormat), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Audio.AudioFrame), AotTypeKind.Serializable),
            (typeof(global::ActualChat.AuthorId), AotTypeKind.Serializable),
            (typeof(global::ActualChat.AvatarQuery), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Chat.AddChatMembersBannerUserSettings), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Chat.Author), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Chat.AuthorDiff), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Chat.AuthorFull), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Chat.AuthorReadPosition), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Chat.AuthorRules), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Chat.Chat), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Chat.ChatCopyState), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Chat.ChatCopyStateDiff), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Chat.ChatDiff), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Chat.ChatEntry), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Chat.ChatEntryAttachment), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Chat.ChatEntryAudio), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Chat.ChatEntryDiff), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Chat.ChatEntryForwarded), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Chat.ChatEntryLanguage), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Chat.ChatEntryRangeMeta), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Chat.ChatLanguageTile), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Chat.ChatListSettings), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Chat.ChatNews), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Chat.ChatRangeMeta), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Chat.ChatTile), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Chat.ChatUserSettings), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Chat.Conversation), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Chat.ConversationDiff), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Chat.ConversationRangeMeta), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Chat.LegacyChatEntry), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Chat.LegacyChatNews), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Chat.LegacyChatTile), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Chat.MembersChangedOption), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Chat.Mention), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Chat.MentionMarkup), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Chat.MentionSearchResult), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Chat.NotifyMembersOption), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Chat.Place), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Chat.PlaceDiff), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Chat.PlaceRules), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Chat.Reaction), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Chat.ReactionSummary), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Chat.ReadPositionsStat), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Chat.Role), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Chat.RoleDiff), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Chat.SystemEntry), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Chat.Translation), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Chat.TranslationDiff), AotTypeKind.Serializable),
            (typeof(global::ActualChat.ChatEntryId), AotTypeKind.Serializable),
            (typeof(global::ActualChat.ChatId), AotTypeKind.Serializable),
            (typeof(global::ActualChat.ContactId), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Contacts.Contact), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Contacts.ContactSubset), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Contacts.ExternalContact), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Contacts.ExternalContactFull), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Contacts.ExternalContactsHash), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Contacts.HashedExternalContact), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Contacts.ThreadContact), AotTypeKind.Serializable),
            (typeof(global::ActualChat.ContentId), AotTypeKind.Serializable),
            (typeof(global::ActualChat.ContentLinkInfo), AotTypeKind.Serializable),
            (typeof(global::ActualChat.ConversationId), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Country), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Email), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Emoji), AotTypeKind.Serializable),
            (typeof(global::ActualChat.ExplicitNotificationId), AotTypeKind.Serializable),
            (typeof(global::ActualChat.ExternalContactId), AotTypeKind.Serializable),
            (typeof(global::ActualChat.FakeDeviceContactOptions), AotTypeKind.Serializable),
            (typeof(global::ActualChat.GroupChatId), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Interest), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Invite.ChatInviteOption), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Invite.ChatInviteSettings), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Invite.Invite), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Invite.InviteChatLinkPreview), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Invite.InviteDetails), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Invite.PlaceInviteOption), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Invite.UserInviteOption), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Language), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Live.LiveAudioFrame), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Live.LiveStreamEnd), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Live.LiveStreamInfo), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Live.LiveStreamReset), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Live.LiveStreamSettings), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Live.LiveStreamStart), AotTypeKind.Serializable),
            (typeof(global::ActualChat.LocalAppSettings), AotTypeKind.Serializable),
            (typeof(global::ActualChat.LocalOnboardingSettings), AotTypeKind.Serializable),
            (typeof(global::ActualChat.LocalUrl), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Media.GrabStatus), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Media.LinkPreview), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Media.Media), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Media.MediaFull), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Media.MediaProgress), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Media.MediaRef), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Media.RecordingPart), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Media.Upload), AotTypeKind.Serializable),
            (typeof(global::ActualChat.MediaId), AotTypeKind.Serializable),
            (typeof(global::ActualChat.MentionId), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Notification.ChatEntryNotificationOption), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Notification.ChatNotificationOption), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Notification.GetAttentionNotificationOption), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Notification.Notification), AotTypeKind.Serializable),
            (typeof(global::ActualChat.NotificationId), AotTypeKind.Serializable),
            (typeof(global::ActualChat.PeerChatId), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Phone), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Picture), AotTypeKind.Serializable),
            (typeof(global::ActualChat.PlaceChatId), AotTypeKind.Serializable),
            (typeof(global::ActualChat.PlaceId), AotTypeKind.Serializable),
            (typeof(global::ActualChat.PrincipalId), AotTypeKind.Serializable),
            (typeof(global::ActualChat.RoleId), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Search.ContactSearchQuery), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Search.ContactSearchResult), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Search.ContactSearchResultPage), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Search.EntrySearchQuery), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Search.EntrySearchResult), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Search.EntrySearchResultPage), AotTypeKind.Serializable),
            (typeof(global::ActualChat.StreamId), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Streaming.VideoStreamInfo), AotTypeKind.Serializable),
            (typeof(global::ActualChat.ThreadChatId), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Transcription.StringDiff), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Transcription.Transcript), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Transcription.TranscriptDiff), AotTypeKind.Serializable),
            (typeof(global::ActualChat.TranslationId), AotTypeKind.Serializable),
            (typeof(global::ActualChat.TranslationSourceId), AotTypeKind.Serializable),
            (typeof(global::ActualChat.UploadId), AotTypeKind.Serializable),
            (typeof(global::ActualChat.UserDeviceId), AotTypeKind.Serializable),
            (typeof(global::ActualChat.UserId), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Users.Account), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Users.AccountFull), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Users.Avatar), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Users.AvatarFull), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Users.ChatPosition), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Users.DigestPreview), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Users.DigestPreviewChat), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Users.GuestIdOption), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Users.LegacySessionInfo), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Users.SessionInfo), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Users.SessionInfoFull), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Users.TimeZone), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Users.UserAppSettings), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Users.UserAvatarSettings), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Users.UserBubbleSettings), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Users.UserChatRecordingDetectedLanguage), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Users.UserEmailsSettings), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Users.UserIdentity), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Users.UserLanguageSettings), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Users.UserListeningSettings), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Users.UserNavbarSettings), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Users.UserOnboardingSettings), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Users.UserReactionSettings), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Users.UserReplaySettings), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Users.UserSettings_Set), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Users.UserTranscodingTestSettings), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Users.UserTranscriptionEngineSettings), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Video.VideoFormat), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Video.VideoFrame), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Video.VideoQualityPreset), AotTypeKind.Serializable),
        ];
}
