// <auto-generated>
// This file is generated by App.AotHelper -g. Do not edit manually.
// </auto-generated>

#pragma warning disable CS0618 // Obsolete types are still needed for AOT retention

using ActualChat.Aot;

namespace ActualChat.Module;

internal partial class ApiAotSource : IAotSource
{
    public void KeepTypes()
    {
        if (CodeKeeper.AlwaysTrue)
            return;

        CodeKeeper.KeepSerializable<global::ActualChat.AliasId>();
        CodeKeeper.KeepSerializable<global::ActualChat.Audio.AudioFormat>();
        CodeKeeper.KeepSerializable<global::ActualChat.Audio.AudioFrame>();
        CodeKeeper.KeepSerializable<global::ActualChat.AuthorId>();
        CodeKeeper.KeepSerializable<global::ActualChat.AvatarQuery>();
        CodeKeeper.KeepSerializable<global::ActualChat.Chat.AddChatMembersBannerUserSettings>();
        CodeKeeper.KeepSerializable<global::ActualChat.Chat.Author>();
        CodeKeeper.KeepSerializable<global::ActualChat.Chat.AuthorDiff>();
        CodeKeeper.KeepSerializable<global::ActualChat.Chat.AuthorFull>();
        CodeKeeper.KeepSerializable<global::ActualChat.Chat.AuthorReadPosition>();
        CodeKeeper.KeepSerializable<global::ActualChat.Chat.AuthorRules>();
        CodeKeeper.KeepSerializable<global::ActualChat.Chat.Chat>();
        CodeKeeper.KeepSerializable<global::ActualChat.Chat.ChatCopyState>();
        CodeKeeper.KeepSerializable<global::ActualChat.Chat.ChatCopyStateDiff>();
        CodeKeeper.KeepSerializable<global::ActualChat.Chat.ChatDiff>();
        CodeKeeper.KeepSerializable<global::ActualChat.Chat.ChatEntry>();
        CodeKeeper.KeepSerializable<global::ActualChat.Chat.ChatEntryAttachment>();
        CodeKeeper.KeepSerializable<global::ActualChat.Chat.ChatEntryAudio>();
        CodeKeeper.KeepSerializable<global::ActualChat.Chat.ChatEntryDiff>();
        CodeKeeper.KeepSerializable<global::ActualChat.Chat.ChatEntryForwarded>();
        CodeKeeper.KeepSerializable<global::ActualChat.Chat.ChatEntryLanguage>();
        CodeKeeper.KeepSerializable<global::ActualChat.Chat.ChatEntryRangeMeta>();
        CodeKeeper.KeepSerializable<global::ActualChat.Chat.ChatLanguageTile>();
        CodeKeeper.KeepSerializable<global::ActualChat.Chat.ChatListSettings>();
        CodeKeeper.KeepSerializable<global::ActualChat.Chat.ChatNews>();
        CodeKeeper.KeepSerializable<global::ActualChat.Chat.ChatRangeMeta>();
        CodeKeeper.KeepSerializable<global::ActualChat.Chat.ChatTile>();
        CodeKeeper.KeepSerializable<global::ActualChat.Chat.ChatUserSettings>();
        CodeKeeper.KeepSerializable<global::ActualChat.Chat.Conversation>();
        CodeKeeper.KeepSerializable<global::ActualChat.Chat.ConversationDiff>();
        CodeKeeper.KeepSerializable<global::ActualChat.Chat.ConversationRangeMeta>();
        CodeKeeper.KeepSerializable<global::ActualChat.Chat.LegacyChatEntry>();
        CodeKeeper.KeepSerializable<global::ActualChat.Chat.LegacyChatNews>();
        CodeKeeper.KeepSerializable<global::ActualChat.Chat.LegacyChatTile>();
        CodeKeeper.KeepSerializable<global::ActualChat.Chat.MembersChangedOption>();
        CodeKeeper.KeepSerializable<global::ActualChat.Chat.Mention>();
        CodeKeeper.KeepSerializable<global::ActualChat.Chat.MentionMarkup>();
        CodeKeeper.KeepSerializable<global::ActualChat.Chat.MentionSearchResult>();
        CodeKeeper.KeepSerializable<global::ActualChat.Chat.NotifyMembersOption>();
        CodeKeeper.KeepSerializable<global::ActualChat.Chat.Place>();
        CodeKeeper.KeepSerializable<global::ActualChat.Chat.PlaceDiff>();
        CodeKeeper.KeepSerializable<global::ActualChat.Chat.PlaceRules>();
        CodeKeeper.KeepSerializable<global::ActualChat.Chat.Reaction>();
        CodeKeeper.KeepSerializable<global::ActualChat.Chat.ReactionSummary>();
        CodeKeeper.KeepSerializable<global::ActualChat.Chat.ReadPositionsStat>();
        CodeKeeper.KeepSerializable<global::ActualChat.Chat.Role>();
        CodeKeeper.KeepSerializable<global::ActualChat.Chat.RoleDiff>();
        CodeKeeper.KeepSerializable<global::ActualChat.Chat.SystemEntry>();
        CodeKeeper.KeepSerializable<global::ActualChat.Chat.Translation>();
        CodeKeeper.KeepSerializable<global::ActualChat.Chat.TranslationDiff>();
        CodeKeeper.KeepSerializable<global::ActualChat.ChatEntryId>();
        CodeKeeper.KeepSerializable<global::ActualChat.ChatId>();
        CodeKeeper.KeepSerializable<global::ActualChat.ContactId>();
        CodeKeeper.KeepSerializable<global::ActualChat.Contacts.Contact>();
        CodeKeeper.KeepSerializable<global::ActualChat.Contacts.ContactSubset>();
        CodeKeeper.KeepSerializable<global::ActualChat.Contacts.ExternalContact>();
        CodeKeeper.KeepSerializable<global::ActualChat.Contacts.ExternalContactFull>();
        CodeKeeper.KeepSerializable<global::ActualChat.Contacts.ExternalContactsHash>();
        CodeKeeper.KeepSerializable<global::ActualChat.Contacts.HashedExternalContact>();
        CodeKeeper.KeepSerializable<global::ActualChat.Contacts.ThreadContact>();
        CodeKeeper.KeepSerializable<global::ActualChat.ContentId>();
        CodeKeeper.KeepSerializable<global::ActualChat.ContentLinkInfo>();
        CodeKeeper.KeepSerializable<global::ActualChat.ConversationId>();
        CodeKeeper.KeepSerializable<global::ActualChat.Country>();
        CodeKeeper.KeepSerializable<global::ActualChat.Email>();
        CodeKeeper.KeepSerializable<global::ActualChat.Emoji>();
        CodeKeeper.KeepSerializable<global::ActualChat.ExplicitNotificationId>();
        CodeKeeper.KeepSerializable<global::ActualChat.ExternalContactId>();
        CodeKeeper.KeepSerializable<global::ActualChat.FakeDeviceContactOptions>();
        CodeKeeper.KeepSerializable<global::ActualChat.GroupChatId>();
        CodeKeeper.KeepSerializable<global::ActualChat.Interest>();
        CodeKeeper.KeepSerializable<global::ActualChat.Invite.ChatInviteOption>();
        CodeKeeper.KeepSerializable<global::ActualChat.Invite.ChatInviteSettings>();
        CodeKeeper.KeepSerializable<global::ActualChat.Invite.Invite>();
        CodeKeeper.KeepSerializable<global::ActualChat.Invite.InviteChatLinkPreview>();
        CodeKeeper.KeepSerializable<global::ActualChat.Invite.InviteDetails>();
        CodeKeeper.KeepSerializable<global::ActualChat.Invite.PlaceInviteOption>();
        CodeKeeper.KeepSerializable<global::ActualChat.Invite.UserInviteOption>();
        CodeKeeper.KeepSerializable<global::ActualChat.Language>();
        CodeKeeper.KeepSerializable<global::ActualChat.Live.LiveAudioFrame>();
        CodeKeeper.KeepSerializable<global::ActualChat.Live.LiveStreamEnd>();
        CodeKeeper.KeepSerializable<global::ActualChat.Live.LiveStreamInfo>();
        CodeKeeper.KeepSerializable<global::ActualChat.Live.LiveStreamReset>();
        CodeKeeper.KeepSerializable<global::ActualChat.Live.LiveStreamSettings>();
        CodeKeeper.KeepSerializable<global::ActualChat.Live.LiveStreamStart>();
        CodeKeeper.KeepSerializable<global::ActualChat.LocalAppSettings>();
        CodeKeeper.KeepSerializable<global::ActualChat.LocalOnboardingSettings>();
        CodeKeeper.KeepSerializable<global::ActualChat.LocalUrl>();
        CodeKeeper.KeepSerializable<global::ActualChat.Media.GrabStatus>();
        CodeKeeper.KeepSerializable<global::ActualChat.Media.LinkPreview>();
        CodeKeeper.KeepSerializable<global::ActualChat.Media.Media>();
        CodeKeeper.KeepSerializable<global::ActualChat.Media.MediaFull>();
        CodeKeeper.KeepSerializable<global::ActualChat.Media.MediaProgress>();
        CodeKeeper.KeepSerializable<global::ActualChat.Media.MediaRef>();
        CodeKeeper.KeepSerializable<global::ActualChat.Media.RecordingPart>();
        CodeKeeper.KeepSerializable<global::ActualChat.Media.Upload>();
        CodeKeeper.KeepSerializable<global::ActualChat.MediaId>();
        CodeKeeper.KeepSerializable<global::ActualChat.MentionId>();
        CodeKeeper.KeepSerializable<global::ActualChat.Notification.ChatEntryNotificationOption>();
        CodeKeeper.KeepSerializable<global::ActualChat.Notification.ChatNotificationOption>();
        CodeKeeper.KeepSerializable<global::ActualChat.Notification.GetAttentionNotificationOption>();
        CodeKeeper.KeepSerializable<global::ActualChat.Notification.Notification>();
        CodeKeeper.KeepSerializable<global::ActualChat.NotificationId>();
        CodeKeeper.KeepSerializable<global::ActualChat.PeerChatId>();
        CodeKeeper.KeepSerializable<global::ActualChat.Phone>();
        CodeKeeper.KeepSerializable<global::ActualChat.Picture>();
        CodeKeeper.KeepSerializable<global::ActualChat.PlaceChatId>();
        CodeKeeper.KeepSerializable<global::ActualChat.PlaceId>();
        CodeKeeper.KeepSerializable<global::ActualChat.PrincipalId>();
        CodeKeeper.KeepSerializable<global::ActualChat.RoleId>();
        CodeKeeper.KeepSerializable<global::ActualChat.Search.ContactSearchQuery>();
        CodeKeeper.KeepSerializable<global::ActualChat.Search.ContactSearchResult>();
        CodeKeeper.KeepSerializable<global::ActualChat.Search.ContactSearchResultPage>();
        CodeKeeper.KeepSerializable<global::ActualChat.Search.EntrySearchQuery>();
        CodeKeeper.KeepSerializable<global::ActualChat.Search.EntrySearchResult>();
        CodeKeeper.KeepSerializable<global::ActualChat.Search.EntrySearchResultPage>();
        CodeKeeper.KeepSerializable<global::ActualChat.StreamId>();
        CodeKeeper.KeepSerializable<global::ActualChat.Streaming.VideoStreamInfo>();
        CodeKeeper.KeepSerializable<global::ActualChat.ThreadChatId>();
        CodeKeeper.KeepSerializable<global::ActualChat.Transcription.StringDiff>();
        CodeKeeper.KeepSerializable<global::ActualChat.Transcription.Transcript>();
        CodeKeeper.KeepSerializable<global::ActualChat.Transcription.TranscriptDiff>();
        CodeKeeper.KeepSerializable<global::ActualChat.TranslationId>();
        CodeKeeper.KeepSerializable<global::ActualChat.TranslationSourceId>();
        CodeKeeper.KeepSerializable<global::ActualChat.UploadId>();
        CodeKeeper.KeepSerializable<global::ActualChat.UserDeviceId>();
        CodeKeeper.KeepSerializable<global::ActualChat.UserId>();
        CodeKeeper.KeepSerializable<global::ActualChat.Users.Account>();
        CodeKeeper.KeepSerializable<global::ActualChat.Users.AccountFull>();
        CodeKeeper.KeepSerializable<global::ActualChat.Users.Avatar>();
        CodeKeeper.KeepSerializable<global::ActualChat.Users.AvatarFull>();
        CodeKeeper.KeepSerializable<global::ActualChat.Users.ChatPosition>();
        CodeKeeper.KeepSerializable<global::ActualChat.Users.DigestPreview>();
        CodeKeeper.KeepSerializable<global::ActualChat.Users.DigestPreviewChat>();
        CodeKeeper.KeepSerializable<global::ActualChat.Users.GuestIdOption>();
        CodeKeeper.KeepSerializable<global::ActualChat.Users.LegacySessionInfo>();
        CodeKeeper.KeepSerializable<global::ActualChat.Users.SessionInfo>();
        CodeKeeper.KeepSerializable<global::ActualChat.Users.SessionInfoFull>();
        CodeKeeper.KeepSerializable<global::ActualChat.Users.TimeZone>();
        CodeKeeper.KeepSerializable<global::ActualChat.Users.UserAppSettings>();
        CodeKeeper.KeepSerializable<global::ActualChat.Users.UserAvatarSettings>();
        CodeKeeper.KeepSerializable<global::ActualChat.Users.UserBubbleSettings>();
        CodeKeeper.KeepSerializable<global::ActualChat.Users.UserChatRecordingDetectedLanguage>();
        CodeKeeper.KeepSerializable<global::ActualChat.Users.UserEmailsSettings>();
        CodeKeeper.KeepSerializable<global::ActualChat.Users.UserIdentity>();
        CodeKeeper.KeepSerializable<global::ActualChat.Users.UserLanguageSettings>();
        CodeKeeper.KeepSerializable<global::ActualChat.Users.UserListeningSettings>();
        CodeKeeper.KeepSerializable<global::ActualChat.Users.UserNavbarSettings>();
        CodeKeeper.KeepSerializable<global::ActualChat.Users.UserOnboardingSettings>();
        CodeKeeper.KeepSerializable<global::ActualChat.Users.UserReactionSettings>();
        CodeKeeper.KeepSerializable<global::ActualChat.Users.UserReplaySettings>();
        CodeKeeper.KeepSerializable<global::ActualChat.Users.UserSettings_Set>();
        CodeKeeper.KeepSerializable<global::ActualChat.Users.UserTranscodingTestSettings>();
        CodeKeeper.KeepSerializable<global::ActualChat.Users.UserTranscriptionEngineSettings>();
        CodeKeeper.KeepSerializable<global::ActualChat.Video.VideoFormat>();
        CodeKeeper.KeepSerializable<global::ActualChat.Video.VideoFrame>();
        CodeKeeper.KeepSerializable<global::ActualChat.Video.VideoQualityPreset>();

        // MessagePack formatter types for serializable root types (auto-discovered)
        CodeKeeper.Keep("ActualChat.Internal.StringIdentifierMessagePackFormatter`1[[ActualChat.AliasId, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], ActualChat.Core, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("ActualChat.Internal.StringIdentifierMessagePackFormatter`1[[ActualChat.AuthorId, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], ActualChat.Core, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("ActualChat.Internal.StringIdentifierMessagePackFormatter`1[[ActualChat.ChatEntryId, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], ActualChat.Core, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("ActualChat.Internal.StringIdentifierMessagePackFormatter`1[[ActualChat.ChatId, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], ActualChat.Core, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("ActualChat.Internal.StringIdentifierMessagePackFormatter`1[[ActualChat.ContactId, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], ActualChat.Core, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("ActualChat.Internal.StringIdentifierMessagePackFormatter`1[[ActualChat.ContentId, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], ActualChat.Core, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("ActualChat.Internal.StringIdentifierMessagePackFormatter`1[[ActualChat.ConversationId, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], ActualChat.Core, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("ActualChat.Internal.StringIdentifierMessagePackFormatter`1[[ActualChat.Country, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], ActualChat.Core, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("ActualChat.Internal.StringIdentifierMessagePackFormatter`1[[ActualChat.Email, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], ActualChat.Core, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("ActualChat.Internal.StringIdentifierMessagePackFormatter`1[[ActualChat.Emoji, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], ActualChat.Core, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("ActualChat.Internal.StringIdentifierMessagePackFormatter`1[[ActualChat.ExplicitNotificationId, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], ActualChat.Core, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("ActualChat.Internal.StringIdentifierMessagePackFormatter`1[[ActualChat.ExternalContactId, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], ActualChat.Core, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("ActualChat.Internal.StringIdentifierMessagePackFormatter`1[[ActualChat.GroupChatId, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], ActualChat.Core, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("ActualChat.Internal.StringIdentifierMessagePackFormatter`1[[ActualChat.Interest, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], ActualChat.Core, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("ActualChat.Internal.StringIdentifierMessagePackFormatter`1[[ActualChat.Language, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], ActualChat.Core, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("ActualChat.Internal.StringIdentifierMessagePackFormatter`1[[ActualChat.MediaId, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], ActualChat.Core, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("ActualChat.Internal.StringIdentifierMessagePackFormatter`1[[ActualChat.MentionId, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], ActualChat.Core, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("ActualChat.Internal.StringIdentifierMessagePackFormatter`1[[ActualChat.NotificationId, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], ActualChat.Core, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("ActualChat.Internal.StringIdentifierMessagePackFormatter`1[[ActualChat.PeerChatId, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], ActualChat.Core, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("ActualChat.Internal.StringIdentifierMessagePackFormatter`1[[ActualChat.Phone, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], ActualChat.Core, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("ActualChat.Internal.StringIdentifierMessagePackFormatter`1[[ActualChat.PlaceChatId, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], ActualChat.Core, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("ActualChat.Internal.StringIdentifierMessagePackFormatter`1[[ActualChat.PlaceId, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], ActualChat.Core, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("ActualChat.Internal.StringIdentifierMessagePackFormatter`1[[ActualChat.PrincipalId, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], ActualChat.Core, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("ActualChat.Internal.StringIdentifierMessagePackFormatter`1[[ActualChat.RoleId, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], ActualChat.Core, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("ActualChat.Internal.StringIdentifierMessagePackFormatter`1[[ActualChat.StreamId, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], ActualChat.Core, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("ActualChat.Internal.StringIdentifierMessagePackFormatter`1[[ActualChat.ThreadChatId, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], ActualChat.Core, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("ActualChat.Internal.StringIdentifierMessagePackFormatter`1[[ActualChat.TranslationId, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], ActualChat.Core, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("ActualChat.Internal.StringIdentifierMessagePackFormatter`1[[ActualChat.TranslationSourceId, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], ActualChat.Core, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("ActualChat.Internal.StringIdentifierMessagePackFormatter`1[[ActualChat.UploadId, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], ActualChat.Core, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("ActualChat.Internal.StringIdentifierMessagePackFormatter`1[[ActualChat.UserDeviceId, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], ActualChat.Core, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("ActualChat.Internal.StringIdentifierMessagePackFormatter`1[[ActualChat.UserId, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], ActualChat.Core, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("ActualChat.Serialization.Internal.SetDiffMessagePackFormatter`2[[ActualChat.AuthorId[], ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null],[ActualChat.AuthorId, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], ActualChat.Core, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("ActualLab.Fusion.Internal.SessionMessagePackFormatter, ActualLab.Fusion, Version=12.3.25.16053, Culture=neutral, PublicKeyToken=7c239217ec78b545");
        CodeKeeper.Keep("ActualLab.Serialization.Internal.OptionMessagePackFormatter`1[[ActualChat.Chat.ChatEntryAudio, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], ActualLab.Core, Version=12.3.25.16053, Culture=neutral, PublicKeyToken=7c239217ec78b545");
        CodeKeeper.Keep("ActualLab.Serialization.Internal.OptionMessagePackFormatter`1[[ActualChat.Chat.ChatEntryForwarded, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], ActualLab.Core, Version=12.3.25.16053, Culture=neutral, PublicKeyToken=7c239217ec78b545");
        CodeKeeper.Keep("ActualLab.Serialization.Internal.OptionMessagePackFormatter`1[[ActualChat.Chat.SystemEntry, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], ActualLab.Core, Version=12.3.25.16053, Culture=neutral, PublicKeyToken=7c239217ec78b545");
        CodeKeeper.Keep("ActualLab.Serialization.Internal.OptionMessagePackFormatter`1[[ActualChat.ChatId, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], ActualLab.Core, Version=12.3.25.16053, Culture=neutral, PublicKeyToken=7c239217ec78b545");
        CodeKeeper.Keep("ActualLab.Serialization.Internal.OptionMessagePackFormatter`1[[ActualChat.StreamId, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], ActualLab.Core, Version=12.3.25.16053, Culture=neutral, PublicKeyToken=7c239217ec78b545");
        CodeKeeper.Keep("ActualLab.Serialization.Internal.OptionMessagePackFormatter`1[[ActualChat.UserId, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], ActualLab.Core, Version=12.3.25.16053, Culture=neutral, PublicKeyToken=7c239217ec78b545");
        CodeKeeper.Keep("ActualLab.Serialization.Internal.OptionMessagePackFormatter`1[[ActualLab.Option`1[[ActualChat.Chat.ChatEntryAudio, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], ActualLab.Core, Version=12.3.25.16053, Culture=neutral, PublicKeyToken=7c239217ec78b545]], ActualLab.Core, Version=12.3.25.16053, Culture=neutral, PublicKeyToken=7c239217ec78b545");
        CodeKeeper.Keep("ActualLab.Serialization.Internal.OptionMessagePackFormatter`1[[ActualLab.Option`1[[ActualChat.Chat.ChatEntryForwarded, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], ActualLab.Core, Version=12.3.25.16053, Culture=neutral, PublicKeyToken=7c239217ec78b545]], ActualLab.Core, Version=12.3.25.16053, Culture=neutral, PublicKeyToken=7c239217ec78b545");
        CodeKeeper.Keep("ActualLab.Serialization.Internal.OptionMessagePackFormatter`1[[ActualLab.Option`1[[ActualChat.Chat.SystemEntry, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], ActualLab.Core, Version=12.3.25.16053, Culture=neutral, PublicKeyToken=7c239217ec78b545]], ActualLab.Core, Version=12.3.25.16053, Culture=neutral, PublicKeyToken=7c239217ec78b545");
        CodeKeeper.Keep("ActualLab.Serialization.Internal.OptionMessagePackFormatter`1[[ActualLab.Option`1[[ActualChat.ChatId, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], ActualLab.Core, Version=12.3.25.16053, Culture=neutral, PublicKeyToken=7c239217ec78b545]], ActualLab.Core, Version=12.3.25.16053, Culture=neutral, PublicKeyToken=7c239217ec78b545");
        CodeKeeper.Keep("ActualLab.Serialization.Internal.OptionMessagePackFormatter`1[[ActualLab.Option`1[[ActualChat.StreamId, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], ActualLab.Core, Version=12.3.25.16053, Culture=neutral, PublicKeyToken=7c239217ec78b545]], ActualLab.Core, Version=12.3.25.16053, Culture=neutral, PublicKeyToken=7c239217ec78b545");
        CodeKeeper.Keep("ActualLab.Serialization.Internal.OptionMessagePackFormatter`1[[ActualLab.Option`1[[ActualChat.UserId, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], ActualLab.Core, Version=12.3.25.16053, Culture=neutral, PublicKeyToken=7c239217ec78b545]], ActualLab.Core, Version=12.3.25.16053, Culture=neutral, PublicKeyToken=7c239217ec78b545");
        CodeKeeper.Keep("ActualLab.Serialization.Internal.OptionMessagePackFormatter`1[[ActualLab.Option`1[[System.Nullable`1[[ActualLab.Time.Moment, ActualLab.Core, Version=12.3.25.16053, Culture=neutral, PublicKeyToken=7c239217ec78b545]], System.Private.CoreLib, Version=10.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], ActualLab.Core, Version=12.3.25.16053, Culture=neutral, PublicKeyToken=7c239217ec78b545]], ActualLab.Core, Version=12.3.25.16053, Culture=neutral, PublicKeyToken=7c239217ec78b545");
        CodeKeeper.Keep("ActualLab.Serialization.Internal.OptionMessagePackFormatter`1[[ActualLab.Option`1[[System.Nullable`1[[System.Boolean, System.Private.CoreLib, Version=10.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=10.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], ActualLab.Core, Version=12.3.25.16053, Culture=neutral, PublicKeyToken=7c239217ec78b545]], ActualLab.Core, Version=12.3.25.16053, Culture=neutral, PublicKeyToken=7c239217ec78b545");
        CodeKeeper.Keep("ActualLab.Serialization.Internal.OptionMessagePackFormatter`1[[ActualLab.Option`1[[System.Nullable`1[[System.Int64, System.Private.CoreLib, Version=10.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=10.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], ActualLab.Core, Version=12.3.25.16053, Culture=neutral, PublicKeyToken=7c239217ec78b545]], ActualLab.Core, Version=12.3.25.16053, Culture=neutral, PublicKeyToken=7c239217ec78b545");
        CodeKeeper.Keep("ActualLab.Serialization.Internal.OptionMessagePackFormatter`1[[System.Nullable`1[[ActualLab.Time.Moment, ActualLab.Core, Version=12.3.25.16053, Culture=neutral, PublicKeyToken=7c239217ec78b545]], System.Private.CoreLib, Version=10.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], ActualLab.Core, Version=12.3.25.16053, Culture=neutral, PublicKeyToken=7c239217ec78b545");
        CodeKeeper.Keep("ActualLab.Serialization.Internal.OptionMessagePackFormatter`1[[System.Nullable`1[[System.Boolean, System.Private.CoreLib, Version=10.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=10.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], ActualLab.Core, Version=12.3.25.16053, Culture=neutral, PublicKeyToken=7c239217ec78b545");
        CodeKeeper.Keep("ActualLab.Serialization.Internal.OptionMessagePackFormatter`1[[System.Nullable`1[[System.Int64, System.Private.CoreLib, Version=10.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=10.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], ActualLab.Core, Version=12.3.25.16053, Culture=neutral, PublicKeyToken=7c239217ec78b545");
        CodeKeeper.Keep("ActualLab.Text.Internal.SymbolMessagePackFormatter, ActualLab.Core, Version=12.3.25.16053, Culture=neutral, PublicKeyToken=7c239217ec78b545");
        CodeKeeper.Keep("ActualLab.Time.Internal.MomentMessagePackFormatter, ActualLab.Core, Version=12.3.25.16053, Culture=neutral, PublicKeyToken=7c239217ec78b545");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Audio_AudioFormatFormatter17, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Audio_AudioFrameFormatter18, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_AvatarQueryFormatter19, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Chat_AddChatMembersBannerUserSettingsFormatter20, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Chat_AuthorDiffFormatter24, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Chat_AuthorFormatter21, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Chat_AuthorFullFormatter25, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Chat_AuthorReadPositionFormatter26, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Chat_AuthorRulesFormatter27, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Chat_ChatCopyStateDiffFormatter31, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Chat_ChatCopyStateFormatter30, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Chat_ChatDiffFormatter32, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Chat_ChatEntryAttachmentFormatter40, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Chat_ChatEntryAudioFormatter38, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Chat_ChatEntryDiffFormatter41, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Chat_ChatEntryFormatter33, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Chat_ChatEntryForwardedFormatter37, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Chat_ChatEntryLanguageFormatter42, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Chat_ChatEntryRangeMetaFormatter43, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Chat_ChatFormatter29, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Chat_ChatLanguageTileFormatter45, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Chat_ChatListSettingsFormatter46, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Chat_ChatNewsFormatter47, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Chat_ChatRangeMetaFormatter48, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Chat_ChatTileFormatter49, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Chat_ChatUserSettingsFormatter51, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Chat_ConversationDiffFormatter53, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Chat_ConversationFormatter52, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Chat_ConversationRangeMetaFormatter54, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Chat_LegacyChatEntryFormatter55, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Chat_LegacyChatNewsFormatter56, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Chat_LegacyChatTileFormatter57, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Chat_MembersChangedOptionFormatter35, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Chat_MentionFormatter58, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Chat_MentionMarkupFormatter59, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Chat_MentionSearchResultFormatter60, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Chat_NotifyMembersOptionFormatter36, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Chat_PlaceDiffFormatter65, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Chat_PlaceFormatter63, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Chat_PlaceRulesFormatter64, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Chat_ReactionFormatter66, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Chat_ReactionSummaryFormatter67, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Chat_ReadPositionsStatFormatter68, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Chat_RoleDiffFormatter70, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Chat_RoleFormatter69, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Chat_SystemEntryFormatter34, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Chat_TranslationDiffFormatter72, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Chat_TranslationFormatter71, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Contacts_ContactFormatter73, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Contacts_ContactSubsetFormatter75, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Contacts_ExternalContactFormatter76, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Contacts_ExternalContactFullFormatter77, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Contacts_ExternalContactsHashFormatter78, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Contacts_HashedExternalContactFormatter79, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Contacts_ThreadContactFormatter80, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_ContentLinkInfoFormatter81, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_FakeDeviceContactOptionsFormatter82, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Hashing_HashStringFormatter1, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Invite_ChatInviteOptionFormatter83, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Invite_ChatInviteSettingsFormatter84, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Invite_InviteChatLinkPreviewFormatter89, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Invite_InviteDetailsFormatter86, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Invite_InviteFormatter85, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Invite_PlaceInviteOptionFormatter88, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Invite_UserInviteOptionFormatter87, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Live_LiveAudioFrameFormatter90, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Live_LiveStreamEndFormatter91, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Live_LiveStreamInfoFormatter92, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Live_LiveStreamResetFormatter93, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Live_LiveStreamSettingsFormatter94, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Live_LiveStreamStartFormatter95, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_LocalAppSettingsFormatter96, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_LocalOnboardingSettingsFormatter97, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_LocalUrlFormatter98, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Mathematics_LinearMapDiffFormatter9, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Mathematics_LinearMapFormatter8, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Mathematics_Range`1\\[\\[ActualLab_Time_Moment\\, ActualLab_Core\\]\\]Formatter50, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Mathematics_Range`1\\[\\[System_Int32\\, System_Private_CoreLib\\]\\]Formatter13, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Mathematics_Range`1\\[\\[System_Int64\\, System_Private_CoreLib\\]\\]Formatter44, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Media_GrabStatusFormatter99, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Media_LinkPreviewFormatter39, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Media_MediaFormatter23, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Media_MediaFullFormatter100, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Media_MediaProgressFormatter101, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Media_MediaRefFormatter62, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Media_RecordingPartFormatter102, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Media_UploadFormatter103, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Notification_ChatEntryNotificationOptionFormatter104, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Notification_ChatNotificationOptionFormatter105, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Notification_GetAttentionNotificationOptionFormatter106, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Notification_NotificationFormatter107, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_PictureFormatter61, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Search_ContactSearchQueryFormatter108, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Search_ContactSearchResultFormatter109, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Search_ContactSearchResultPageFormatter110, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Search_EntrySearchQueryFormatter111, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Search_EntrySearchResultFormatter112, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Search_EntrySearchResultPageFormatter113, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Search_SearchMatchFormatter11, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Search_SearchMatchPartFormatter12, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_StoredSettingsFormatter1, MessagePack.Resolvers.DynamicUnionResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Streaming_VideoStreamInfoFormatter114, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Transcription_StringDiffFormatter116, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Transcription_TranscriptDiffFormatter118, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Transcription_TranscriptFormatter117, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Users_AccountFormatter74, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Users_AccountFullFormatter28, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Users_AvatarFormatter22, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Users_AvatarFullFormatter119, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Users_ChatPositionFormatter120, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Users_DigestPreviewChatFormatter122, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Users_DigestPreviewFormatter121, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Users_GuestIdOptionFormatter123, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Users_LegacySessionInfoFormatter124, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Users_SessionInfoFormatter126, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Users_SessionInfoFullFormatter127, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Users_TimeZoneFormatter128, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Users_UserAppSettingsFormatter129, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Users_UserAvatarSettingsFormatter130, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Users_UserBubbleSettingsFormatter131, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Users_UserChatRecordingDetectedLanguageFormatter132, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Users_UserEmailsSettingsFormatter133, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Users_UserIdentityFormatter125, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Users_UserLanguageSettingsFormatter134, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Users_UserListeningSettingsFormatter135, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Users_UserNavbarSettingsFormatter136, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Users_UserOnboardingSettingsFormatter137, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Users_UserReactionSettingsFormatter138, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Users_UserReplaySettingsFormatter139, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Users_UserSettings_SetFormatter140, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Users_UserTranscodingTestSettingsFormatter141, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Users_UserTranscriptionEngineSettingsFormatter142, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Video_VideoFormatFormatter115, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Video_VideoFrameFormatter143, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Video_VideoQualityPresetFormatter144, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ArrayFormatter`1[[ActualChat.AuthorId, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], MessagePack, Version=3.1.4.0, Culture=neutral, PublicKeyToken=b4a0369545f0a1be");
        CodeKeeper.Keep("MessagePack.Formatters.ArrayFormatter`1[[ActualChat.Chat.AuthorReadPosition, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], MessagePack, Version=3.1.4.0, Culture=neutral, PublicKeyToken=b4a0369545f0a1be");
        CodeKeeper.Keep("MessagePack.Formatters.ArrayFormatter`1[[ActualChat.Chat.ChatEntry, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], MessagePack, Version=3.1.4.0, Culture=neutral, PublicKeyToken=b4a0369545f0a1be");
        CodeKeeper.Keep("MessagePack.Formatters.ArrayFormatter`1[[ActualChat.Chat.ChatEntryAttachment, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], MessagePack, Version=3.1.4.0, Culture=neutral, PublicKeyToken=b4a0369545f0a1be");
        CodeKeeper.Keep("MessagePack.Formatters.ArrayFormatter`1[[ActualChat.Chat.ChatEntryLanguage, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], MessagePack, Version=3.1.4.0, Culture=neutral, PublicKeyToken=b4a0369545f0a1be");
        CodeKeeper.Keep("MessagePack.Formatters.ArrayFormatter`1[[ActualChat.Chat.LegacyChatEntry, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], MessagePack, Version=3.1.4.0, Culture=neutral, PublicKeyToken=b4a0369545f0a1be");
        CodeKeeper.Keep("MessagePack.Formatters.ArrayFormatter`1[[ActualChat.ChatId, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], MessagePack, Version=3.1.4.0, Culture=neutral, PublicKeyToken=b4a0369545f0a1be");
        CodeKeeper.Keep("MessagePack.Formatters.ArrayFormatter`1[[ActualChat.Language, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], MessagePack, Version=3.1.4.0, Culture=neutral, PublicKeyToken=b4a0369545f0a1be");
        CodeKeeper.Keep("MessagePack.Formatters.ArrayFormatter`1[[ActualChat.Mathematics.Range`1[[System.Int64, System.Private.CoreLib, Version=10.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], ActualChat.Core, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], MessagePack, Version=3.1.4.0, Culture=neutral, PublicKeyToken=b4a0369545f0a1be");
        CodeKeeper.Keep("MessagePack.Formatters.ArrayFormatter`1[[ActualChat.Media.LinkPreview, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], MessagePack, Version=3.1.4.0, Culture=neutral, PublicKeyToken=b4a0369545f0a1be");
        CodeKeeper.Keep("MessagePack.Formatters.ArrayFormatter`1[[ActualChat.PlaceId, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], MessagePack, Version=3.1.4.0, Culture=neutral, PublicKeyToken=b4a0369545f0a1be");
        CodeKeeper.Keep("MessagePack.Formatters.ArrayFormatter`1[[ActualChat.Search.ContactSearchResult, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], MessagePack, Version=3.1.4.0, Culture=neutral, PublicKeyToken=b4a0369545f0a1be");
        CodeKeeper.Keep("MessagePack.Formatters.ArrayFormatter`1[[ActualChat.Search.EntrySearchResult, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], MessagePack, Version=3.1.4.0, Culture=neutral, PublicKeyToken=b4a0369545f0a1be");
        CodeKeeper.Keep("MessagePack.Formatters.ArrayFormatter`1[[ActualChat.Search.SearchMatchPart, ActualChat.Core, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], MessagePack, Version=3.1.4.0, Culture=neutral, PublicKeyToken=b4a0369545f0a1be");
        CodeKeeper.Keep("MessagePack.Formatters.ArrayFormatter`1[[ActualChat.Users.DigestPreviewChat, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], MessagePack, Version=3.1.4.0, Culture=neutral, PublicKeyToken=b4a0369545f0a1be");
        CodeKeeper.Keep("MessagePack.Formatters.ArrayFormatter`1[[ActualLab.Collections.Internal.PropertyBagItem, ActualLab.Core, Version=12.3.25.16053, Culture=neutral, PublicKeyToken=7c239217ec78b545]], MessagePack, Version=3.1.4.0, Culture=neutral, PublicKeyToken=b4a0369545f0a1be");
        CodeKeeper.Keep("MessagePack.Formatters.ArrayFormatter`1[[ActualLab.Text.Symbol, ActualLab.Core, Version=12.3.25.16053, Culture=neutral, PublicKeyToken=7c239217ec78b545]], MessagePack, Version=3.1.4.0, Culture=neutral, PublicKeyToken=b4a0369545f0a1be");
        CodeKeeper.Keep("MessagePack.Formatters.ByteArrayFormatter, MessagePack, Version=3.1.4.0, Culture=neutral, PublicKeyToken=b4a0369545f0a1be");
        CodeKeeper.Keep("MessagePack.Formatters.DictionaryFormatter`2[[System.String, System.Private.CoreLib, Version=10.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Int32, System.Private.CoreLib, Version=10.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], MessagePack, Version=3.1.4.0, Culture=neutral, PublicKeyToken=b4a0369545f0a1be");
        CodeKeeper.Keep("MessagePack.Formatters.GenericCollectionFormatter`2[[System.String, System.Private.CoreLib, Version=10.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[ActualLab.Api.ApiSet`1[[System.String, System.Private.CoreLib, Version=10.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], ActualLab.Core, Version=12.3.25.16053, Culture=neutral, PublicKeyToken=7c239217ec78b545]], MessagePack, Version=3.1.4.0, Culture=neutral, PublicKeyToken=b4a0369545f0a1be");
        CodeKeeper.Keep("MessagePack.Formatters.GenericDictionaryFormatter`3[[System.String, System.Private.CoreLib, Version=10.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.String, System.Private.CoreLib, Version=10.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[ActualLab.Api.ApiMap`2[[System.String, System.Private.CoreLib, Version=10.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.String, System.Private.CoreLib, Version=10.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], ActualLab.Core, Version=12.3.25.16053, Culture=neutral, PublicKeyToken=7c239217ec78b545]], MessagePack, Version=3.1.4.0, Culture=neutral, PublicKeyToken=b4a0369545f0a1be");
        CodeKeeper.Keep("MessagePack.Formatters.GenericEnumFormatter`1[[ActualChat.Audio.AudioCodecKind, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], MessagePack, Version=3.1.4.0, Culture=neutral, PublicKeyToken=b4a0369545f0a1be");
        CodeKeeper.Keep("MessagePack.Formatters.GenericEnumFormatter`1[[ActualChat.Chat.ChatEntryFlags, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], MessagePack, Version=3.1.4.0, Culture=neutral, PublicKeyToken=b4a0369545f0a1be");
        CodeKeeper.Keep("MessagePack.Formatters.GenericEnumFormatter`1[[ActualChat.Chat.ChatListOrder, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], MessagePack, Version=3.1.4.0, Culture=neutral, PublicKeyToken=b4a0369545f0a1be");
        CodeKeeper.Keep("MessagePack.Formatters.GenericEnumFormatter`1[[ActualChat.Chat.ChatPermissions, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], MessagePack, Version=3.1.4.0, Culture=neutral, PublicKeyToken=b4a0369545f0a1be");
        CodeKeeper.Keep("MessagePack.Formatters.GenericEnumFormatter`1[[ActualChat.Chat.PlacePermissions, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], MessagePack, Version=3.1.4.0, Culture=neutral, PublicKeyToken=b4a0369545f0a1be");
        CodeKeeper.Keep("MessagePack.Formatters.GenericEnumFormatter`1[[ActualChat.Chat.SystemRole, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], MessagePack, Version=3.1.4.0, Culture=neutral, PublicKeyToken=b4a0369545f0a1be");
        CodeKeeper.Keep("MessagePack.Formatters.GenericEnumFormatter`1[[ActualChat.ChatKind, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], MessagePack, Version=3.1.4.0, Culture=neutral, PublicKeyToken=b4a0369545f0a1be");
        CodeKeeper.Keep("MessagePack.Formatters.GenericEnumFormatter`1[[ActualChat.Contacts.ContactSubsetKind, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], MessagePack, Version=3.1.4.0, Culture=neutral, PublicKeyToken=b4a0369545f0a1be");
        CodeKeeper.Keep("MessagePack.Formatters.GenericEnumFormatter`1[[ActualChat.Live.LiveStreamKind, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], MessagePack, Version=3.1.4.0, Culture=neutral, PublicKeyToken=b4a0369545f0a1be");
        CodeKeeper.Keep("MessagePack.Formatters.GenericEnumFormatter`1[[ActualChat.Media.LinkPreviewMode, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], MessagePack, Version=3.1.4.0, Culture=neutral, PublicKeyToken=b4a0369545f0a1be");
        CodeKeeper.Keep("MessagePack.Formatters.GenericEnumFormatter`1[[ActualChat.Media.MediaKind, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], MessagePack, Version=3.1.4.0, Culture=neutral, PublicKeyToken=b4a0369545f0a1be");
        CodeKeeper.Keep("MessagePack.Formatters.GenericEnumFormatter`1[[ActualChat.Media.MediaProcessingStage, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], MessagePack, Version=3.1.4.0, Culture=neutral, PublicKeyToken=b4a0369545f0a1be");
        CodeKeeper.Keep("MessagePack.Formatters.GenericEnumFormatter`1[[ActualChat.Media.RecordingEventKind, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], MessagePack, Version=3.1.4.0, Culture=neutral, PublicKeyToken=b4a0369545f0a1be");
        CodeKeeper.Keep("MessagePack.Formatters.GenericEnumFormatter`1[[ActualChat.Search.SearchScope, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], MessagePack, Version=3.1.4.0, Culture=neutral, PublicKeyToken=b4a0369545f0a1be");
        CodeKeeper.Keep("MessagePack.Formatters.GenericEnumFormatter`1[[ActualChat.Streaming.StreamKind, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], MessagePack, Version=3.1.4.0, Culture=neutral, PublicKeyToken=b4a0369545f0a1be");
        CodeKeeper.Keep("MessagePack.Formatters.GenericEnumFormatter`1[[ActualChat.Transcription.TranscriptionEngine, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], MessagePack, Version=3.1.4.0, Culture=neutral, PublicKeyToken=b4a0369545f0a1be");
        CodeKeeper.Keep("MessagePack.Formatters.GenericEnumFormatter`1[[ActualChat.TranslationIdKind, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], MessagePack, Version=3.1.4.0, Culture=neutral, PublicKeyToken=b4a0369545f0a1be");
        CodeKeeper.Keep("MessagePack.Formatters.GenericEnumFormatter`1[[ActualChat.Users.AccountStatus, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], MessagePack, Version=3.1.4.0, Culture=neutral, PublicKeyToken=b4a0369545f0a1be");
        CodeKeeper.Keep("MessagePack.Formatters.GenericEnumFormatter`1[[ActualChat.Users.AvatarFormat, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], MessagePack, Version=3.1.4.0, Culture=neutral, PublicKeyToken=b4a0369545f0a1be");
        CodeKeeper.Keep("MessagePack.Formatters.GenericEnumFormatter`1[[ActualChat.Users.AvatarKind, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], MessagePack, Version=3.1.4.0, Culture=neutral, PublicKeyToken=b4a0369545f0a1be");
        CodeKeeper.Keep("MessagePack.Formatters.GenericEnumFormatter`1[[ActualChat.Users.ChatNotificationMode, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], MessagePack, Version=3.1.4.0, Culture=neutral, PublicKeyToken=b4a0369545f0a1be");
        CodeKeeper.Keep("MessagePack.Formatters.GenericEnumFormatter`1[[ActualChat.Users.ListeningMode, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], MessagePack, Version=3.1.4.0, Culture=neutral, PublicKeyToken=b4a0369545f0a1be");
        CodeKeeper.Keep("MessagePack.Formatters.GenericEnumFormatter`1[[ActualChat.Users.VoiceMode, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], MessagePack, Version=3.1.4.0, Culture=neutral, PublicKeyToken=b4a0369545f0a1be");
        CodeKeeper.Keep("MessagePack.Formatters.GenericEnumFormatter`1[[ActualChat.Video.VideoQualityLevel, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], MessagePack, Version=3.1.4.0, Culture=neutral, PublicKeyToken=b4a0369545f0a1be");
        CodeKeeper.Keep("MessagePack.Formatters.InterfaceCollectionFormatter2`1[[ActualLab.Serialization.NewtonsoftJsonSerialized`1[[System.Object, System.Private.CoreLib, Version=10.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], ActualLab.Core, Version=12.3.25.16053, Culture=neutral, PublicKeyToken=7c239217ec78b545]], MessagePack, Version=3.1.4.0, Culture=neutral, PublicKeyToken=b4a0369545f0a1be");
        CodeKeeper.Keep("MessagePack.Formatters.InterfaceCollectionFormatter2`1[[System.String, System.Private.CoreLib, Version=10.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], MessagePack, Version=3.1.4.0, Culture=neutral, PublicKeyToken=b4a0369545f0a1be");
        CodeKeeper.Keep("MessagePack.Formatters.InterfaceDictionaryFormatter`2[[System.String, System.Private.CoreLib, Version=10.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[ActualLab.Serialization.NewtonsoftJsonSerialized`1[[System.Object, System.Private.CoreLib, Version=10.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], ActualLab.Core, Version=12.3.25.16053, Culture=neutral, PublicKeyToken=7c239217ec78b545]], MessagePack, Version=3.1.4.0, Culture=neutral, PublicKeyToken=b4a0369545f0a1be");
        CodeKeeper.Keep("MessagePack.Formatters.InterfaceReadOnlyListFormatter`1[[ActualChat.AuthorId, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], MessagePack, Version=3.1.4.0, Culture=neutral, PublicKeyToken=b4a0369545f0a1be");
        CodeKeeper.Keep("MessagePack.Formatters.InterfaceReadOnlyListFormatter`1[[ActualChat.RoleId, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], MessagePack, Version=3.1.4.0, Culture=neutral, PublicKeyToken=b4a0369545f0a1be");
        CodeKeeper.Keep("MessagePack.Formatters.NullableBooleanFormatter, MessagePack, Version=3.1.4.0, Culture=neutral, PublicKeyToken=b4a0369545f0a1be");
        CodeKeeper.Keep("MessagePack.Formatters.NullableFormatter`1[[ActualChat.Chat.ChatPermissions, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], MessagePack, Version=3.1.4.0, Culture=neutral, PublicKeyToken=b4a0369545f0a1be");
        CodeKeeper.Keep("MessagePack.Formatters.NullableFormatter`1[[ActualChat.Chat.SystemRole, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], MessagePack, Version=3.1.4.0, Culture=neutral, PublicKeyToken=b4a0369545f0a1be");
        CodeKeeper.Keep("MessagePack.Formatters.NullableFormatter`1[[ActualChat.ChatKind, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], MessagePack, Version=3.1.4.0, Culture=neutral, PublicKeyToken=b4a0369545f0a1be");
        CodeKeeper.Keep("MessagePack.Formatters.NullableFormatter`1[[ActualChat.Hashing.HashString, ActualChat.Core, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], MessagePack, Version=3.1.4.0, Culture=neutral, PublicKeyToken=b4a0369545f0a1be");
        CodeKeeper.Keep("MessagePack.Formatters.NullableFormatter`1[[ActualChat.Mathematics.Range`1[[System.Int64, System.Private.CoreLib, Version=10.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], ActualChat.Core, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], MessagePack, Version=3.1.4.0, Culture=neutral, PublicKeyToken=b4a0369545f0a1be");
        CodeKeeper.Keep("MessagePack.Formatters.NullableFormatter`1[[ActualChat.Media.LinkPreviewMode, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], MessagePack, Version=3.1.4.0, Culture=neutral, PublicKeyToken=b4a0369545f0a1be");
        CodeKeeper.Keep("MessagePack.Formatters.NullableFormatter`1[[ActualLab.Text.Symbol, ActualLab.Core, Version=12.3.25.16053, Culture=neutral, PublicKeyToken=7c239217ec78b545]], MessagePack, Version=3.1.4.0, Culture=neutral, PublicKeyToken=b4a0369545f0a1be");
        CodeKeeper.Keep("MessagePack.Formatters.NullableFormatter`1[[ActualLab.Time.Moment, ActualLab.Core, Version=12.3.25.16053, Culture=neutral, PublicKeyToken=7c239217ec78b545]], MessagePack, Version=3.1.4.0, Culture=neutral, PublicKeyToken=b4a0369545f0a1be");
        CodeKeeper.Keep("MessagePack.Formatters.NullableInt32Formatter, MessagePack, Version=3.1.4.0, Culture=neutral, PublicKeyToken=b4a0369545f0a1be");
        CodeKeeper.Keep("MessagePack.Formatters.NullableInt64Formatter, MessagePack, Version=3.1.4.0, Culture=neutral, PublicKeyToken=b4a0369545f0a1be");
        CodeKeeper.Keep("MessagePack.Formatters.NullableStringArrayFormatter, MessagePack, Version=3.1.4.0, Culture=neutral, PublicKeyToken=b4a0369545f0a1be");
        CodeKeeper.Keep("MessagePack.Formatters.SingleArrayFormatter, MessagePack, Version=3.1.4.0, Culture=neutral, PublicKeyToken=b4a0369545f0a1be");
        CodeKeeper.Keep("MessagePack.Formatters.StaticNullableFormatter`1[[System.TimeSpan, System.Private.CoreLib, Version=10.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], MessagePack, Version=3.1.4.0, Culture=neutral, PublicKeyToken=b4a0369545f0a1be");
        CodeKeeper.Keep("MessagePack.Formatters.Vector2Formatter, MessagePack, Version=3.1.4.0, Culture=neutral, PublicKeyToken=b4a0369545f0a1be");
        CodeKeeper.Keep("MessagePack.GeneratedMessagePackResolver+ActualLab+Collections+ImmutableOptionSetFormatter, ActualLab.Core, Version=12.3.25.16053, Culture=neutral, PublicKeyToken=7c239217ec78b545");
        CodeKeeper.Keep("MessagePack.GeneratedMessagePackResolver+ActualLab+Collections+Internal+PropertyBagItemFormatter, ActualLab.Core, Version=12.3.25.16053, Culture=neutral, PublicKeyToken=7c239217ec78b545");
        CodeKeeper.Keep("MessagePack.GeneratedMessagePackResolver+ActualLab+Collections+PropertyBagFormatter, ActualLab.Core, Version=12.3.25.16053, Culture=neutral, PublicKeyToken=7c239217ec78b545");
        CodeKeeper.Keep("MessagePack.GeneratedMessagePackResolver+ActualLab+Serialization+NewtonsoftJsonSerializedFormatter`1[[System.Object, System.Private.CoreLib, Version=10.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], ActualLab.Core, Version=12.3.25.16053, Culture=neutral, PublicKeyToken=7c239217ec78b545");
        CodeKeeper.Keep("MessagePack.GeneratedMessagePackResolver+ActualLab+Serialization+TypeDecoratingUniSerializedFormatter`1[[System.Object, System.Private.CoreLib, Version=10.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], ActualLab.Core, Version=12.3.25.16053, Culture=neutral, PublicKeyToken=7c239217ec78b545");
        CodeKeeper.Keep("MessagePack.ImmutableCollection.ImmutableListFormatter`1[[ActualChat.AuthorId, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], MessagePack, Version=3.1.4.0, Culture=neutral, PublicKeyToken=b4a0369545f0a1be");
    }

    public (Type, AotTypeKind)[] ListTypes()
        => [
            (typeof(global::ActualChat.AliasId), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Audio.AudioFormat), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Audio.AudioFrame), AotTypeKind.Serializable),
            (typeof(global::ActualChat.AuthorId), AotTypeKind.Serializable),
            (typeof(global::ActualChat.AvatarQuery), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Chat.AddChatMembersBannerUserSettings), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Chat.Author), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Chat.AuthorDiff), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Chat.AuthorFull), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Chat.AuthorReadPosition), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Chat.AuthorRules), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Chat.Chat), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Chat.ChatCopyState), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Chat.ChatCopyStateDiff), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Chat.ChatDiff), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Chat.ChatEntry), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Chat.ChatEntryAttachment), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Chat.ChatEntryAudio), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Chat.ChatEntryDiff), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Chat.ChatEntryForwarded), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Chat.ChatEntryLanguage), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Chat.ChatEntryRangeMeta), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Chat.ChatLanguageTile), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Chat.ChatListSettings), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Chat.ChatNews), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Chat.ChatRangeMeta), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Chat.ChatTile), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Chat.ChatUserSettings), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Chat.Conversation), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Chat.ConversationDiff), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Chat.ConversationRangeMeta), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Chat.LegacyChatEntry), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Chat.LegacyChatNews), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Chat.LegacyChatTile), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Chat.MembersChangedOption), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Chat.Mention), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Chat.MentionMarkup), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Chat.MentionSearchResult), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Chat.NotifyMembersOption), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Chat.Place), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Chat.PlaceDiff), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Chat.PlaceRules), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Chat.Reaction), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Chat.ReactionSummary), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Chat.ReadPositionsStat), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Chat.Role), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Chat.RoleDiff), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Chat.SystemEntry), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Chat.Translation), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Chat.TranslationDiff), AotTypeKind.Serializable),
            (typeof(global::ActualChat.ChatEntryId), AotTypeKind.Serializable),
            (typeof(global::ActualChat.ChatId), AotTypeKind.Serializable),
            (typeof(global::ActualChat.ContactId), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Contacts.Contact), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Contacts.ContactSubset), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Contacts.ExternalContact), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Contacts.ExternalContactFull), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Contacts.ExternalContactsHash), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Contacts.HashedExternalContact), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Contacts.ThreadContact), AotTypeKind.Serializable),
            (typeof(global::ActualChat.ContentId), AotTypeKind.Serializable),
            (typeof(global::ActualChat.ContentLinkInfo), AotTypeKind.Serializable),
            (typeof(global::ActualChat.ConversationId), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Country), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Email), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Emoji), AotTypeKind.Serializable),
            (typeof(global::ActualChat.ExplicitNotificationId), AotTypeKind.Serializable),
            (typeof(global::ActualChat.ExternalContactId), AotTypeKind.Serializable),
            (typeof(global::ActualChat.FakeDeviceContactOptions), AotTypeKind.Serializable),
            (typeof(global::ActualChat.GroupChatId), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Interest), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Invite.ChatInviteOption), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Invite.ChatInviteSettings), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Invite.Invite), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Invite.InviteChatLinkPreview), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Invite.InviteDetails), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Invite.PlaceInviteOption), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Invite.UserInviteOption), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Language), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Live.LiveAudioFrame), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Live.LiveStreamEnd), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Live.LiveStreamInfo), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Live.LiveStreamReset), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Live.LiveStreamSettings), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Live.LiveStreamStart), AotTypeKind.Serializable),
            (typeof(global::ActualChat.LocalAppSettings), AotTypeKind.Serializable),
            (typeof(global::ActualChat.LocalOnboardingSettings), AotTypeKind.Serializable),
            (typeof(global::ActualChat.LocalUrl), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Media.GrabStatus), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Media.LinkPreview), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Media.Media), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Media.MediaFull), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Media.MediaProgress), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Media.MediaRef), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Media.RecordingPart), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Media.Upload), AotTypeKind.Serializable),
            (typeof(global::ActualChat.MediaId), AotTypeKind.Serializable),
            (typeof(global::ActualChat.MentionId), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Notification.ChatEntryNotificationOption), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Notification.ChatNotificationOption), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Notification.GetAttentionNotificationOption), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Notification.Notification), AotTypeKind.Serializable),
            (typeof(global::ActualChat.NotificationId), AotTypeKind.Serializable),
            (typeof(global::ActualChat.PeerChatId), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Phone), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Picture), AotTypeKind.Serializable),
            (typeof(global::ActualChat.PlaceChatId), AotTypeKind.Serializable),
            (typeof(global::ActualChat.PlaceId), AotTypeKind.Serializable),
            (typeof(global::ActualChat.PrincipalId), AotTypeKind.Serializable),
            (typeof(global::ActualChat.RoleId), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Search.ContactSearchQuery), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Search.ContactSearchResult), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Search.ContactSearchResultPage), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Search.EntrySearchQuery), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Search.EntrySearchResult), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Search.EntrySearchResultPage), AotTypeKind.Serializable),
            (typeof(global::ActualChat.StreamId), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Streaming.VideoStreamInfo), AotTypeKind.Serializable),
            (typeof(global::ActualChat.ThreadChatId), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Transcription.StringDiff), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Transcription.Transcript), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Transcription.TranscriptDiff), AotTypeKind.Serializable),
            (typeof(global::ActualChat.TranslationId), AotTypeKind.Serializable),
            (typeof(global::ActualChat.TranslationSourceId), AotTypeKind.Serializable),
            (typeof(global::ActualChat.UploadId), AotTypeKind.Serializable),
            (typeof(global::ActualChat.UserDeviceId), AotTypeKind.Serializable),
            (typeof(global::ActualChat.UserId), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Users.Account), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Users.AccountFull), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Users.Avatar), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Users.AvatarFull), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Users.ChatPosition), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Users.DigestPreview), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Users.DigestPreviewChat), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Users.GuestIdOption), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Users.LegacySessionInfo), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Users.SessionInfo), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Users.SessionInfoFull), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Users.TimeZone), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Users.UserAppSettings), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Users.UserAvatarSettings), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Users.UserBubbleSettings), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Users.UserChatRecordingDetectedLanguage), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Users.UserEmailsSettings), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Users.UserIdentity), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Users.UserLanguageSettings), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Users.UserListeningSettings), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Users.UserNavbarSettings), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Users.UserOnboardingSettings), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Users.UserReactionSettings), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Users.UserReplaySettings), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Users.UserSettings_Set), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Users.UserTranscodingTestSettings), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Users.UserTranscriptionEngineSettings), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Video.VideoFormat), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Video.VideoFrame), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Video.VideoQualityPreset), AotTypeKind.Serializable),
        ];
}
