env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking

parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
  tsconfigRootDir: '.'
  project: src/nodejs/tsconfig.json
plugins:
  - '@typescript-eslint'
  - prettier
rules:
  indent: "off"
  "@typescript-eslint/indent": ["error", 4]
  quotes: ["error", "single", { "allowTemplateLiterals": true, "avoidEscape": true, }]
  no-console: off
#  no-console: "warn"
