env:
  browser: true
  es2021: true
extends:
  - airbnb-base
  - airbnb-typescript/base
  - prettier
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
  tsconfigRootDir: '.'
  project: './tsconfig.json'
plugins:
  - '@typescript-eslint'
  - prettier
rules:
  indent: ["error", 4]
  "@typescript-eslint/indent": ["error", 4]
