env:
  browser: true
  es2021: true
extends:
  - airbnb-base
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
  tsconfigRootDir: '.'
plugins:
  - '@typescript-eslint'
rules:
  indent: ["error", 4]
