// @ts-check
"use strict";
const path = require('path');
const fs = require('fs');
const plugin = require('tailwindcss/plugin');
/**
 * @param {string} file
 */
function _(file) {
  return path.normalize(path.resolve(__dirname, file));
}

const dirs = fs.readdirSync(_('./../dotnet/'), { withFileTypes: true })
  .filter(d => d.isDirectory() && d.name.indexOf("UI.Blazor") >= 0)
  .map(d => `${_(`./../dotnet/${d.name}`)}${path.sep}**/*.{razor,cshtml}`)
  .concat(`${_('./../dotnet/App.Server')}${path.sep}**/*.{razor,cshtml}`);

module.exports = {
  content: dirs,
  safelist: [
    // Used by in Avatar sizes and skeletons
    'w-9',
    'w-10',
    'w-11',
    'w-12',
    'w-14',
    'w-16',
    'w-17',
    'w-20',
    'w-24',
    'w-28',
    'w-30',
    'w-32',
    'w-36',
    'w-40',
    'h-9',
    'h-10',
    'h-11',
    'h-12',
    'h-14',
    'h-16',
    'h-17',
    'h-20',
    'h-24',
    'h-28',
    'h-30',
    'h-32',
    'h-36',
    'h-40',
    'max-h-17',
    'max-w-17',
    'min-h-17',
    'min-w-17',
    'min-w-88',
    'min-h-120',
    'min-h-128',
    'rounded-4xl',
    'rounded-5xl',
    '-r-46',
    'flex-x',
    '-flex-x',
    'flex-y',
    '-flex-y',
  ],
  presets: [],
  darkMode: 'media',
  theme: {
    extend: {
      backdropBlur: {
        xs: '2px',
      },
      colors: {
        'counter': 'var(--counter)',
        'counter-navgroup': 'var(--counter-navgroup)',
        'icons-01': 'var(--icons-01)',
        'icons-02': 'var(--icons-02)',
        'icons-03': 'var(--icons-03)',
        'icons-04': 'var(--icons-04)',
        'error-toast-body': 'var(--error-toast-body)',
        'error-toast-text': 'var(--error-toast-text)',
        'success': 'var(--success)',
        'audio-message': 'var(--audio-message)',
        'online': 'var(--online)',
        'away': 'var(--away)',
        'unread': 'var(--unread)',
        'separator': 'var(--separator)',
        'placeholder': 'var(--placeholder)',
        'white': 'var(--white)',
        'rating': 'var(--rating)',

        'disabled': 'var(--disabled)',
        'primary': 'var(--primary)',
        'accent': 'var(--accent)',
        'primary-hover': 'var(--primary-hover)',
        'primary-title': 'var(--primary-title)',
        'reaction-own': 'var(--reaction-own)',
        'secondary': 'var(--secondary)',
        'secondary-hover': 'var(--secondary-hover)',
        'secondary-title': 'var(--secondary-title)',
        'cancel': 'var(--cancel)',
        'cancel-hover': 'var(--cancel-hover)',
        'cancel-title': 'var(--cancel-title)',
        'outline': 'var(--outline)',
        'outline-hover': 'var(--outline-hover)',
        'outline-title': 'var(--outline-title)',

        'error': 'var(--error)',
        'error-hover': 'var(--error-hover)',
        'error-title': 'var(--error-title)',
        'error-ring': 'var(--error-ring)',
        'error-outline-hover': 'var(--error-outline-hover)',
        'error-outline-title': 'var(--error-outline-title)',
        'square': 'var(--square)',
        'square-hover': 'var(--square-hover)',
        'square-active': 'var(--square-active)',
        'square-focus': 'var(--square-focus)',
        'square-title': 'var(--square-title)',
        'round': 'var(--round)',
        'round-hover': 'var(--round-hover)',
        'round-active': 'var(--round-active)',
        'round-focus': 'var(--round-focus)',
        'round-title': 'var(--round-title)',
        'header-btn-active': 'var(--round-active)',
        'recorder': 'var(--recorder)',
        'recorder-hover': 'var(--recorder-hover)',
        'recorder-title': 'var(--recorder-title)',
        'code': 'var(--code)',
        'avatar': 'var(--avatar)',
        'recorder-on': 'var(--recorder-on)',
        'toggle-on': 'var(--toggle-on)',
        'toggle-hover': 'var(--toggle-hover)',
        'message-hover': 'var(--message-hover)',
        'mention-other': 'var(--mention-other)',
        'mention-other-text': 'var(--mention-other-text)',
        'mention-own': 'var(--mention-own)',
        'mention-own-border': 'var(--mention-own-border)',
        'mention-own-text': 'var(--mention-own-text)',
        'mention-invalid': 'var(--mention-invalid)',
        'mention-invalid-text': 'var(--mention-invalid-text)',
        'mention-list-item-selected': 'var(--mention-list-item-selected)',
        'mention-message': 'var(--mention-message)',
        'mention-message-hover': 'var(--mention-message-hover)',
        'replied-message': 'var(--replied-message)',
        'replied-message-hover': 'var(--replied-message-hover)',
        'replied-message-border': 'var(--replied-message-border)',
        'context-menu': 'var(--context-menu)',
        'context-border': 'var(--context-border)',
        'selection': 'var(--selection)',
        'dot': 'var(--dot)',
        'dot-selected': 'var(--dot-selected)',
        'shadow-main': 'var(--background-04)',
        'skeleton': 'var(--skeleton)',
        'skeleton-border': 'var(--skeleton-border)',
        'scrollbar': 'var(--scrollbar)',
        'quote': 'var(--quote)',
        'selected': 'var(--selected)',
        'hover': 'var(--hover)',
        'place': 'var(--place)',
        'badge': 'var(--badge)',
        'bubble': 'var(--bubble)',
        'new-separator': 'var(--new-separator)',
        'menuitem-hover': 'var(--menuitem-hover)',
        'menuitem-hover-warning': 'var(--menuitem-hover-warning)',
        'gradient-stop-01': 'var(--gradient-stop-01)',
        'gradient-stop-02': 'var(--gradient-stop-02)',
        'bubble-btn-hover': 'var(--bubble-btn-hover)',
      },
      textColor: {
        '01': 'var(--text-01)',
        '02': 'var(--text-02)',
        '03': 'var(--text-03)',
        '04': 'var(--text-04)',
        '05': 'var(--text-05)',
        '06': 'var(--text-06)',
        'banner-warning': 'var(--text-banner-warning)',
        'banner-error': 'var(--text-banner-error)',
        'banner-info': 'var(--text-banner-info)',
        'banner-success': 'var(--text-banner-success)',
      },
      borderColor: {
        'bg-01': 'var(--background-01)',
        'text-01': 'var(--text-01)',
        'bg-02': 'var(--background-02)',
        'text-02': 'var(--text-02)',
        'bg-03': 'var(--background-03)',
        'text-03': 'var(--text-03)',
        'bg-04': 'var(--background-04)',
        'text-04': 'var(--text-04)',
        'bg-05': 'var(--background-05)',
        'text-05': 'var(--text-05)',
        'bg-06': 'var(--background-06)',
        'bg-07': 'var(--background-07)',
        'accent': 'var(--accent)',
      },
      backgroundColor: {
        '01': 'var(--background-01)',
        '02': 'var(--background-02)',
        '03': 'var(--background-03)',
        '04': 'var(--background-04)',
        '05': 'var(--background-05)',
        '06': 'var(--background-06)',
        '07': 'var(--background-07)',
        '08': 'var(--background-08)',
        '09': 'var(--text-03)',
        'banner-warning': 'var(--background-banner-warning)',
        'banner-error': 'var(--background-banner-error)',
        'banner-info': 'var(--background-banner-info)',
        'banner-success': 'var(--background-banner-success)',
        'recording-countdown': 'var(--background-recording-countdown)',
        'accent': 'var(--accent)',
      },
    },
    screens: {
      sm: '640px',
      md: '1024px',
      lg: '1280px',
      xl: '1536px',
      '2xl': '1800px',
    },
    colors: ({ colors }) => ({
      inherit: colors.inherit,
      current: colors.current,
      transparent: colors.transparent,
      black: colors.black,
      white: colors.white,
      slate: colors.slate,
      gray: colors.gray,
      zinc: colors.zinc,
      neutral: colors.neutral,
      stone: colors.stone,
      red: colors.red,
      orange: colors.orange,
      amber: colors.amber,
      yellow: colors.yellow,
      lime: colors.lime,
      green: colors.green,
      emerald: colors.emerald,
      teal: colors.teal,
      cyan: colors.cyan,
      sky: colors.sky,
      blue: colors.blue,
      indigo: colors.indigo,
      violet: colors.violet,
      purple: colors.purple,
      fuchsia: colors.fuchsia,
      pink: colors.pink,
      rose: colors.rose,
    }),
    columns: {
      auto: 'auto',
      1: '1',
      2: '2',
      3: '3',
      4: '4',
      5: '5',
      6: '6',
      7: '7',
      8: '8',
      9: '9',
      10: '10',
      11: '11',
      12: '12',
      '3xs': '16rem',
      '2xs': '18rem',
      xs: '20rem',
      sm: '24rem',
      md: '28rem',
      lg: '32rem',
      xl: '36rem',
      '2xl': '42rem',
      '3xl': '48rem',
      '4xl': '56rem',
      '5xl': '64rem',
      '6xl': '72rem',
      '7xl': '80rem',
    },
    spacing: {
      px: '1px',
      0: '0px',
      0.25: '0.065rem',
      0.5: '0.125rem',
      0.75: '0.195rem',
      1: '0.25rem',
      1.5: '0.375rem',
      1.75: '0.415rem',
      2: '0.5rem',
      2.5: '0.625rem',
      3: '0.75rem',
      3.5: '0.875rem',
      4: '1rem',
      4.5: '1.125rem',
      5: '1.25rem',
      6: '1.5rem',
      7: '1.75rem',
      8: '2rem',
      9: '2.25rem',
      10: '2.5rem',
      11: '2.75rem',
      12: '3rem',
      14: '3.5rem',
      15: '3.75rem',
      16: '4rem',
      17: '4.25rem',
      18: '4.5rem',
      20: '5rem',
      22: '5.5rem',
      24: '6rem',
      28: '7rem',
      30: '7.5rem',
      32: '8rem',
      34: '8.5rem',
      36: '9rem',
      40: '10rem',
      44: '11rem',
      46: '11.5rem',
      48: '12rem',
      52: '13rem',
      56: '14rem',
      60: '15rem',
      64: '16rem',
      72: '18rem',
      80: '20rem',
      82: '20.5rem',
      84: '21rem',
      88: '22rem',
      90: '22.5rem',
      96: '24rem',
      100: '25rem',
      110: '27.5rem',
      120: '30rem',
      128: '32rem',
      132: '33rem',
      136: '34rem',
      144: '36rem',
      160: '40rem',
      164: '41rem',
      180: '45rem',
      240: '60rem',
      320: '80rem',
    },
    'relativeSpacing' : {
      '1/2': '50%',
      '2/3': '66.666666%',
      '3/4': '75%',
      '4/5': '80%',
      '5/6': '83.333333%',
    },
    animation: {
      none: 'none',
      spin: 'spin 1s linear infinite',
      ping: 'ping 1s cubic-bezier(0, 0, 0.2, 1) infinite',
      pulse: 'pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
      'pulse-70': 'pulse-70 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
      'custom-pulse': 'custom-pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
      'swipe-by': 'swipe-by 2s infinite',
      'scale': 'scale 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
      'decrease': 'decrease 500ms ease-in-out',
      'increase': 'increase 500ms ease-in-out',
      bounce: 'bounce 1s infinite',
      'instant-display': 'display-element-from-left 0s',
      'display-from-left': 'display-element-from-left 150ms ease-in-out',
      'display-from-right': 'display-element-from-right 150ms ease-in-out',
      'display-from-top': 'display-element-from-top 150ms ease-in-out',
      'display-from-bottom': 'display-element-from-bottom 150ms ease-in-out',
      'display-from-left-slow': 'display-element-from-left 300ms ease-in-out',
      'display-from-right-slow': 'display-element-from-right 300ms ease-in-out',
      'display-from-top-slow': 'display-element-from-top 300ms ease-in-out',
      'display-from-bottom-slow': 'display-element-from-bottom 300ms ease-in-out',
      'opacity-from-0': 'opacity-from-0 150ms ease-in-out',
      'scale-from-left': 'scale-from-left 150ms ease-in-out',
      'scale-from-right': 'scale-from-right 150ms ease-in-out',
      'from-left': 'from-left 150ms ease-in-out',
      'from-right': 'from-right 150ms ease-in-out',
      'width-to-zero': 'width-to-zero 150ms ease-in-out',
      'width-to-full': 'width-to-full 150ms ease-in-out',
      'hide-to-left': 'hide-to-left 150ms ease-in-out',
      'tooltip-vertical': 'tooltip-vertical 300ms ease-in-out forwards',
      'tooltip-horizontal': 'tooltip-horizontal 300ms ease-in-out forwards',
      'scale-icon': 'scale-icon 150ms ease-in-out forwards',
      'scaling-5': 'scaling-5 2s ease-in-out infinite',
      'checkbox-active-on': 'checkbox-active-on 300ms linear forwards',
      'checkbox-active-off': 'checkbox-active-off 300ms linear forwards',
      'highlight': 'highlight 1s ease-in-out forwards',
      'width-half-to-full': 'width-half-to-full 150ms ease-in-out',
      'width-5-to-7': 'width-5-to-7 150ms ease-in-out',
      'width-full-to-half': 'width-full-to-half 150ms ease-in-out',
      'width-7-to-5': 'width-7-to-5 150ms ease-in-out',
      'loud-show': 'loud-show 150ms ease-in-out',
      'loud-show-text-mode': 'loud-show-text-mode 150ms ease-in-out',
      'loud-hide': 'loud-hide 150ms ease-in-out',
      'loud-hide-text-mode': 'loud-hide-text-mode 150ms ease-in-out',
      'scale-to-full': 'scale-to-full 300ms ease-in-out',
      'scale-cycle': 'scale-cycle 600ms cubic-bezier(0.4, 0, 0.6, 1) infinite',
      'scale-to-5': 'scale-to-5 150ms ease-in-out',
      'notify-panel-opening': 'notify-panel-opening 150ms ease-in-out',
      'notify-panel-closing': 'notify-panel-closing 150ms ease-in-out',
      'notify-toggle-hide': 'notify-toggle-hide 150ms ease-in-out',
      'notify-toggle-show': 'notify-toggle-show 150ms ease-in-out',
      'opacity-0-100-0': 'opacity-0-100-0 3s ease-in-out infinite',
      'opacity-10-20-10': 'opacity-10-20-10 3s ease-in-out infinite',
      'backdrop-2-4-2': 'backdrop-2-4-2 3s ease-in-out infinite',

    },
    aspectRatio: {
      auto: 'auto',
      square: '1 / 1',
      video: '16 / 9',
    },
    backdropBlur: ({ theme }) => theme('blur'),
    backdropBrightness: ({ theme }) => theme('brightness'),
    backdropContrast: ({ theme }) => theme('contrast'),
    backdropGrayscale: ({ theme }) => theme('grayscale'),
    backdropHueRotate: ({ theme }) => theme('hueRotate'),
    backdropInvert: ({ theme }) => theme('invert'),
    backdropOpacity: ({ theme }) => theme('opacity'),
    backdropSaturate: ({ theme }) => theme('saturate'),
    backdropSepia: ({ theme }) => theme('sepia'),
    backgroundColor: ({ theme }) => theme('colors'),
    backgroundImage: {
      none: 'none',
      'gradient-to-t': 'linear-gradient(to top, var(--tw-gradient-stops))',
      'gradient-to-tr': 'linear-gradient(to top right, var(--tw-gradient-stops))',
      'gradient-to-r': 'linear-gradient(to right, var(--tw-gradient-stops))',
      'gradient-to-br': 'linear-gradient(to bottom right, var(--tw-gradient-stops))',
      'gradient-to-b': 'linear-gradient(to bottom, var(--tw-gradient-stops))',
      'gradient-to-bl': 'linear-gradient(to bottom left, var(--tw-gradient-stops))',
      'gradient-to-l': 'linear-gradient(to left, var(--tw-gradient-stops))',
      'gradient-to-tl': 'linear-gradient(to top left, var(--tw-gradient-stops))',
    },
    backgroundOpacity: ({ theme }) => theme('opacity'),
    backgroundPosition: {
      bottom: 'bottom',
      center: 'center',
      left: 'left',
      'left-bottom': 'left bottom',
      'left-top': 'left top',
      right: 'right',
      'right-bottom': 'right bottom',
      'right-top': 'right top',
      top: 'top',
    },
    backgroundSize: {
      auto: 'auto',
      cover: 'cover',
      contain: 'contain',
    },
    blur: {
      0: '0',
      none: '0',
      sm: '4px',
      DEFAULT: '8px',
      md: '12px',
      lg: '16px',
      xl: '24px',
      '2xl': '40px',
      '3xl': '64px',
    },
    brightness: {
      0: '0',
      50: '.5',
      75: '.75',
      90: '.9',
      95: '.95',
      100: '1',
      105: '1.05',
      110: '1.1',
      125: '1.25',
      150: '1.5',
      200: '2',
    },
    borderColor: ({ theme }) => ({
      ...theme('colors'),
      DEFAULT: theme('colors.gray.200', 'currentColor'),
    }),
    borderOpacity: ({ theme }) => theme('opacity'),
    borderRadius: {
      none: '0px',
      sm: '0.125rem',
      DEFAULT: '0.25rem',
      md: '0.375rem',
      lg: '0.5rem',
      xl: '0.75rem',
      '2xl': '1rem',
      '3xl': '1.5rem',
      '3.5xl': '1.75rem',
      '4xl': '2rem',
      '5xl': '2.5rem',
      full: '9999px',
    },
    borderWidth: {
      DEFAULT: '1px',
      0: '0px',
      2: '2px',
      3: '3px',
      4: '4px',
      5: '5px',
      8: '8px',
    },
    boxShadow: {
      sm: '0 1px 2px 0 rgb(0 0 0 / 0.05)',
      DEFAULT: '0 1px 3px 0 rgb(0 0 0 / 0.1), 0 1px 2px -1px rgb(0 0 0 / 0.1)',
      md: '0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)',
      lg: '0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)',
      xl: '0 20px 25px -5px rgb(0 0 0 / 0.1), 0 8px 10px -6px rgb(0 0 0 / 0.1)',
      '2xl': '0 25px 50px -12px rgb(0 0 0 / 0.25)',
      inner: 'inset 0 2px 4px 0 rgb(0 0 0 / 0.05)',
      'inner-square': 'inset 0px 0px 4px 0px rgb(237 240 243 / 0.2)',
      'recorder': '0 35px 60px -15px rgb(0 0 0 / 0.25)',
      none: 'none',
      context: '5px 5px 4px 0px rgba(34, 60, 80, 0.2);',
      'mobile-button': '0px 4px 6px 3px rgba(0, 0, 0, 0.2);',
      'up': '0px -6px 8px 2px rgba(200, 200, 200, 0.2);',
    },
    boxShadowColor: ({ theme }) => theme('colors'),
    caretColor: ({ theme }) => theme('colors'),
    accentColor: ({ theme }) => ({
      ...theme('colors'),
      auto: 'auto',
    }),
    contrast: {
      0: '0',
      50: '.5',
      75: '.75',
      100: '1',
      125: '1.25',
      150: '1.5',
      200: '2',
    },
    container: {},
    content: {
      none: 'none',
    },
    cursor: {
      auto: 'auto',
      default: 'default',
      pointer: 'pointer',
      wait: 'wait',
      text: 'text',
      move: 'move',
      help: 'help',
      'not-allowed': 'not-allowed',
      none: 'none',
      'context-menu': 'context-menu',
      progress: 'progress',
      cell: 'cell',
      crosshair: 'crosshair',
      'vertical-text': 'vertical-text',
      alias: 'alias',
      copy: 'copy',
      'no-drop': 'no-drop',
      grab: 'grab',
      grabbing: 'grabbing',
      'all-scroll': 'all-scroll',
      'col-resize': 'col-resize',
      'row-resize': 'row-resize',
      'n-resize': 'n-resize',
      'e-resize': 'e-resize',
      's-resize': 's-resize',
      'w-resize': 'w-resize',
      'ne-resize': 'ne-resize',
      'nw-resize': 'nw-resize',
      'se-resize': 'se-resize',
      'sw-resize': 'sw-resize',
      'ew-resize': 'ew-resize',
      'ns-resize': 'ns-resize',
      'nesw-resize': 'nesw-resize',
      'nwse-resize': 'nwse-resize',
      'zoom-in': 'zoom-in',
      'zoom-out': 'zoom-out',
    },
    divideColor: ({ theme }) => theme('borderColor'),
    divideOpacity: ({ theme }) => theme('borderOpacity'),
    divideWidth: ({ theme }) => theme('borderWidth'),
    dropShadow: {
      sm: '0 1px 1px rgb(0 0 0 / 0.05)',
      DEFAULT: ['0 1px 2px rgb(0 0 0 / 0.1)', '0 1px 1px rgb(0 0 0 / 0.06)'],
      md: ['0 4px 3px rgb(0 0 0 / 0.07)', '0 2px 2px rgb(0 0 0 / 0.06)'],
      lg: ['0 10px 8px rgb(0 0 0 / 0.04)', '0 4px 3px rgb(0 0 0 / 0.1)'],
      xl: ['0 20px 13px rgb(0 0 0 / 0.03)', '0 8px 5px rgb(0 0 0 / 0.08)'],
      '2xl': '0 25px 25px rgb(0 0 0 / 0.15)',
      none: '0 0 #0000',
    },
    fill: ({ theme }) => theme('colors'),
    grayscale: {
      0: '0',
      DEFAULT: '100%',
    },
    hueRotate: {
      0: '0deg',
      15: '15deg',
      30: '30deg',
      60: '60deg',
      90: '90deg',
      180: '180deg',
    },
    invert: {
      0: '0',
      DEFAULT: '100%',
    },
    flex: {
      1: '1 1 0%',
      auto: '1 1 auto',
      initial: '0 1 auto',
      none: 'none',
    },
    flexBasis: ({ theme }) => ({
      auto: 'auto',
      ...theme('spacing'),
      '1/2': '50%',
      '1/3': '33.333333%',
      '2/3': '66.666667%',
      '1/4': '25%',
      '2/4': '50%',
      '3/4': '75%',
      '1/5': '20%',
      '2/5': '40%',
      '3/5': '60%',
      '4/5': '80%',
      '1/6': '16.666667%',
      '2/6': '33.333333%',
      '3/6': '50%',
      '4/6': '66.666667%',
      '5/6': '83.333333%',
      '1/12': '8.333333%',
      '2/12': '16.666667%',
      '3/12': '25%',
      '4/12': '33.333333%',
      '5/12': '41.666667%',
      '6/12': '50%',
      '7/12': '58.333333%',
      '8/12': '66.666667%',
      '9/12': '75%',
      '10/12': '83.333333%',
      '11/12': '91.666667%',
      full: '100%',
    }),
    flexGrow: {
      0: '0',
      DEFAULT: '1',
    },
    flexShrink: {
      0: '0',
      DEFAULT: '1',
    },
    fontFamily: {
      sans: [
        'ui-sans-serif',
        'system-ui',
        '-apple-system',
        'BlinkMacSystemFont',
        '"Segoe UI"',
        'Roboto',
        '"Helvetica Neue"',
        'Arial',
        '"Noto Sans"',
        'sans-serif',
        '"Apple Color Emoji"',
        '"Segoe UI Emoji"',
        '"Segoe UI Symbol"',
        '"Noto Color Emoji"',
      ],
      serif: ['ui-serif', 'Georgia', 'Cambria', '"Times New Roman"', 'Times', 'serif'],
      mono: [
        'TT Commons Pro Mono',
        'ui-monospace',
        'SFMono-Regular',
        'Menlo',
        'Monaco',
        'Consolas',
        '"Liberation Mono"',
        '"Courier New"',
        'monospace',
      ],
    },
    fontSize: {
      xxs: ['0.6rem', { lineHeight: '0.75rem' }],
      xs: ['0.75rem', { lineHeight: '1rem' }],
      sm: ['0.875rem', { lineHeight: '1.25rem' }],
      base: ['1rem', { lineHeight: '1.375rem' }],
      lg: ['1.125rem', { lineHeight: '1.5rem' }],
      xl: ['1.25rem', { lineHeight: '1.75rem' }],
      '2xl': ['1.5rem', { lineHeight: '2rem' }],
      '3xl': ['1.875rem', { lineHeight: '2.25rem' }],
      '3.5xl': ['2rem', { lineHeight: '2.5rem' }],
      '4xl': ['2.25rem', { lineHeight: '2.5rem' }],
      '4.5xl': ['2.5rem', { lineHeight: '3rem' }],
      '5xl': ['3rem', { lineHeight: '1' }],
      '5.5xl': ['3.5rem', { lineHeight: '1' }],
      '6xl': ['3.75rem', { lineHeight: '1' }],
      '7xl': ['4.5rem', { lineHeight: '1' }],
      '8xl': ['6rem', { lineHeight: '1' }],
      '9xl': ['8rem', { lineHeight: '1' }],
      'title-1': ['1.25rem', { lineHeight: '1.375rem', fontWeight: '500' }],
      'headline-1': ['1rem', { lineHeight: '1.125rem', fontWeight: '500' }],
      'headline-2': ['4.5rem', { lineHeight: '4.75rem', fontWeight: '600' }],
      'headline-3': ['3.5rem', { lineHeight: '3.75rem', fontWeight: '600' }],
      'headline-4': ['2.5rem', { lineHeight: '2.75rem', fontWeight: '600' }],
      'headline-5': ['1.5rem', { lineHeight: '1.75rem', fontWeight: '500' }],
      'text-1': ['1rem', { lineHeight: '1.125rem', fontWeight: '400' }],
      'caption-1': ['0.875rem', { lineHeight: '1rem', fontWeight: '500' }],
      'caption-2': ['0.85rem', { lineHeight: '0.875rem', fontWeight: '400' }],
      'caption-3': ['0.85rem', { lineHeight: '0.875rem', fontWeight: '500' }],
      'caption-4': ['0.875rem', { lineHeight: '1rem', fontWeight: '400' }],
    },
    fontWeight: {
      thin: '100',
      extralight: '200',
      light: '300',
      normal: '400',
      medium: '500',
      semibold: '600',
      bold: '700',
      extrabold: '800',
      black: '900',
    },
    gap: ({ theme }) => theme('spacing'),
    gradientColorStops: ({ theme }) => theme('colors'),
    gridAutoColumns: {
      auto: 'auto',
      min: 'min-content',
      max: 'max-content',
      fr: 'minmax(0, 1fr)',
    },
    gridAutoRows: {
      auto: 'auto',
      min: 'min-content',
      max: 'max-content',
      fr: 'minmax(0, 1fr)',
    },
    gridColumn: {
      auto: 'auto',
      'span-1': 'span 1 / span 1',
      'span-2': 'span 2 / span 2',
      'span-3': 'span 3 / span 3',
      'span-4': 'span 4 / span 4',
      'span-5': 'span 5 / span 5',
      'span-6': 'span 6 / span 6',
      'span-7': 'span 7 / span 7',
      'span-8': 'span 8 / span 8',
      'span-9': 'span 9 / span 9',
      'span-10': 'span 10 / span 10',
      'span-11': 'span 11 / span 11',
      'span-12': 'span 12 / span 12',
      'span-full': '1 / -1',
    },
    gridColumnEnd: {
      auto: 'auto',
      1: '1',
      2: '2',
      3: '3',
      4: '4',
      5: '5',
      6: '6',
      7: '7',
      8: '8',
      9: '9',
      10: '10',
      11: '11',
      12: '12',
      13: '13',
    },
    gridColumnStart: {
      auto: 'auto',
      1: '1',
      2: '2',
      3: '3',
      4: '4',
      5: '5',
      6: '6',
      7: '7',
      8: '8',
      9: '9',
      10: '10',
      11: '11',
      12: '12',
      13: '13',
    },
    gridRow: {
      auto: 'auto',
      'span-1': 'span 1 / span 1',
      'span-2': 'span 2 / span 2',
      'span-3': 'span 3 / span 3',
      'span-4': 'span 4 / span 4',
      'span-5': 'span 5 / span 5',
      'span-6': 'span 6 / span 6',
      'span-full': '1 / -1',
    },
    gridRowStart: {
      auto: 'auto',
      1: '1',
      2: '2',
      3: '3',
      4: '4',
      5: '5',
      6: '6',
      7: '7',
    },
    gridRowEnd: {
      auto: 'auto',
      1: '1',
      2: '2',
      3: '3',
      4: '4',
      5: '5',
      6: '6',
      7: '7',
    },
    gridTemplateColumns: {
      none: 'none',
      1: 'repeat(1, minmax(0, 1fr))',
      2: 'repeat(2, minmax(0, 1fr))',
      3: 'repeat(3, minmax(0, 1fr))',
      4: 'repeat(4, minmax(0, 1fr))',
      5: 'repeat(5, minmax(0, 1fr))',
      6: 'repeat(6, minmax(0, 1fr))',
      7: 'repeat(7, minmax(0, 1fr))',
      8: 'repeat(8, minmax(0, 1fr))',
      9: 'repeat(9, minmax(0, 1fr))',
      10: 'repeat(10, minmax(0, 1fr))',
      11: 'repeat(11, minmax(0, 1fr))',
      12: 'repeat(12, minmax(0, 1fr))',
    },
    gridTemplateRows: {
      none: 'none',
      1: 'repeat(1, minmax(0, 1fr))',
      2: 'repeat(2, minmax(0, 1fr))',
      3: 'repeat(3, minmax(0, 1fr))',
      4: 'repeat(4, minmax(0, 1fr))',
      5: 'repeat(5, minmax(0, 1fr))',
      6: 'repeat(6, minmax(0, 1fr))',
    },
    height: ({ theme }) => ({
      auto: 'auto',
      ...theme('spacing'),
      '1/2': '50%',
      '1/3': '33.333333%',
      '2/3': '66.666667%',
      '1/4': '25%',
      '2/4': '50%',
      '3/4': '75%',
      '1/5': '20%',
      '2/5': '40%',
      '3/5': '60%',
      '4/5': '80%',
      '1/6': '16.666667%',
      '2/6': '33.333333%',
      '3/6': '50%',
      '4/6': '66.666667%',
      '5/6': '83.333333%',
      '9/10': '90%',
      full: '100%',
      screen: '100vh',
      min: 'min-content',
      max: 'max-content',
      fit: 'fit-content',
    }),
    inset: ({ theme }) => ({
      auto: 'auto',
      ...theme('spacing'),
      '1/2': '50%',
      '1/3': '33.333333%',
      '2/3': '66.666667%',
      '1/4': '25%',
      '2/4': '50%',
      '3/4': '75%',
      '1/24': '4.166667%',
      full: '100%',
    }),
    keyframes: {
      spin: {
        to: {
          transform: 'rotate(360deg)',
        },
      },
      ping: {
        '75%, 100%': {
          transform: 'scale(2)',
          opacity: '0',
        },
      },
      pulse: {
        '50%': {
          opacity: '.5',
        },
      },
      'pulse-70': {
        '50%': {
          opacity: '.7',
        },
      },
      'custom-pulse': {
        '50%': {
          opacity: '.1',
        },
      },
      'swipe-by': {
        '0%': {
          transform: 'translate(-150%) rotate(10deg)',
        },
        '70%': {
          transform: 'translate(150%) rotate(10deg)',
        },
        '100%': {
          transform: 'translate(150%) rotate(10deg)',
        },
      },
      'scale': {
        '50%': {
          transform: 'scale(0.3)',
        },
      },
      'decrease': {
        from: {
          transform: 'scale(1)',
        },
        to: {
          transform: 'scale(0.05)',
        },
      },
      'increase': {
        from: {
          transform: 'scale(.05)',
        },
        to: {
          transform: 'scale(1)',
        },
      },
      bounce: {
        '0%, 100%': {
          transform: 'translateY(-25%)',
          animationTimingFunction: 'cubic-bezier(0.8,0,1,1)',
        },
        '50%': {
          transform: 'none',
          animationTimingFunction: 'cubic-bezier(0,0,0.2,1)',
        },
      },
      'checkbox-active-on': {
        '0%': {
          'box-shadow': '0 0 0 0 rgba(212,212,212, 0)',
        },
        '99%': {
          'box-shadow': '0 0 0 7px rgba(212,212,212, 0.5)',
        },
      },
      'checkbox-active-off': {
        '0%': {
          'box-shadow': '0 0 0 0 rgba(154,190,247, 0)',
        },
        '99%': {
          'box-shadow': '0 0 0 7px rgba(154,190,247, 0.5)',
        },
      },
      'display-element-from-left': {
        from: {
          transform: 'translateX(-1rem) scale(.05)',
        },
        to: {
          transform: 'translateX(0rem) scale(1)',
        },
      },
      'width-to-zero': {
        from: {
          width: '100%',
        },
        to: {
          width: '16%',
        },
      },
      'width-to-full': {
        from: {
          width: '0%',
          opacity: '0',
        },
        to: {
          width: '84%',
          opacity: '1'
        },
      },
      'width-full-to-half': {
        from: {
          width: '100%',
        },
        to: {
          width: '50%',
        },
      },
      'width-7-to-5': {
        from: {
          width: '7rem',
        },
        to: {
          width: '5rem',
        },
      },
      'width-half-to-full': {
        from: {
          width: '50%',
        },
        to: {
          width: '100%',
        },
      },
      'width-5-to-7': {
        from: {
          width: '5rem',
        },
        to: {
          width: '7rem',
        },
      },
      'loud-show': {
        from: {
          transform: 'translateX(1.5rem) scale(.05)',
        },
        to: {
          transform: 'translateX(3rem) scale(1)',
        },
      },
      'loud-show-text-mode': {
        from: {
          transform: 'translateX(1.5rem) scale(.05)',
        },
        to: {
          transform: 'translateX(2.5rem) scale(1)',
        },
      },
      'loud-hide': {
        from: {
          transform: 'translateX(3rem) scale(1)',
        },
        to: {
          transform: 'translateX(1.5rem) scale(.05)',
        },
      },
      'loud-hide-text-mode': {
        from: {
          transform: 'translateX(2.5rem) scale(1)',
        },
        to: {
          transform: 'translateX(1.5rem) scale(.05)',
        },
      },
      'scale-to-full': {
        '0%': {
          transform: 'scale(0)',
        },
        '50%': {
          transform: 'scale(0.05)'
        },
        '99%': {
          transform: 'scale(1)',
        },
      },
      'scale-cycle': {
        '0%': {
            transform: 'scale(0)',
        },
        '50%': {
            transform: 'scale(1)'
        },
        '100%': {
            transform: 'scale(0)',
        },
      },
      'scale-to-5': {
        from: {
          transform: 'scale(1)',
        },
        to: {
          transform: 'scale(0.05)',
        },
      },
      'notify-panel-opening': {
        '0%': {
          transform: 'scale(0)',
          width: '0',
        },
        '50%': {
          transform: 'scale(0)',
            width: '0',
        },
        '100%': {
          transform: 'scale(1)',
          width: '100%',
        },
      },
      'notify-panel-closing': {
        '0%': {
          transform: 'scale(1)',
        },
        '50%': {
          transform: 'scale(0)',
        },
        '100%': {
          transform: 'scale(0)',
        },
      },
      'notify-toggle-hide': {
        '0%': {
          transform: 'scale(1)',
        },
        '50%': {
          transform: 'scale(0)',
        },
        '100%': {
          transform: 'scale(0)',
        },
      },
      'notify-toggle-show': {
        '0%': {
          transform: 'scale(0)',
        },
        '50%': {
          transform: 'scale(0)',
        },
        '100%': {
          transform: 'scale(1)',
        },
      },
      'hide-to-left': {
        to: {
          transform: '-translateX(300%)',
        },
      },
      'scale-from-right': {
        from: {
          transform: 'translateX(1rem) scale(.05)',
        },
        to: {
          transform: 'translateX(0rem) scale(1)',
        },
      },
      'from-right': {
        from: {
          transform: 'translate(8rem, 0rem) scale(1)',
        },
        to: {
          transform: 'translate(0rem, 0rem) scale(1)',
        },
      },
      'display-element-from-top': {
        from: {
          height: 0,
          transform: 'translateY(-1.5rem)',
        },
        to: {
          height: '100%',
          transform: 'translateY(0rem)',
        },
      },
      'display-element-from-bottom': {
        from: {
          opacity: 0,
          transform: 'translateY(1.5rem)',
        },
        to: {
          opacity: 1,
          transform: 'translateY(0rem)',
        },
      },
      'opacity-from-0': {
        from: {
          opacity: 0,
        },
        to: {
          opacity: 1,
        },
      },
      'scale-icon': {
        from: {
          transform: 'scale(1)',
        },
        to: {
          transform: 'scale(1.05)',
        },
      },
      'scaling-5': {
        '0%, 100%': {
          transform: 'scale(1)',
        },
        '50%': {
          transform: 'scale(1.05)',
        },
      },
      'tooltip-vertical': {
        to: {
          transform: 'translate(-50%, 0)',
          opacity: 1,
        },
      },
      'tooltip-horizontal': {
        to: {
          transform: 'translate(0, -50%)',
          opacity: 1,
        },
      },
      'highlight': {
          '0%': {
              'background': 'var(--replied-message-hover)',
              'border-left': '2px solid var(--replied-message-border)',
          },
          '99%': {
              'background': '',
              'border-left': '2px solid transparent',
          },
      },
      'opacity-0-100-0': {
        '0%, 100%': {
          opacity: 0,
        },
        '50%': {
          opacity: 1,
        },
      },
      'opacity-10-20-10': {
        '0%, 100%': {
          opacity: 0.1,
        },
        '50%': {
          opacity: 0.2,
        },
      },
      'backdrop-2-4-2': {
        '0%, 100%': {
          opacity: 0.9,
          'backdrop-filter': 'blur(2px)',
        },
        '50%': {
          opacity: 0.8,
          'backdrop-filter': 'blur(4px)',
        },
      },
    },
    letterSpacing: {
      tighter: '-0.05em',
      tight: '-0.025em',
      normal: '0em',
      wide: '0.025em',
      wider: '0.05em',
      widest: '0.1em',
    },
    lineHeight: {
      none: '1',
      tight: '1.25',
      snug: '1.375',
      normal: '1.5',
      relaxed: '1.625',
      loose: '2',
      3: '.75rem',
      4: '1rem',
      5: '1.25rem',
      6: '1.5rem',
      7: '1.75rem',
      8: '2rem',
      9: '2.25rem',
      10: '2.5rem',
    },
    listStyleType: {
      none: 'none',
      disc: 'disc',
      decimal: 'decimal',
    },
    margin: ({ theme }) => ({
      auto: 'auto',
      ...theme('spacing'),
    }),
    maxHeight: ({ theme }) => ({
      ...theme('spacing'),
      ...theme('relativeSpacing'),
      full: '100%',
      screen: '100vh',
      min: 'min-content',
      max: 'max-content',
      fit: 'fit-content',
      footer: '3.75rem',
      none: 'none',
    }),
    maxWidth: ({ theme, breakpoints }) => ({
      ...theme('spacing'),
      ...theme('relativeSpacing'),
      none: 'none',
      xxs: '10rem',
      xs: '20rem',
      sm: '24rem',
      md: '28rem',
      lg: '32rem',
      xl: '36rem',
      '2xl': '42rem',
      '3xl': '48rem',
      '4xl': '56rem',
      '5xl': '64rem',
      '6xl': '72rem',
      '7xl': '80rem',
      full: '100%',
      min: 'min-content',
      max: 'max-content',
      fit: 'fit-content',
      prose: '65ch',
      modal: '480px',
      ...breakpoints(theme('screens')),
    }),
    minHeight: ({ theme }) => ({
      ...theme('spacing'),
      ...theme('relativeSpacing'),
      full: '100%',
      screen: '100vh',
      min: 'min-content',
      max: 'max-content',
      fit: 'fit-content',
      footer: '3.75rem',
    }),
    minWidth: ({ theme }) => ({
      ...theme('spacing'),
      ...theme('relativeSpacing'),
      full: '100%',
      min: 'min-content',
      max: 'max-content',
      fit: 'fit-content',
      'modal': '480px',
    }),
    objectPosition: {
      bottom: 'bottom',
      center: 'center',
      left: 'left',
      'left-bottom': 'left bottom',
      'left-top': 'left top',
      right: 'right',
      'right-bottom': 'right bottom',
      'right-top': 'right top',
      top: 'top',
    },
    opacity: {
      0: '0',
      5: '0.05',
      10: '0.1',
      20: '0.2',
      25: '0.25',
      30: '0.3',
      40: '0.4',
      50: '0.5',
      60: '0.6',
      70: '0.7',
      75: '0.75',
      80: '0.8',
      90: '0.9',
      95: '0.95',
      100: '1',
    },
    order: {
      first: '-9999',
      last: '9999',
      none: '0',
      1: '1',
      2: '2',
      3: '3',
      4: '4',
      5: '5',
      6: '6',
      7: '7',
      8: '8',
      9: '9',
      10: '10',
      11: '11',
      12: '12',
    },
    padding: ({ theme }) => theme('spacing'),
    placeholderColor: ({ theme }) => theme('colors'),
    placeholderOpacity: ({ theme }) => theme('opacity'),
    outlineColor: ({ theme }) => theme('colors'),
    outlineOffset: {
      0: '0px',
      1: '1px',
      2: '2px',
      4: '4px',
      8: '8px',
    },
    outlineWidth: {
      0: '0px',
      1: '1px',
      2: '2px',
      4: '4px',
      8: '8px',
    },
    ringColor: ({ theme }) => ({
      DEFAULT: theme('colors.blue.500', '#3b82f6'),
      ...theme('borderColor'),
    }),
    ringOffsetColor: ({ theme }) => theme('borderColor'),
    ringOffsetWidth: {
      0: '0px',
      1: '1px',
      2: '2px',
      4: '4px',
      8: '8px',
    },
    ringOpacity: ({ theme }) => ({
      DEFAULT: '0.1',
      ...theme('opacity'),
    }),
    ringWidth: {
      DEFAULT: '3px',
      0: '0px',
      1: '1px',
      2: '2px',
      4: '4px',
      8: '8px',
    },
    rotate: {
      0: '0deg',
      1: '1deg',
      2: '2deg',
      3: '3deg',
      6: '6deg',
      12: '12deg',
      45: '45deg',
      90: '90deg',
      180: '180deg',
    },
    saturate: {
      0: '0',
      50: '.5',
      100: '1',
      150: '1.5',
      200: '2',
    },
    scale: {
      0: '0',
      50: '.5',
      75: '.75',
      90: '.9',
      95: '.95',
      100: '1',
      105: '1.05',
      110: '1.1',
      125: '1.25',
      150: '1.5',
    },
    scrollMargin: ({ theme }) => ({
      ...theme('spacing'),
    }),
    scrollPadding: ({ theme }) => theme('spacing'),
    sepia: {
      0: '0',
      DEFAULT: '100%',
    },
    skew: {
      0: '0deg',
      1: '1deg',
      2: '2deg',
      3: '3deg',
      6: '6deg',
      12: '12deg',
    },
    space: ({ theme }) => ({
      ...theme('spacing'),
    }),
    stroke: ({ theme }) => theme('colors'),
    strokeWidth: {
      0: '0',
      1: '1',
      2: '2',
    },
    textColor: ({ theme }) => theme('colors'),
    textDecorationColor: ({ theme }) => theme('colors'),
    textDecorationThickness: {
      auto: 'auto',
      'from-font': 'from-font',
      0: '0px',
      1: '1px',
      2: '2px',
      4: '4px',
      8: '8px',
    },
    textUnderlineOffset: {
      auto: 'auto',
      0: '0px',
      1: '1px',
      2: '2px',
      4: '4px',
      8: '8px',
    },
    textIndent: ({ theme }) => ({
      ...theme('spacing'),
    }),
    textOpacity: ({ theme }) => theme('opacity'),
    transformOrigin: {
      center: 'center',
      top: 'top',
      'top-right': 'top right',
      right: 'right',
      'bottom-right': 'bottom right',
      bottom: 'bottom',
      'bottom-left': 'bottom left',
      left: 'left',
      'top-left': 'top left',
    },
    transitionDelay: {
      75: '75ms',
      100: '100ms',
      150: '150ms',
      200: '200ms',
      300: '300ms',
      500: '500ms',
      700: '700ms',
      1000: '1000ms',
    },
    transitionDuration: {
      DEFAULT: '150ms',
      75: '75ms',
      100: '100ms',
      150: '150ms',
      200: '200ms',
      250: '250ms',
      300: '300ms',
      500: '500ms',
      700: '700ms',
      1000: '1000ms',
    },
    transitionProperty: {
      none: 'none',
      all: 'all',
      DEFAULT:
        'color, background-color, border-color, text-decoration-color, fill, stroke, opacity, box-shadow, transform, filter, backdrop-filter',
      colors: 'color, background-color, border-color, text-decoration-color, fill, stroke',
      opacity: 'opacity',
      shadow: 'box-shadow',
      transform: 'transform',
    },
    transitionTimingFunction: {
      DEFAULT: 'cubic-bezier(0.4, 0, 0.2, 1)',
      linear: 'linear',
      in: 'cubic-bezier(0.4, 0, 1, 1)',
      out: 'cubic-bezier(0, 0, 0.2, 1)',
      'in-out': 'cubic-bezier(0.4, 0, 0.2, 1)',
    },
    translate: ({ theme }) => ({
      ...theme('spacing'),
      '1/2': '50%',
      '1/3': '33.333333%',
      '2/3': '66.666667%',
      '1/4': '25%',
      '1/5': '20%',
      '2/4': '50%',
      '3/4': '75%',
      '4/5': '80%',
      '5/6': '83.333333%',
      full: '100%',
    }),
    width: ({ theme }) => ({
      auto: 'auto',
      ...theme('spacing'),
      '1/2': '50%',
      '1/3': '33.333333%',
      '2/3': '66.666667%',
      '1/4': '25%',
      '2/4': '50%',
      '3/4': '75%',
      '1/5': '20%',
      '2/5': '40%',
      '3/5': '60%',
      '4/5': '80%',
      '1/6': '16.666667%',
      '2/6': '33.333333%',
      '3/6': '50%',
      '4/6': '66.666667%',
      '5/6': '83.333333%',
      '1/12': '8.333333%',
      '2/12': '16.666667%',
      '3/12': '25%',
      '4/12': '33.333333%',
      '5/12': '41.666667%',
      '6/12': '50%',
      '7/12': '58.333333%',
      '8/12': '66.666667%',
      '9/12': '75%',
      '10/12': '83.333333%',
      '11/12': '91.666667%',
      '3/24': '12.5%',
      '21/24': '87.5%',
      full: '100%',
      screen: '100vw',
      min: 'min-content',
      max: 'max-content',
      fit: 'fit-content',
      'modal': '480px',
    }),
    willChange: {
      auto: 'auto',
      scroll: 'scroll-position',
      contents: 'contents',
      transform: 'transform',
    },
    zIndex: {
      auto: 'auto',
      0: '0',
      10: '10',
      20: '20',
      30: '30',
      40: '40',
      50: '50',
      60: '60',
      70: '70',
      80: '80',
      90: '90',
      'minus': '-1',
      'button': '100',
      'menu-container': '200',
      'modal-overlay': '200',
      'menu-overlay': '201',
      'menu-hover': '202',
      'menu': '203',
      'error-container': '300',
      'bubble': '900',
      'tooltip': '999',
    },
  },
  variantOrder: [
    'first',
    'last',
    'odd',
    'even',
    'visited',
    'checked',
    'empty',
    'read-only',
    'group-hover',
    'group-focus',
    'focus-within',
    'hover',
    'focus',
    'focus-visible',
    'active',
    'disabled',
  ],
  plugins: [
      // require('@tailwindcss/forms'),
    plugin(({ matchUtilities, theme }) => {
      matchUtilities(
        {
          'translate-z': (value) => ({
            '--tw-translate-z': value,
            transform: ` translate3d(var(--tw-translate-x), var(--tw-translate-y), var(--tw-translate-z)) rotate(var(--tw-rotate)) skewX(var(--tw-skew-x)) skewY(var(--tw-skew-y)) scaleX(var(--tw-scale-x)) scaleY(var(--tw-scale-y))`,
          }), // this is actual CSS
        },
        { values: theme('translate'), supportsNegativeValues: true },
      );
    }),
  ],
  future: {
    hoverOnlyWhenSupported: true,
  },
};
