// <auto-generated>
// This file is generated by App.AotHelper -g. Do not edit manually.
// </auto-generated>
//
// PolyType witness for every [Serializable] AOT root in ActualChat.UI.Blazor.App. Each
// [GenerateShapeFor<T>] attribute makes this class implement IShapeable<T>, which the
// Nerdbank.MessagePack serializer can use to round-trip T under NativeAOT without
// touching the reflection shape provider.
//
// The generated half of BlazorUIAppModuleInitializer self-registers the shape provider (and the
// AOT source, when present) via [ModuleInitializer], so the hand-written half only
// needs to declare its own dependency chain through its static constructor + Load().

#pragma warning disable CS0618 // Obsolete types are still needed for AOT retention
#pragma warning disable CA2255  // ModuleInitializer is intended for AOT setup

using PolyType;

namespace ActualChat.UI.Blazor.App.Module;

[GenerateShapeFor<global::ActualChat.UI.Blazor.App.Services.ActiveChat>]
[GenerateShapeFor<global::ActualChat.UI.Blazor.App.Services.AttachFileRequestEntry>]
[GenerateShapeFor<global::ActualChat.UI.Blazor.App.Services.EntryRef>]
[GenerateShapeFor<global::ActualChat.UI.Blazor.App.Services.FileMetadata>]
[GenerateShapeFor<global::ActualChat.UI.Blazor.App.Services.MauiFileProvider>]
[GenerateShapeFor<global::ActualChat.UI.Blazor.App.Services.RelatedEntryRef>]
[GenerateShapeFor<global::ActualChat.UI.Blazor.App.Services.SendMessageRequestEntry>]
[GenerateShapeFor<global::ActualChat.UI.Blazor.App.Services.UploadSessionSnapshot>]
[GenerateShapeFor<global::ActualChat.UI.Blazor.App.Services.WebFileProvider>]
[GenerateShapeFor<global::ActualChat.UI.Blazor.App.Services.ActiveChat[]>]
[GenerateShapeFor<global::ActualChat.UI.Blazor.App.Services.ReadPosition>]
[GenerateShapeFor<global::ActualLab.Serialization.Box<global::ActualLab.Time.Moment>>]
[GenerateShapeFor<global::System.Collections.Immutable.IImmutableDictionary<global::System.String, global::ActualChat.ChatId>>]
internal partial class BlazorUIAppWitness;

public static partial class BlazorUIAppModuleInitializer
{
    [global::System.Runtime.CompilerServices.ModuleInitializer]
    internal static void RegisterGenerated()
    {
        global::ActualChat.Aot.AotTypes.AddSource(new BlazorUIAppAotSource());
        global::ActualChat.Serialization.Serializers.RegisterShapeProvider(BlazorUIAppWitness.GeneratedTypeShapeProvider);
    }
}
