<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Testing\Testing.csproj" />
    <ProjectReference Include="..\..\src\dotnet\Core.Audio\Core.Audio.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="data\**" CopyToOutputDirectory="Always" />
    <Content Include="..\..\src\dotnet\Core.Audio\APM\runtimes\win-x64\native\webrtc-apm.dll">
      <Link>webrtc-apm.dll</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
    <Content Include="..\..\src\dotnet\Core.Audio\APM\runtimes\linux-x64\native\libwebrtc-apm.so">
      <Link>libwebrtc-apm.so</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="data\" />
  </ItemGroup>

</Project>
