<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Core.Server\Core.Server.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Anthropic.SDK" />
    <PackageReference Include="ZString" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="ActualChat.MLSearch.IntegrationTests"/>
    <InternalsVisibleTo Include="ActualChat.Chat.IntegrationTests"/>
  </ItemGroup>

</Project>
