#!/usr/bin/env pwsh
# Classes and functions to configure the hosts file, the LOCAL_IP entry in
# .env, and trust dev SSL certificates. Idempotent: skips work that's already
# done. Only requests admin (Windows) or sudo (macOS/Linux) when an action
# actually needs it.
#
# This file contains only class and function definitions. Depends on
# scripts/Common.ps1 being dot-sourced into the same scope. To use it:
#
#     pwsh -NoProfile -c ". ./scripts/Common.ps1; . ./add-hosts.ps1; Configure-LocalEnvHosts"

# --- Root CA trust store -----------------------------------------------------

class RootCertStore {
    static [string] GetThumbprint([string]$path) {
        $cert = [System.Security.Cryptography.X509Certificates.X509Certificate2]::new($path)
        return $cert.Thumbprint
    }

    static [RootCertStore] ForCurrentOS() {
        switch (Get-CurrentOS) {
            'Windows' { return [WindowsRootCertStore]::new() }
            'macOS'   { return [MacOSRootCertStore]::new() }
            default   { return [LinuxRootCertStore]::new() }
        }
        return $null  # unreachable
    }

    [bool] IsInstalled([string]$path) {
        throw "Not implemented - use a platform-specific subclass"
    }

    [void] Install([string]$path) {
        throw "Not implemented - use a platform-specific subclass"
    }
}

class WindowsRootCertStore : RootCertStore {
    [bool] IsInstalled([string]$path) {
        $thumbprint = [RootCertStore]::GetThumbprint($path)
        $store = [System.Security.Cryptography.X509Certificates.X509Store]::new('Root', 'LocalMachine')
        try {
            $store.Open([System.Security.Cryptography.X509Certificates.OpenFlags]::ReadOnly)
            return [bool]($store.Certificates | Where-Object { $_.Thumbprint -ieq $thumbprint })
        } finally {
            $store.Close()
        }
    }

    [void] Install([string]$path) {
        Write-Host "Trusting root certificate (admin required)..."
        try {
            $proc = Start-Process certutil `
                -ArgumentList @('-addstore', '-f', 'ROOT', "`"$path`"") `
                -Verb RunAs -Wait -PassThru -ErrorAction Stop
            if ($proc.ExitCode -ne 0) {
                Write-Host "certutil exited with code $($proc.ExitCode)" -ForegroundColor Yellow
            }
        } catch {
            Write-Host "Could not elevate to install root certificate." -ForegroundColor Yellow
            Write-Host "Run manually as admin:" -ForegroundColor Yellow
            Write-Host "  certutil -addstore -f ROOT `"$path`""
        }
    }
}

class MacOSRootCertStore : RootCertStore {
    [bool] IsInstalled([string]$path) {
        $thumbprint = [RootCertStore]::GetThumbprint($path)
        $found = security find-certificate -a -Z /Library/Keychains/System.keychain 2>$null |
            Select-String -Pattern "SHA-1 hash: $thumbprint" -SimpleMatch -Quiet
        return [bool]$found
    }

    [void] Install([string]$path) {
        Write-Host "Trusting root certificate (sudo required)..."
        sudo security add-trusted-cert -d -r trustRoot -k /Library/Keychains/System.keychain $path
    }
}

class LinuxRootCertStore : RootCertStore {
    # Linux / WSL / Docker.
    # Namespaced filename to avoid conflicts with rootCA.crt files generated by
    # other dev tools (mkcert, custom self-signed CAs, etc.).
    static [string] $DestPath = '/usr/local/share/ca-certificates/voxt-local-dev-rootCA.crt'

    [bool] IsInstalled([string]$path) {
        if (-not (Test-Path ([LinuxRootCertStore]::DestPath))) { return $false }
        return (Get-FileHash $path -Algorithm SHA256).Hash -eq (Get-FileHash ([LinuxRootCertStore]::DestPath) -Algorithm SHA256).Hash
    }

    [void] Install([string]$path) {
        Write-Host "Trusting root certificate (sudo required)..."
        sudo cp $path ([LinuxRootCertStore]::DestPath)
        sudo update-ca-certificates
    }
}

# --- .NET dev cert -----------------------------------------------------------

class DotnetDevCert {
    [bool] IsTrusted() {
        # `--check --trust` returns 0 only if a trusted dev cert exists.
        # On Linux, --trust is unsupported, so fall back to existence check.
        if ((Get-CurrentOS) -in @('Windows', 'macOS')) {
            & dotnet dev-certs https --check --trust *> $null
        } else {
            & dotnet dev-certs https --check *> $null
        }
        return $LASTEXITCODE -eq 0
    }

    [void] Install() {
        if ((Get-CurrentOS) -eq 'Windows') {
            $pfxPath = Join-Path $env:USERPROFILE '.aspnet/https/aspnetapp.pfx'
            $pfxDir = Split-Path -Parent $pfxPath
            if (-not (Test-Path $pfxDir)) {
                New-Item -ItemType Directory -Path $pfxDir -Force | Out-Null
            }
            if (-not (Test-Path $pfxPath)) {
                Write-Host "Exporting dev cert PFX to $pfxPath..."
                & dotnet dev-certs https -ep $pfxPath -p crypticpassword
            }
        }
        Write-Host "Installing dotnet dev-certs (--trust)..."
        & dotnet dev-certs https --trust
    }
}

# --- Orchestrator ------------------------------------------------------------

function Configure-LocalEnvHosts {
    [CmdletBinding()]
    param(
        [switch]$Force
    )

    # 1. Hosts file + .env LOCAL_IP. Update-HostEntries already elevates only
    #    when the file actually needs changes.
    Write-Host "Updating hosts file and .env LOCAL_IP..."
    $baseHostnames = @(
        'local.voxt.ai', 'media.local.voxt.ai', 'cdn.local.voxt.ai',
        'local.actual.chat', 'media.local.actual.chat', 'cdn.local.actual.chat'
    )
    # Also refresh any dynamically-created subdomains already in the hosts file
    # (e.g. per-worktree domains) — they all resolve to this same machine.
    $existingHostnames = Get-MatchingHostnames -Suffixes @('local.voxt.ai', 'local.actual.chat')
    $allHostnames = @($baseHostnames + $existingHostnames | Select-Object -Unique)
    Update-HostEntries -DetectIP -Hostnames $allHostnames | Out-Null
    Update-LocalIP | Out-Null

    # 2. Root CA
    $certPath = Join-Path $PSScriptRoot '.config/local.voxt.ai/ssl/rootCA.crt'
    if (-not (Test-Path $certPath)) {
        Write-Error "Root CA certificate not found: $certPath"
        return
    }

    $rootStore = [RootCertStore]::ForCurrentOS()
    if (-not $Force -and $rootStore.IsInstalled($certPath)) {
        Write-Host "Root certificate already trusted - skipping"
    } else {
        $rootStore.Install($certPath)
    }

    # 3. .NET dev cert
    $devCert = [DotnetDevCert]::new()
    if (-not $Force -and $devCert.IsTrusted()) {
        Write-Host "dotnet dev-certs already trusted - skipping"
    } else {
        $devCert.Install()
    }

    Write-Host "Done."
}
