version: '3.8'
services:
  imageproxy:
    image: willnorris/imageproxy:latest
    ports:
      - 8080:8080
    environment:
      - IMAGEPROXY_CACHE=memory:100:24h
      - IMAGEPROXY_SCALEUP=true
      # - SSL_CERT_FILE=/usr/local/share/ca-certificates/local.actual.chat.crt
      - SSL_CERT_DIR=/usr/local/share/ca-certificates/
    volumes:
      - ./local.actual.chat.crt:/usr/local/share/ca-certificates/local.actual.chat.crt
    extra_hosts:
      - "cdn.local.actual.chat:host-gateway" #host and ip
      - "local.actual.chat:host-gateway" #host and ip
  nginx:
    container_name: reverse
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./access.log:/var/log/nginx/access.log
#      - ./data/certbot/conf:/etc/letsencrypt
#      - ./data/certbot/www:/var/www/certbot
    extra_hosts:
      - "cdn.local.actual.chat:host-gateway" #host and ip
      - "local.actual.chat:host-gateway" #host and ip

