version: '3.8'
services:
  redis:
    image: "redis:7.2.4-alpine3.19"
    ports:
     - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
  postgres:
    image: "postgres:14.0-alpine3.14"
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_HOST_AUTH_METHOD: "password"
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    entrypoint: ["docker-entrypoint.sh", "-c", "shared_buffers=256MB", "-c", "max_connections=1000", "-c", "shared_preload_libraries=pg_stat_statements", "-c", "pg_stat_statements.track=all"]
  imageproxy:
    image: willnorris/imageproxy:latest
    expose:
      - 8080
    environment:
      - IMAGEPROXY_CACHE=memory:100:24h
      - SSL_CERT_DIR=/usr/local/share/ca-certificates/
    volumes:
      - ./.config/local.actual.chat/ssl/local.actual.chat.crt:/usr/local/share/ca-certificates/local.actual.chat.crt
    extra_hosts:
      - "cdn.local.actual.chat:host-gateway"
  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./.config/local.actual.chat/ssl:/etc/ssl
      - ./.config/local.actual.chat/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./.config/local.actual.chat/nginx/nginx.proxy-headers.conf:/etc/nginx/nginx.proxy-headers.conf
      - ./.config/local.actual.chat/nginx/snippets:/etc/nginx/snippets
      - ./.config/local.actual.chat/nginx/dhparam.pem:/etc/nginx/dhparam.pem
    # To have logging, uncomment line below and adjust path to log file and ensure it exists
    #  - ./.config/local.actual.chat/log/nginx/access.log:/var/log/nginx/access.log
    extra_hosts:
      - "local.actual.chat:host-gateway"
      - "embedded.actual.chat:host-gateway"
  dns-forwarder:
    image: janeczku/go-dnsmasq
    network_mode: bridge
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    expose:
      - 53
  smtp4dev:
    image: rnwood/smtp4dev:linux-amd64-v3
    ports:
      - "5000:80"
      - "25:25"
  elasticsearch:
    image: elasticsearch:8.11.4
    volumes:
      - ./artifacts/elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    environment:
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=elastic
      - xpack.security.enabled=false
      - discovery.type=single-node
    healthcheck:
      interval: 10s
      retries: 80
      test: curl --write-out 'HTTP %{http_code}' --fail --silent --output /dev/null http://localhost:9200/
    deploy:
      resources:
        limits:
          memory: 6G
    ulimits:
      memlock:
        soft: -1
        hard: -1
  kibana:
    depends_on:
      - elasticsearch
    image: kibana:8.11.4
    volumes:
      - ./artifacts/kibana-data:/usr/share/kibana/data
    ports:
     - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.2'
