version: '3.4'
services:
  redis:
    image: "redis:alpine"
    ports:
     - "6379:6379"
  db:
    image: "docker.io/bitnami/postgresql:13"
    environment:
      POSTGRES_PASSWORD: "ActualChat.Dev.2021.07"
    expose:
     - "5432"
    ports:
     - "5432:5432"

  app_debug:
    build:
      context: .
      target: app_debug
    depends_on:
     - db
    ports:
      - "7080:7080"
    environment:
      ASPNETCORE_URLS: "http://*:7080"
      ActualChat__Users__Db: "Server=db;Database=ac_dev_users;Port=5432;User Id=postgres;Password=ActualChat.Dev.2021.07"
      ActualChat__Todos__Db: "Server=db;Database=ac_dev_todos;Port=5432;User Id=postgres;Password=ActualChat.Dev.2021.07"

  app_release:
    build:
      context: .
      target: app_release
    depends_on:
     - db
    ports:
     - "80:80"
    environment:
      ASPNETCORE_URLS: "http://*:80"
      HTTPS_PORT: 443
      ActualChat__Users__Db: "Server=db;Database=ac_dev_users;Port=5432;User Id=postgres;Password=ActualChat.Dev.2021.07"
      ActualChat__Todos__Db: "Server=db;Database=ac_dev_todos;Port=5432;User Id=postgres;Password=ActualChat.Dev.2021.07"
