version: '3.4'
services:
  jaeger:
    image: "jaegertracing/all-in-one:1.28.0"
    ports:
      - "16686:16686"
  otel-collector:
    image: "otel/opentelemetry-collector-contrib:0.38.0"
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317"
    depends_on:
      - jaeger