version: '3.4'
services:
  redis:
    image: "redis:6.2.6-alpine3.14"
    ports:
     - "6379:6379"
  postgres:
    image: "postgres:14.0-alpine3.14"
    environment:
      #POSTGRES_PASSWORD: "z7@bAZ!hFq6"
      POSTGRES_PASSWORD: "ActualChat.Dev.2021.07"
      POSTGRES_USER: "postgres"
      POSTGRES_HOST_AUTH_METHOD: "password"
    ports:
     - "5432:5432"