version: '3.8'
services:
  imageproxy:
    image: willnorris/imageproxy:latest
    expose:
      - 8080
    environment:
      - IMAGEPROXY_CACHE=memory:100:24h
      - SSL_CERT_DIR=/usr/local/share/ca-certificates/
    volumes:
      - ./data/ssl/local.actual.chat.crt:/usr/local/share/ca-certificates/local.actual.chat.crt
    extra_hosts:
      - "cdn.local.actual.chat:host-gateway"
  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/ssl:/etc/ssl
      - ./data/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./data/nginx/snippets:/etc/nginx/snippets
      - ./data/nginx/dhparam.pem:/etc/nginx/dhparam.pem
      - ./data/log/nginx/access.log:/var/log/nginx/access.log
    extra_hosts:
      - "local.actual.chat:host-gateway"
