version: '3.7'
services:
  tests:
    build:
      context: .
      target: base
      args:
        GITHUB_TOKEN: ${GITHUB_TOKEN}
    volumes:
      - ./artifacts/tests/docker-output/:/src/artifacts/tests/output/
    environment:
      NPM_READ_TOKEN: ${NPM_READ_TOKEN}
    command: >-
      /bin/sh -c "
      dotnet build --nologo --no-restore --configuration Debug &&
      dotnet run --project build --configuration Release --no-build --no-launch-profile -- --configuration Debug unit-tests
      "
