version: '3.8'
services:
  redis:
    image: "redis:6.2.6-alpine3.14"
    ports:
     - "6379:6379"
  postgres:
    image: "postgres:14.0-alpine3.14"
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_HOST_AUTH_METHOD: "password"
    ports:
     - "5432:5432"
    entrypoint: ["docker-entrypoint.sh", "-c", "shared_buffers=256MB", "-c", "max_connections=1000"]
  imageproxy:
    image: willnorris/imageproxy:latest
    expose:
      - 8080
    environment:
      - IMAGEPROXY_CACHE=memory:100:24h
      - SSL_CERT_DIR=/usr/local/share/ca-certificates/
    volumes:
      - ./.config/local.actual.chat/ssl/local.actual.chat.crt:/usr/local/share/ca-certificates/local.actual.chat.crt
    extra_hosts:
      - "cdn.local.actual.chat:host-gateway"
  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./.config/local.actual.chat/ssl:/etc/ssl
      - ./.config/local.actual.chat/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./.config/local.actual.chat/nginx/snippets:/etc/nginx/snippets
      - ./.config/local.actual.chat/nginx/dhparam.pem:/etc/nginx/dhparam.pem
    # To have logging, uncomment line below and adjust path to log file and ensure it exists
    #  - ./.config/local.actual.chat/log/nginx/access.log:/var/log/nginx/access.log
    extra_hosts:
      - "local.actual.chat:host-gateway"
