call EF-Migrations.cmd Flows.Service add %*
call EF-Migrations.cmd Chat.Service add %*
call EF-Migrations.cmd Contacts.Service add %*
call EF-Migrations.cmd Invite.Service add %*
call EF-Migrations.cmd Media.Service add %*
call EF-Migrations.cmd MLSearch.Service add %*
call EF-Migrations.cmd Notification.Service add %*
call EF-Migrations.cmd Search.Service add %*
call EF-Migrations.cmd Users.Service add %*
