ARG VARIANT=1-3.12-bullseye

FROM mcr.microsoft.com/devcontainers/python:${VARIANT}

ARG USER_NAME

RUN \
    # Install git lfs
    apt-get update && \
    apt-get -y install git-lfs && \
    # Install & configure Python tools
    pipx install poetry==1.8.3 && \
    poetry config virtualenvs.create false && \
    # Update container user
    groupmod -n ${USER_NAME} vscode && \
    usermod -l ${USER_NAME} vscode && \
    usermod -d /home/${USER_NAME} -m ${USER_NAME} && \
    # Persist bash history
    SNIPPET="export PROMT_COMMAND='history -a' && export HISTFILE=/commandhistory/.bash_history" && \
    mkdir /commandhistory && \
    touch /commandhistory/.bash_history && \
    chown -R ${USER_NAME} /commandhistory && \
    echo "$SNIPPET" >> "/home/${USER_NAME}/.bashrc"

USER ${USER_NAME}

RUN \
    # Create Python's venv for the project
    python -m venv ~/.venv/chatbot
