namespace ActualChat.UI.Blazor.Components;

public enum SquareSize
{
    Size0 = 0, // pic-size-0 w-0 h-0 - we need this to make sure these classes are generated by tailwind
    Size4 = 4, // pic-size-4 w-4 h-4
    Size5 = 5, // pic-size-5 w-5 h-5
    Size6 = 6, // pic-size-6 w-6 h-6
    Size7 = 7, // pic-size-7 w-7 h-7
    Size8 = 8, // pic-size-8 w-8 h-8
    Size9 = 9, // pic-size-9 w-9 h-9
    Size10 = 10, // pic-size-10 w-10 h-10
    Size12 = 12, // pic-size-12 w-12 h-12
    Size14 = 14, // pic-size-14 w-14 h-14
    Size16 = 16, // pic-size-16 w-16 h-16
    Size20 = 20, // pic-size-20 w-20 h-20
    Size24 = 24, // pic-size-24 w-24 h-24
    Size30 = 30, // pic-size-30 w-30 h-30
    SizeFull = 100, // pic-size-full-screen w-full h-full
}
