<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\Core\Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Using Remove="ActualChat.Users" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MemoryPack" Condition="$(UseMemoryPack)" />
    <PackageReference Include="ActualLab.Fusion.Blazor" />
  </ItemGroup>
</Project>
