// <auto-generated />
using System;
using ActualChat.Media.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ActualChat.Media.Migrations;

[DbContext(typeof(MediaDbContext))]
partial class MediaDbContextModelSnapshot : ModelSnapshot
{
    // If you encounter a merge conflict in the line below, it means you need to
    // discard one of the migration branches and recreate its migrations on top of
    // the other branch. See https://aka.ms/efcore-docs-migrations-conflicts for more info.
    public override string LastMigrationId => "20260916085525_AddImageSuggestions";

    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "11.0.0-preview.6.26359.118")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("ActualChat.Media.Db.DbGrabStatus", b =>
            {
                b.Property<string>("Id")
                    .HasColumnType("text")
                    .HasColumnName("id")
                    .UseCollation("C");

                b.Property<DateTime>("ModifiedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("modified_at");

                b.Property<bool>("Success")
                    .HasColumnType("boolean")
                    .HasColumnName("success");

                b.Property<long>("Version")
                    .IsConcurrencyToken()
                    .HasColumnType("bigint")
                    .HasColumnName("version");

                b.HasKey("Id")
                    .HasName("pk_grab_statuses");

                b.ToTable("grab_statuses");
            });

        modelBuilder.Entity("ActualChat.Media.Db.DbImageSuggestion", b =>
            {
                b.Property<string>("Id")
                    .HasColumnType("text")
                    .HasColumnName("id")
                    .UseCollation("C");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("created_at");

                b.Property<DateTime?>("DismissedUntil")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("dismissed_until");

                b.Property<string>("ImageDescription")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("image_description");

                b.Property<string>("MediaId")
                    .HasColumnType("text")
                    .HasColumnName("media_id")
                    .UseCollation("C");

                b.Property<long>("Version")
                    .IsConcurrencyToken()
                    .HasColumnType("bigint")
                    .HasColumnName("version");

                b.HasKey("Id")
                    .HasName("pk_image_suggestions");

                b.ToTable("image_suggestions");
            });

        modelBuilder.Entity("ActualChat.Media.Db.DbLinkPreview", b =>
            {
                b.Property<string>("Id")
                    .HasColumnType("text")
                    .HasColumnName("id")
                    .UseCollation("C");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("created_at");

                b.Property<string>("Description")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("description");

                b.Property<string>("MetadataJson")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("metadata_json");

                b.Property<DateTime>("ModifiedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("modified_at");

                b.Property<string>("ThumbnailMediaId")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("thumbnail_media_id")
                    .UseCollation("C");

                b.Property<string>("Title")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("title");

                b.Property<string>("Url")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("url");

                b.Property<long>("Version")
                    .IsConcurrencyToken()
                    .HasColumnType("bigint")
                    .HasColumnName("version");

                b.HasKey("Id")
                    .HasName("pk_link_previews");

                b.ToTable("link_previews");
            });

        modelBuilder.Entity("ActualChat.Media.Db.DbMedia", b =>
            {
                b.Property<string>("Id")
                    .HasColumnType("text")
                    .HasColumnName("id")
                    .UseCollation("C");

                b.Property<string>("BlobId")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("blob_id")
                    .UseCollation("C");

                b.Property<int>("Kind")
                    .HasColumnType("integer")
                    .HasColumnName("kind");

                b.Property<string>("LocalId")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("local_id")
                    .UseCollation("C");

                b.Property<string>("MetadataJson")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("metadata_json");

                b.Property<byte[]>("Placeholder")
                    .HasColumnType("bytea")
                    .HasColumnName("placeholder");

                b.Property<string>("Scope")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("scope")
                    .UseCollation("C");

                b.Property<string>("ThumbnailId")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("thumbnail_id")
                    .UseCollation("C");

                b.Property<string>("UserId")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("user_id")
                    .UseCollation("C");

                b.Property<long>("Version")
                    .IsConcurrencyToken()
                    .HasColumnType("bigint")
                    .HasColumnName("version");

                b.HasKey("Id")
                    .HasName("pk_media");

                b.HasIndex("BlobId")
                    .HasDatabaseName("ix_media_blob_id");

                b.ToTable("media");
            });

        modelBuilder.Entity("ActualChat.Media.Db.DbMediaProgress", b =>
            {
                b.Property<string>("Id")
                    .HasColumnType("text")
                    .HasColumnName("id")
                    .UseCollation("C");

                b.Property<string>("Error")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("error");

                b.Property<int>("Stage")
                    .HasColumnType("integer")
                    .HasColumnName("stage");

                b.Property<double>("StageProgress")
                    .HasColumnType("double precision")
                    .HasColumnName("stage_progress");

                b.Property<long>("Version")
                    .IsConcurrencyToken()
                    .HasColumnType("bigint")
                    .HasColumnName("version");

                b.HasKey("Id")
                    .HasName("pk_media_progresses");

                b.ToTable("media_progresses");
            });

        modelBuilder.Entity("ActualLab.Fusion.EntityFramework.Operations.DbEvent", b =>
            {
                b.Property<string>("Uuid")
                    .HasColumnType("text")
                    .HasColumnName("uuid")
                    .UseCollation("C");

                b.Property<DateTime>("DelayUntil")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("delay_until");

                b.Property<DateTime>("LoggedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("logged_at");

                b.Property<int>("State")
                    .HasColumnType("integer")
                    .HasColumnName("state");

                b.Property<string>("ValueJson")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("value_json");

                b.Property<long>("Version")
                    .IsConcurrencyToken()
                    .HasColumnType("bigint")
                    .HasColumnName("version");

                b.HasKey("Uuid")
                    .HasName("pk_events");

                b.HasIndex("DelayUntil")
                    .HasDatabaseName("ix_events_pending")
                    .HasFilter("state = 0");

                b.HasIndex("DelayUntil", "State")
                    .HasDatabaseName("ix_events_delay_until_state_non_new")
                    .HasFilter("state != 0");

                b.ToTable("_events");
            });

        modelBuilder.Entity("ActualLab.Fusion.EntityFramework.Operations.DbOperation", b =>
            {
                var index = b.Property<long>("Index")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("bigint")
                    .HasColumnName("index");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(index);

                b.Property<string>("CommandJson")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("command_json");

                b.Property<string>("HostId")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("host_id")
                    .UseCollation("C");

                b.Property<string>("ItemsJson")
                    .HasColumnType("text")
                    .HasColumnName("items_json");

                b.Property<DateTime>("LoggedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("logged_at");

                b.Property<string>("NestedOperations")
                    .HasColumnType("text")
                    .HasColumnName("nested_operations");

                b.Property<string>("Uuid")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("uuid")
                    .UseCollation("C");

                b.HasKey("Index")
                    .HasName("pk_operations");

                b.HasIndex("LoggedAt")
                    .HasDatabaseName("ix_operations_logged_at");

                b.HasIndex("Uuid")
                    .IsUnique()
                    .HasDatabaseName("ix_operations_uuid");

                b.ToTable("_operations");
            });
#pragma warning restore 612, 618
    }
}
