<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <!-- NOTE: android target is a workaround for windows  -->
    <TargetFrameworks Condition="!$([MSBuild]::IsOSPlatform('osx'))">net9.0-android;</TargetFrameworks>
    <TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('osx'))">net9.0-ios;</TargetFrameworks>
    <OutputType>Library</OutputType>
    <UseMauiEssentials>true</UseMauiEssentials>
    <SingleProject>true</SingleProject>

    <ApplicationId>chat.actual.app.share</ApplicationId>
    <ApplicationTitle>Voxt</ApplicationTitle>

    <IsAppExtension>True</IsAppExtension>
    <IsWatchExtension>False</IsWatchExtension>
    <Registrar>static</Registrar>

<!--    <ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>-->
<!--    <ApplicationVersion>1</ApplicationVersion>-->

    <SupportedOSPlatformVersion Condition="$(TargetFramework.Contains('-ios'))">16.4</SupportedOSPlatformVersion>
  </PropertyGroup>

  <PropertyGroup Condition="'$(IsDevMaui)' == ''">
    <IsDevMaui>true</IsDevMaui>
  </PropertyGroup>

  <PropertyGroup Condition="'$(IsDevMaui)' == 'true'">
    <DefineConstants>$(DefineConstants);IS_DEV_MAUI</DefineConstants>
    <ApplicationId>chat.actual.dev.app.share</ApplicationId>
    <ApplicationTitle>Voxt (Dev)</ApplicationTitle>
  </PropertyGroup>

  <!-- Build properties -->
  <!-- Both: Debug & Release configuration -->
  <PropertyGroup>
    <CodesignEntitlements Condition="'$(IsDevMaui)' == 'true'">Entitlements.dev.plist</CodesignEntitlements>
    <CodesignEntitlements Condition="'$(IsDevMaui)' != 'true'">Entitlements.prod.plist</CodesignEntitlements>
    <MtouchLink>SdkOnly</MtouchLink>
  </PropertyGroup>

  <!-- Debug configuration -->
  <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
    <CodesignProvision>chat.actual.dev.app.share</CodesignProvision>
    <UseInterpreter>true</UseInterpreter>
  </PropertyGroup>

  <!-- Release configuration -->
  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <CodesignProvision Condition="'$(IsDevMaui)' == 'true'">App Store Share Dev</CodesignProvision>
    <CodesignProvision Condition="'$(IsDevMaui)' != 'true'">App Store Share</CodesignProvision>
    <CodesignKey>Apple Distribution: Actual Chat Inc. (M287G8G83F)</CodesignKey>
    <UseInterpreter>true</UseInterpreter>
    <MTouchInterpreter>-ActualChat</MTouchInterpreter>
  </PropertyGroup>

  <!-- Environment -->
  <PropertyGroup>
    <FixedEnvironment Condition="'$(FixedEnvironment)' == ''" />
    <!-- Produces tons of misleading warnings if true! -->
    <EnforceCodeStyleInBuild>false</EnforceCodeStyleInBuild>
  </PropertyGroup>
  <PropertyGroup Condition="'$(FixedEnvironment)' == 'Production'">
    <DefineConstants>$(DefineConstants);IS_PRODUCTION_ENV</DefineConstants>
  </PropertyGroup>


  <ItemGroup>
    <BundleResource Include="..\..\..\resources\images\converted\error-barrier-image.png" Link="%(Filename)%(Extension)" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Api.Contracts\Api.Contracts.csproj" />
    <ProjectReference Include="..\Maui\Maui.csproj" Condition="$(TargetFramework.Contains('-ios')) AND $([MSBuild]::IsOSPlatform('osx'))" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Maui.Essentials" />
    <PackageReference Include="Svg.Skia" />
  </ItemGroup>

  <!-- Workaround for excluding C# files from compilation for non-iOS targets -->
  <ItemGroup Condition="!$(TargetFramework.Contains('-ios'))">
    <Compile Remove="**\*.cs"/>
    <None Include="**\*.cs" Exclude="$(DefaultItemExcludes);$(DefaultExcludesInProjectFolder)"/>
  </ItemGroup>

</Project>
