// <auto-generated>
// This file is generated by App.AotHelper -g. Do not edit manually.
// </auto-generated>

#pragma warning disable CS0618 // Obsolete types are still needed for AOT retention

using ActualChat.Aot;

namespace ActualChat.Module;

internal partial class ApiContractsAotSource : IAotSource
{
    public void KeepTypes()
    {
        if (CodeKeeper.AlwaysTrue)
            return;

        CodeKeeper.Keep<global::ActualChat.Chat.IAliases>();
        CodeKeeper.Keep<global::ActualChat.Chat.IAuthors>();
        CodeKeeper.Keep<global::ActualChat.Chat.IChatThreads>();
        CodeKeeper.Keep<global::ActualChat.Chat.IChats>();
        CodeKeeper.Keep<global::ActualChat.Chat.IConversations>();
        CodeKeeper.Keep<global::ActualChat.Chat.IDiagnostics>();
        CodeKeeper.Keep<global::ActualChat.Chat.ILegacyChats>();
        CodeKeeper.Keep<global::ActualChat.Chat.IMentions>();
        CodeKeeper.Keep<global::ActualChat.Chat.IPlaces>();
        CodeKeeper.Keep<global::ActualChat.Chat.IReactions>();
        CodeKeeper.Keep<global::ActualChat.Chat.IRoles>();
        CodeKeeper.Keep<global::ActualChat.Chat.ITranslations>();
        CodeKeeper.Keep<global::ActualChat.Contacts.IContacts>();
        CodeKeeper.Keep<global::ActualChat.Contacts.IExternalContactHashes>();
        CodeKeeper.Keep<global::ActualChat.Contacts.IExternalContacts>();
        CodeKeeper.Keep<global::ActualChat.Invite.IInvites>();
        CodeKeeper.Keep<global::ActualChat.Media.IMedia>();
        CodeKeeper.Keep<global::ActualChat.Media.IMediaLinkPreviews>();
        CodeKeeper.Keep<global::ActualChat.Media.IUploads>();
        CodeKeeper.Keep<global::ActualChat.Notification.INotifications>();
        CodeKeeper.Keep<global::ActualChat.Search.ISearch>();
        CodeKeeper.Keep<global::ActualChat.Streaming.ILiveAudioStreams>();
        CodeKeeper.Keep<global::ActualChat.Streaming.ILiveVideoStreams>();
        CodeKeeper.Keep<global::ActualChat.Users.IAccounts>();
        CodeKeeper.Keep<global::ActualChat.Users.IAvatars>();
        CodeKeeper.Keep<global::ActualChat.Users.IChatPositions>();
        CodeKeeper.Keep<global::ActualChat.Users.IChatUsages>();
        CodeKeeper.Keep<global::ActualChat.Users.IEmailAuth>();
        CodeKeeper.Keep<global::ActualChat.Users.IEmails>();
        CodeKeeper.Keep<global::ActualChat.Users.IMobileSessions>();
        CodeKeeper.Keep<global::ActualChat.Users.IPhoneAuth>();
        CodeKeeper.Keep<global::ActualChat.Users.IPhones>();
        CodeKeeper.Keep<global::ActualChat.Users.ISessionTemporals>();
        CodeKeeper.Keep<global::ActualChat.Users.ISystemProperties>();
        CodeKeeper.Keep<global::ActualChat.Users.ITimeZones>();
        CodeKeeper.Keep<global::ActualChat.Users.IUserPresences>();
        CodeKeeper.KeepSerializable<global::ActualChat.Chat.AliasTarget>();
        CodeKeeper.KeepSerializable<global::ActualChat.Chat.Authors_Exclude>();
        CodeKeeper.KeepSerializable<global::ActualChat.Chat.Authors_Invite>();
        CodeKeeper.KeepSerializable<global::ActualChat.Chat.Authors_Join>();
        CodeKeeper.KeepSerializable<global::ActualChat.Chat.Authors_Leave>();
        CodeKeeper.KeepSerializable<global::ActualChat.Chat.Authors_PromoteToOwner>();
        CodeKeeper.KeepSerializable<global::ActualChat.Chat.Authors_Restore>();
        CodeKeeper.KeepSerializable<global::ActualChat.Chat.Authors_SetAvatar>();
        CodeKeeper.KeepSerializable<global::ActualChat.Chat.ChatThreads_Start>();
        CodeKeeper.KeepSerializable<global::ActualChat.Chat.ChatThreads_ToggleThreadFollowStatus>();
        CodeKeeper.KeepSerializable<global::ActualChat.Chat.Chat_CopyChat>();
        CodeKeeper.KeepSerializable<global::ActualChat.Chat.Chat_CopyChatResult>();
        CodeKeeper.KeepSerializable<global::ActualChat.Chat.Chat_PublishCopiedChat>();
        CodeKeeper.KeepSerializable<global::ActualChat.Chat.Chats_Change>();
        CodeKeeper.KeepSerializable<global::ActualChat.Chat.Chats_ForwardEntries>();
        CodeKeeper.KeepSerializable<global::ActualChat.Chat.Chats_GetOrCreateFromTemplate>();
        CodeKeeper.KeepSerializable<global::ActualChat.Chat.Chats_RemoveEntries>();
        CodeKeeper.KeepSerializable<global::ActualChat.Chat.Chats_RemoveEntry>();
        CodeKeeper.KeepSerializable<global::ActualChat.Chat.Chats_RestoreEntries>();
        CodeKeeper.KeepSerializable<global::ActualChat.Chat.Chats_RestoreEntry>();
        CodeKeeper.KeepSerializable<global::ActualChat.Chat.Chats_UpsertEntry>();
        CodeKeeper.KeepSerializable<global::ActualChat.Chat.Chats_UpsertTextEntry>();
        CodeKeeper.KeepSerializable<global::ActualChat.Chat.Conversations_Summarize>();
        CodeKeeper.KeepSerializable<global::ActualChat.Chat.MeshDiagInfo>();
        CodeKeeper.KeepSerializable<global::ActualChat.Chat.MeshRpcPeerRefDiagInfo>();
        CodeKeeper.KeepSerializable<global::ActualChat.Chat.NodeDiagInfo>();
        CodeKeeper.KeepSerializable<global::ActualChat.Chat.Places_Change>();
        CodeKeeper.KeepSerializable<global::ActualChat.Chat.Places_Exclude>();
        CodeKeeper.KeepSerializable<global::ActualChat.Chat.Places_Invite>();
        CodeKeeper.KeepSerializable<global::ActualChat.Chat.Places_Join>();
        CodeKeeper.KeepSerializable<global::ActualChat.Chat.Places_Leave>();
        CodeKeeper.KeepSerializable<global::ActualChat.Chat.Places_PromoteToOwner>();
        CodeKeeper.KeepSerializable<global::ActualChat.Chat.Places_Restore>();
        CodeKeeper.KeepSerializable<global::ActualChat.Chat.Reactions_React>();
        CodeKeeper.KeepSerializable<global::ActualChat.Chat.Roles_Change>();
        CodeKeeper.KeepSerializable<global::ActualChat.Chat.RpcPeerDiagInfo>();
        CodeKeeper.KeepSerializable<global::ActualChat.Chat.ThreadStat>();
        CodeKeeper.KeepSerializable<global::ActualChat.Contacts.Contacts_Change>();
        CodeKeeper.KeepSerializable<global::ActualChat.Contacts.Contacts_Touch>();
        CodeKeeper.KeepSerializable<global::ActualChat.Contacts.ExternalContactChange>();
        CodeKeeper.KeepSerializable<global::ActualChat.Contacts.ExternalContactHashes_Change>();
        CodeKeeper.KeepSerializable<global::ActualChat.Contacts.ExternalContacts_BulkChange>();
        CodeKeeper.KeepSerializable<global::ActualChat.Invite.Invites_Generate>();
        CodeKeeper.KeepSerializable<global::ActualChat.Invite.Invites_Revoke>();
        CodeKeeper.KeepSerializable<global::ActualChat.Invite.Invites_Use>();
        CodeKeeper.KeepSerializable<global::ActualChat.Media.GifItem>();
        CodeKeeper.KeepSerializable<global::ActualChat.Media.GifSearchResult>();
        CodeKeeper.KeepSerializable<global::ActualChat.Media.Media_ProcessUpload>();
        CodeKeeper.KeepSerializable<global::ActualChat.Media.Media_RemoveMedia>();
        CodeKeeper.KeepSerializable<global::ActualChat.Media.Media_ReserveMedia>();
        CodeKeeper.KeepSerializable<global::ActualChat.Media.Media_UpdateProgress>();
        CodeKeeper.KeepSerializable<global::ActualChat.Media.Uploads_Append>();
        CodeKeeper.KeepSerializable<global::ActualChat.Media.Uploads_ConvertToMediaRef>();
        CodeKeeper.KeepSerializable<global::ActualChat.Media.Uploads_Create>();
        CodeKeeper.KeepSerializable<global::ActualChat.Media.Uploads_Remove>();
        CodeKeeper.KeepSerializable<global::ActualChat.Media.Uploads_StartProcessUpload>();
        CodeKeeper.KeepSerializable<global::ActualChat.Notification.Notifications_DeregisterDevice>();
        CodeKeeper.KeepSerializable<global::ActualChat.Notification.Notifications_Handle>();
        CodeKeeper.KeepSerializable<global::ActualChat.Notification.Notifications_NotifyMembers>();
        CodeKeeper.KeepSerializable<global::ActualChat.Notification.Notifications_NotifyMentionedMembers>();
        CodeKeeper.KeepSerializable<global::ActualChat.Notification.Notifications_RegisterDevice>();
        CodeKeeper.KeepSerializable<global::ActualChat.Users.Accounts_CreateApiKey>();
        CodeKeeper.KeepSerializable<global::ActualChat.Users.Accounts_DeactivateAllSessions>();
        CodeKeeper.KeepSerializable<global::ActualChat.Users.Accounts_DeactivateSession>();
        CodeKeeper.KeepSerializable<global::ActualChat.Users.Accounts_DeleteOwn>();
        CodeKeeper.KeepSerializable<global::ActualChat.Users.Accounts_SignOut>();
        CodeKeeper.KeepSerializable<global::ActualChat.Users.Accounts_Update>();
        CodeKeeper.KeepSerializable<global::ActualChat.Users.Avatars_Change>();
        CodeKeeper.KeepSerializable<global::ActualChat.Users.Avatars_SetDefault>();
        CodeKeeper.KeepSerializable<global::ActualChat.Users.ChatPositions_Set>();
        CodeKeeper.KeepSerializable<global::ActualChat.Users.ChatUsages_RegisterUsage>();
        CodeKeeper.KeepSerializable<global::ActualChat.Users.EmailAuth_SendTotp>();
        CodeKeeper.KeepSerializable<global::ActualChat.Users.EmailAuth_ValidateTotp>();
        CodeKeeper.KeepSerializable<global::ActualChat.Users.EmailAuth_VerifyEmail>();
        CodeKeeper.KeepSerializable<global::ActualChat.Users.Emails_SendDigest>();
        CodeKeeper.KeepSerializable<global::ActualChat.Users.PhoneAuth_SendTotp>();
        CodeKeeper.KeepSerializable<global::ActualChat.Users.PhoneAuth_ValidateTotp>();
        CodeKeeper.KeepSerializable<global::ActualChat.Users.PhoneAuth_VerifyPhone>();
        CodeKeeper.KeepSerializable<global::ActualChat.Users.RecaptchaValidationResult>();
        CodeKeeper.KeepSerializable<global::ActualChat.Users.ServerApiInfo>();
        CodeKeeper.KeepSerializable<global::ActualChat.Users.SessionTemporals_Set>();
        CodeKeeper.KeepSerializable<global::ActualChat.Users.SystemProperties_InvalidateEverything>();
        CodeKeeper.KeepSerializable<global::ActualChat.Users.SystemProperties_PruneComputedGraph>();
        CodeKeeper.KeepSerializable<global::ActualChat.Users.UserPresences_CheckIn>();

        // MessagePack formatter types for serializable root types (auto-discovered)
        CodeKeeper.Keep("ActualChat.Internal.StringIdentifierMessagePackFormatter`1[[ActualChat.AliasId, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], ActualChat.Core, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("ActualChat.Internal.StringIdentifierMessagePackFormatter`1[[ActualChat.AuthorId, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], ActualChat.Core, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("ActualChat.Internal.StringIdentifierMessagePackFormatter`1[[ActualChat.ChatEntryId, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], ActualChat.Core, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("ActualChat.Internal.StringIdentifierMessagePackFormatter`1[[ActualChat.ChatId, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], ActualChat.Core, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("ActualChat.Internal.StringIdentifierMessagePackFormatter`1[[ActualChat.ContactId, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], ActualChat.Core, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("ActualChat.Internal.StringIdentifierMessagePackFormatter`1[[ActualChat.ConversationId, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], ActualChat.Core, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("ActualChat.Internal.StringIdentifierMessagePackFormatter`1[[ActualChat.Email, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], ActualChat.Core, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("ActualChat.Internal.StringIdentifierMessagePackFormatter`1[[ActualChat.Emoji, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], ActualChat.Core, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("ActualChat.Internal.StringIdentifierMessagePackFormatter`1[[ActualChat.ExternalContactId, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], ActualChat.Core, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("ActualChat.Internal.StringIdentifierMessagePackFormatter`1[[ActualChat.MediaId, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], ActualChat.Core, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("ActualChat.Internal.StringIdentifierMessagePackFormatter`1[[ActualChat.NotificationId, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], ActualChat.Core, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("ActualChat.Internal.StringIdentifierMessagePackFormatter`1[[ActualChat.Phone, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], ActualChat.Core, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("ActualChat.Internal.StringIdentifierMessagePackFormatter`1[[ActualChat.PlaceChatId, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], ActualChat.Core, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("ActualChat.Internal.StringIdentifierMessagePackFormatter`1[[ActualChat.PlaceId, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], ActualChat.Core, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("ActualChat.Internal.StringIdentifierMessagePackFormatter`1[[ActualChat.RoleId, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], ActualChat.Core, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("ActualChat.Internal.StringIdentifierMessagePackFormatter`1[[ActualChat.ThreadChatId, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], ActualChat.Core, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("ActualChat.Internal.StringIdentifierMessagePackFormatter`1[[ActualChat.UploadId, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], ActualChat.Core, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("ActualChat.Internal.StringIdentifierMessagePackFormatter`1[[ActualChat.UserDeviceId, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], ActualChat.Core, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("ActualChat.Internal.StringIdentifierMessagePackFormatter`1[[ActualChat.UserId, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], ActualChat.Core, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("ActualChat.Serialization.Internal.ChangeMessagePackFormatter`1[[ActualChat.Change`1[[ActualChat.Chat.ChatDiff, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], ActualChat.Core, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], ActualChat.Core, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("ActualChat.Serialization.Internal.ChangeMessagePackFormatter`1[[ActualChat.Change`1[[ActualChat.Chat.PlaceDiff, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], ActualChat.Core, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], ActualChat.Core, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("ActualChat.Serialization.Internal.ChangeMessagePackFormatter`1[[ActualChat.Change`1[[ActualChat.Chat.RoleDiff, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], ActualChat.Core, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], ActualChat.Core, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("ActualChat.Serialization.Internal.ChangeMessagePackFormatter`1[[ActualChat.Change`1[[ActualChat.Contacts.Contact, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], ActualChat.Core, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], ActualChat.Core, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("ActualChat.Serialization.Internal.ChangeMessagePackFormatter`1[[ActualChat.Change`1[[ActualChat.Contacts.ExternalContactFull, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], ActualChat.Core, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], ActualChat.Core, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("ActualChat.Serialization.Internal.ChangeMessagePackFormatter`1[[ActualChat.Change`1[[ActualChat.Contacts.ExternalContactsHash, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], ActualChat.Core, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], ActualChat.Core, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("ActualChat.Serialization.Internal.ChangeMessagePackFormatter`1[[ActualChat.Change`1[[ActualChat.Users.AvatarFull, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], ActualChat.Core, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], ActualChat.Core, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("ActualChat.Serialization.Internal.ChangeMessagePackFormatter`1[[ActualChat.Chat.ChatDiff, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], ActualChat.Core, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("ActualChat.Serialization.Internal.ChangeMessagePackFormatter`1[[ActualChat.Chat.PlaceDiff, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], ActualChat.Core, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("ActualChat.Serialization.Internal.ChangeMessagePackFormatter`1[[ActualChat.Chat.RoleDiff, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], ActualChat.Core, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("ActualChat.Serialization.Internal.ChangeMessagePackFormatter`1[[ActualChat.Contacts.Contact, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], ActualChat.Core, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("ActualChat.Serialization.Internal.ChangeMessagePackFormatter`1[[ActualChat.Contacts.ExternalContactFull, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], ActualChat.Core, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("ActualChat.Serialization.Internal.ChangeMessagePackFormatter`1[[ActualChat.Contacts.ExternalContactsHash, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], ActualChat.Core, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("ActualChat.Serialization.Internal.ChangeMessagePackFormatter`1[[ActualChat.Users.AvatarFull, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], ActualChat.Core, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("ActualChat.Serialization.Internal.SetDiffMessagePackFormatter`2[[ActualChat.AuthorId[], ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null],[ActualChat.AuthorId, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], ActualChat.Core, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("ActualLab.Fusion.Internal.SessionMessagePackFormatter, ActualLab.Fusion, Version=12.3.25.16053, Culture=neutral, PublicKeyToken=7c239217ec78b545");
        CodeKeeper.Keep("ActualLab.Serialization.Internal.OptionMessagePackFormatter`1[[ActualChat.Chat.ChatDiff, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], ActualLab.Core, Version=12.3.25.16053, Culture=neutral, PublicKeyToken=7c239217ec78b545");
        CodeKeeper.Keep("ActualLab.Serialization.Internal.OptionMessagePackFormatter`1[[ActualChat.Chat.PlaceDiff, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], ActualLab.Core, Version=12.3.25.16053, Culture=neutral, PublicKeyToken=7c239217ec78b545");
        CodeKeeper.Keep("ActualLab.Serialization.Internal.OptionMessagePackFormatter`1[[ActualChat.Chat.RoleDiff, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], ActualLab.Core, Version=12.3.25.16053, Culture=neutral, PublicKeyToken=7c239217ec78b545");
        CodeKeeper.Keep("ActualLab.Serialization.Internal.OptionMessagePackFormatter`1[[ActualChat.ChatId, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], ActualLab.Core, Version=12.3.25.16053, Culture=neutral, PublicKeyToken=7c239217ec78b545");
        CodeKeeper.Keep("ActualLab.Serialization.Internal.OptionMessagePackFormatter`1[[ActualChat.Contacts.Contact, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], ActualLab.Core, Version=12.3.25.16053, Culture=neutral, PublicKeyToken=7c239217ec78b545");
        CodeKeeper.Keep("ActualLab.Serialization.Internal.OptionMessagePackFormatter`1[[ActualChat.Contacts.ExternalContactFull, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], ActualLab.Core, Version=12.3.25.16053, Culture=neutral, PublicKeyToken=7c239217ec78b545");
        CodeKeeper.Keep("ActualLab.Serialization.Internal.OptionMessagePackFormatter`1[[ActualChat.Contacts.ExternalContactsHash, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], ActualLab.Core, Version=12.3.25.16053, Culture=neutral, PublicKeyToken=7c239217ec78b545");
        CodeKeeper.Keep("ActualLab.Serialization.Internal.OptionMessagePackFormatter`1[[ActualChat.UserId, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], ActualLab.Core, Version=12.3.25.16053, Culture=neutral, PublicKeyToken=7c239217ec78b545");
        CodeKeeper.Keep("ActualLab.Serialization.Internal.OptionMessagePackFormatter`1[[ActualChat.Users.AvatarFull, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], ActualLab.Core, Version=12.3.25.16053, Culture=neutral, PublicKeyToken=7c239217ec78b545");
        CodeKeeper.Keep("ActualLab.Serialization.Internal.OptionMessagePackFormatter`1[[ActualLab.Option`1[[ActualChat.Chat.ChatDiff, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], ActualLab.Core, Version=12.3.25.16053, Culture=neutral, PublicKeyToken=7c239217ec78b545]], ActualLab.Core, Version=12.3.25.16053, Culture=neutral, PublicKeyToken=7c239217ec78b545");
        CodeKeeper.Keep("ActualLab.Serialization.Internal.OptionMessagePackFormatter`1[[ActualLab.Option`1[[ActualChat.Chat.PlaceDiff, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], ActualLab.Core, Version=12.3.25.16053, Culture=neutral, PublicKeyToken=7c239217ec78b545]], ActualLab.Core, Version=12.3.25.16053, Culture=neutral, PublicKeyToken=7c239217ec78b545");
        CodeKeeper.Keep("ActualLab.Serialization.Internal.OptionMessagePackFormatter`1[[ActualLab.Option`1[[ActualChat.Chat.RoleDiff, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], ActualLab.Core, Version=12.3.25.16053, Culture=neutral, PublicKeyToken=7c239217ec78b545]], ActualLab.Core, Version=12.3.25.16053, Culture=neutral, PublicKeyToken=7c239217ec78b545");
        CodeKeeper.Keep("ActualLab.Serialization.Internal.OptionMessagePackFormatter`1[[ActualLab.Option`1[[ActualChat.ChatId, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], ActualLab.Core, Version=12.3.25.16053, Culture=neutral, PublicKeyToken=7c239217ec78b545]], ActualLab.Core, Version=12.3.25.16053, Culture=neutral, PublicKeyToken=7c239217ec78b545");
        CodeKeeper.Keep("ActualLab.Serialization.Internal.OptionMessagePackFormatter`1[[ActualLab.Option`1[[ActualChat.Contacts.Contact, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], ActualLab.Core, Version=12.3.25.16053, Culture=neutral, PublicKeyToken=7c239217ec78b545]], ActualLab.Core, Version=12.3.25.16053, Culture=neutral, PublicKeyToken=7c239217ec78b545");
        CodeKeeper.Keep("ActualLab.Serialization.Internal.OptionMessagePackFormatter`1[[ActualLab.Option`1[[ActualChat.Contacts.ExternalContactFull, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], ActualLab.Core, Version=12.3.25.16053, Culture=neutral, PublicKeyToken=7c239217ec78b545]], ActualLab.Core, Version=12.3.25.16053, Culture=neutral, PublicKeyToken=7c239217ec78b545");
        CodeKeeper.Keep("ActualLab.Serialization.Internal.OptionMessagePackFormatter`1[[ActualLab.Option`1[[ActualChat.Contacts.ExternalContactsHash, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], ActualLab.Core, Version=12.3.25.16053, Culture=neutral, PublicKeyToken=7c239217ec78b545]], ActualLab.Core, Version=12.3.25.16053, Culture=neutral, PublicKeyToken=7c239217ec78b545");
        CodeKeeper.Keep("ActualLab.Serialization.Internal.OptionMessagePackFormatter`1[[ActualLab.Option`1[[ActualChat.UserId, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], ActualLab.Core, Version=12.3.25.16053, Culture=neutral, PublicKeyToken=7c239217ec78b545]], ActualLab.Core, Version=12.3.25.16053, Culture=neutral, PublicKeyToken=7c239217ec78b545");
        CodeKeeper.Keep("ActualLab.Serialization.Internal.OptionMessagePackFormatter`1[[ActualLab.Option`1[[ActualChat.Users.AvatarFull, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], ActualLab.Core, Version=12.3.25.16053, Culture=neutral, PublicKeyToken=7c239217ec78b545]], ActualLab.Core, Version=12.3.25.16053, Culture=neutral, PublicKeyToken=7c239217ec78b545");
        CodeKeeper.Keep("ActualLab.Serialization.Internal.OptionMessagePackFormatter`1[[ActualLab.Option`1[[System.Nullable`1[[System.Boolean, System.Private.CoreLib, Version=10.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=10.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], ActualLab.Core, Version=12.3.25.16053, Culture=neutral, PublicKeyToken=7c239217ec78b545]], ActualLab.Core, Version=12.3.25.16053, Culture=neutral, PublicKeyToken=7c239217ec78b545");
        CodeKeeper.Keep("ActualLab.Serialization.Internal.OptionMessagePackFormatter`1[[ActualLab.Option`1[[System.Nullable`1[[System.Int64, System.Private.CoreLib, Version=10.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=10.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], ActualLab.Core, Version=12.3.25.16053, Culture=neutral, PublicKeyToken=7c239217ec78b545]], ActualLab.Core, Version=12.3.25.16053, Culture=neutral, PublicKeyToken=7c239217ec78b545");
        CodeKeeper.Keep("ActualLab.Serialization.Internal.OptionMessagePackFormatter`1[[System.Nullable`1[[System.Boolean, System.Private.CoreLib, Version=10.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=10.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], ActualLab.Core, Version=12.3.25.16053, Culture=neutral, PublicKeyToken=7c239217ec78b545");
        CodeKeeper.Keep("ActualLab.Serialization.Internal.OptionMessagePackFormatter`1[[System.Nullable`1[[System.Int64, System.Private.CoreLib, Version=10.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=10.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], ActualLab.Core, Version=12.3.25.16053, Culture=neutral, PublicKeyToken=7c239217ec78b545");
        CodeKeeper.Keep("ActualLab.Text.Internal.SymbolMessagePackFormatter, ActualLab.Core, Version=12.3.25.16053, Culture=neutral, PublicKeyToken=7c239217ec78b545");
        CodeKeeper.Keep("ActualLab.Time.Internal.MomentMessagePackFormatter, ActualLab.Core, Version=12.3.25.16053, Culture=neutral, PublicKeyToken=7c239217ec78b545");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Chat_AuthorFullFormatter25, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Chat_AuthorRulesFormatter27, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Chat_ChatDiffFormatter32, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Chat_ChatEntryAttachmentFormatter40, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Chat_ChatEntryForwardedFormatter37, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Chat_ChatFormatter29, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Chat_PlaceDiffFormatter65, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Chat_ReactionFormatter66, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Chat_RoleDiffFormatter70, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Contacts_ContactFormatter73, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Contacts_ExternalContactFullFormatter77, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Contacts_ExternalContactsHashFormatter78, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Hashing_HashStringFormatter1, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Invite_ChatInviteOptionFormatter83, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Invite_InviteDetailsFormatter86, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Invite_InviteFormatter85, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Invite_PlaceInviteOptionFormatter88, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Invite_UserInviteOptionFormatter87, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Media_MediaFormatter23, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Users_AccountFormatter74, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Users_AccountFullFormatter28, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Users_AvatarFormatter22, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Users_AvatarFullFormatter119, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ActualChat_Users_ChatPositionFormatter120, MessagePack.Resolvers.DynamicObjectResolver, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.Formatters.ArrayFormatter`1[[ActualChat.AuthorId, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], MessagePack, Version=3.1.4.0, Culture=neutral, PublicKeyToken=b4a0369545f0a1be");
        CodeKeeper.Keep("MessagePack.Formatters.ArrayFormatter`1[[ActualChat.Chat.ChatEntryAttachment, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], MessagePack, Version=3.1.4.0, Culture=neutral, PublicKeyToken=b4a0369545f0a1be");
        CodeKeeper.Keep("MessagePack.Formatters.ArrayFormatter`1[[ActualChat.Chat.MeshDiagInfo, ActualChat.Api.Contracts, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], MessagePack, Version=3.1.4.0, Culture=neutral, PublicKeyToken=b4a0369545f0a1be");
        CodeKeeper.Keep("MessagePack.Formatters.ArrayFormatter`1[[ActualChat.Chat.MeshRpcPeerRefDiagInfo, ActualChat.Api.Contracts, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], MessagePack, Version=3.1.4.0, Culture=neutral, PublicKeyToken=b4a0369545f0a1be");
        CodeKeeper.Keep("MessagePack.Formatters.ArrayFormatter`1[[ActualChat.Chat.NodeDiagInfo, ActualChat.Api.Contracts, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], MessagePack, Version=3.1.4.0, Culture=neutral, PublicKeyToken=b4a0369545f0a1be");
        CodeKeeper.Keep("MessagePack.Formatters.ArrayFormatter`1[[ActualChat.Chat.RpcPeerDiagInfo, ActualChat.Api.Contracts, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], MessagePack, Version=3.1.4.0, Culture=neutral, PublicKeyToken=b4a0369545f0a1be");
        CodeKeeper.Keep("MessagePack.Formatters.ArrayFormatter`1[[ActualChat.ChatEntryId, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], MessagePack, Version=3.1.4.0, Culture=neutral, PublicKeyToken=b4a0369545f0a1be");
        CodeKeeper.Keep("MessagePack.Formatters.ArrayFormatter`1[[ActualChat.ChatId, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], MessagePack, Version=3.1.4.0, Culture=neutral, PublicKeyToken=b4a0369545f0a1be");
        CodeKeeper.Keep("MessagePack.Formatters.ArrayFormatter`1[[ActualChat.Contacts.ExternalContactChange, ActualChat.Api.Contracts, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], MessagePack, Version=3.1.4.0, Culture=neutral, PublicKeyToken=b4a0369545f0a1be");
        CodeKeeper.Keep("MessagePack.Formatters.ArrayFormatter`1[[ActualChat.Media.GifItem, ActualChat.Api.Contracts, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], MessagePack, Version=3.1.4.0, Culture=neutral, PublicKeyToken=b4a0369545f0a1be");
        CodeKeeper.Keep("MessagePack.Formatters.ArrayFormatter`1[[ActualChat.SessionKind, ActualChat.Core, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], MessagePack, Version=3.1.4.0, Culture=neutral, PublicKeyToken=b4a0369545f0a1be");
        CodeKeeper.Keep("MessagePack.Formatters.ArrayFormatter`1[[ActualChat.UserId, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], MessagePack, Version=3.1.4.0, Culture=neutral, PublicKeyToken=b4a0369545f0a1be");
        CodeKeeper.Keep("MessagePack.Formatters.ArrayFormatter`1[[ActualLab.Collections.Internal.PropertyBagItem, ActualLab.Core, Version=12.3.25.16053, Culture=neutral, PublicKeyToken=7c239217ec78b545]], MessagePack, Version=3.1.4.0, Culture=neutral, PublicKeyToken=b4a0369545f0a1be");
        CodeKeeper.Keep("MessagePack.Formatters.ByteArrayFormatter, MessagePack, Version=3.1.4.0, Culture=neutral, PublicKeyToken=b4a0369545f0a1be");
        CodeKeeper.Keep("MessagePack.Formatters.GenericCollectionFormatter`2[[System.String, System.Private.CoreLib, Version=10.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[ActualLab.Api.ApiSet`1[[System.String, System.Private.CoreLib, Version=10.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], ActualLab.Core, Version=12.3.25.16053, Culture=neutral, PublicKeyToken=7c239217ec78b545]], MessagePack, Version=3.1.4.0, Culture=neutral, PublicKeyToken=b4a0369545f0a1be");
        CodeKeeper.Keep("MessagePack.Formatters.GenericDictionaryFormatter`3[[System.String, System.Private.CoreLib, Version=10.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.String, System.Private.CoreLib, Version=10.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[ActualLab.Api.ApiMap`2[[System.String, System.Private.CoreLib, Version=10.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.String, System.Private.CoreLib, Version=10.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], ActualLab.Core, Version=12.3.25.16053, Culture=neutral, PublicKeyToken=7c239217ec78b545]], MessagePack, Version=3.1.4.0, Culture=neutral, PublicKeyToken=b4a0369545f0a1be");
        CodeKeeper.Keep("MessagePack.Formatters.GenericEnumFormatter`1[[ActualChat.Chat.ChatPermissions, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], MessagePack, Version=3.1.4.0, Culture=neutral, PublicKeyToken=b4a0369545f0a1be");
        CodeKeeper.Keep("MessagePack.Formatters.GenericEnumFormatter`1[[ActualChat.Chat.SystemRole, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], MessagePack, Version=3.1.4.0, Culture=neutral, PublicKeyToken=b4a0369545f0a1be");
        CodeKeeper.Keep("MessagePack.Formatters.GenericEnumFormatter`1[[ActualChat.ChatKind, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], MessagePack, Version=3.1.4.0, Culture=neutral, PublicKeyToken=b4a0369545f0a1be");
        CodeKeeper.Keep("MessagePack.Formatters.GenericEnumFormatter`1[[ActualChat.CompatibilityLevel, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], MessagePack, Version=3.1.4.0, Culture=neutral, PublicKeyToken=b4a0369545f0a1be");
        CodeKeeper.Keep("MessagePack.Formatters.GenericEnumFormatter`1[[ActualChat.Media.MediaKind, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], MessagePack, Version=3.1.4.0, Culture=neutral, PublicKeyToken=b4a0369545f0a1be");
        CodeKeeper.Keep("MessagePack.Formatters.GenericEnumFormatter`1[[ActualChat.Media.MediaProcessingStage, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], MessagePack, Version=3.1.4.0, Culture=neutral, PublicKeyToken=b4a0369545f0a1be");
        CodeKeeper.Keep("MessagePack.Formatters.GenericEnumFormatter`1[[ActualChat.Notification.DeviceType, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], MessagePack, Version=3.1.4.0, Culture=neutral, PublicKeyToken=b4a0369545f0a1be");
        CodeKeeper.Keep("MessagePack.Formatters.GenericEnumFormatter`1[[ActualChat.SessionKind, ActualChat.Core, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], MessagePack, Version=3.1.4.0, Culture=neutral, PublicKeyToken=b4a0369545f0a1be");
        CodeKeeper.Keep("MessagePack.Formatters.GenericEnumFormatter`1[[ActualChat.Users.AccountStatus, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], MessagePack, Version=3.1.4.0, Culture=neutral, PublicKeyToken=b4a0369545f0a1be");
        CodeKeeper.Keep("MessagePack.Formatters.GenericEnumFormatter`1[[ActualChat.Users.ChatPositionKind, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], MessagePack, Version=3.1.4.0, Culture=neutral, PublicKeyToken=b4a0369545f0a1be");
        CodeKeeper.Keep("MessagePack.Formatters.GenericEnumFormatter`1[[ActualChat.Users.ChatUsageListKind, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], MessagePack, Version=3.1.4.0, Culture=neutral, PublicKeyToken=b4a0369545f0a1be");
        CodeKeeper.Keep("MessagePack.Formatters.GenericEnumFormatter`1[[ActualChat.Users.TotpPurpose, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], MessagePack, Version=3.1.4.0, Culture=neutral, PublicKeyToken=b4a0369545f0a1be");
        CodeKeeper.Keep("MessagePack.Formatters.Int64ArrayFormatter, MessagePack, Version=3.1.4.0, Culture=neutral, PublicKeyToken=b4a0369545f0a1be");
        CodeKeeper.Keep("MessagePack.Formatters.InterfaceReadOnlyListFormatter`1[[ActualChat.RoleId, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], MessagePack, Version=3.1.4.0, Culture=neutral, PublicKeyToken=b4a0369545f0a1be");
        CodeKeeper.Keep("MessagePack.Formatters.NullableBooleanFormatter, MessagePack, Version=3.1.4.0, Culture=neutral, PublicKeyToken=b4a0369545f0a1be");
        CodeKeeper.Keep("MessagePack.Formatters.NullableDateTimeFormatter, MessagePack, Version=3.1.4.0, Culture=neutral, PublicKeyToken=b4a0369545f0a1be");
        CodeKeeper.Keep("MessagePack.Formatters.NullableFormatter`1[[ActualChat.Chat.ChatPermissions, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], MessagePack, Version=3.1.4.0, Culture=neutral, PublicKeyToken=b4a0369545f0a1be");
        CodeKeeper.Keep("MessagePack.Formatters.NullableFormatter`1[[ActualChat.Chat.SystemRole, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], MessagePack, Version=3.1.4.0, Culture=neutral, PublicKeyToken=b4a0369545f0a1be");
        CodeKeeper.Keep("MessagePack.Formatters.NullableFormatter`1[[ActualChat.ChatKind, ActualChat.Api, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null]], MessagePack, Version=3.1.4.0, Culture=neutral, PublicKeyToken=b4a0369545f0a1be");
        CodeKeeper.Keep("MessagePack.Formatters.NullableFormatter`1[[ActualLab.Text.Symbol, ActualLab.Core, Version=12.3.25.16053, Culture=neutral, PublicKeyToken=7c239217ec78b545]], MessagePack, Version=3.1.4.0, Culture=neutral, PublicKeyToken=b4a0369545f0a1be");
        CodeKeeper.Keep("MessagePack.Formatters.NullableFormatter`1[[ActualLab.Time.Moment, ActualLab.Core, Version=12.3.25.16053, Culture=neutral, PublicKeyToken=7c239217ec78b545]], MessagePack, Version=3.1.4.0, Culture=neutral, PublicKeyToken=b4a0369545f0a1be");
        CodeKeeper.Keep("MessagePack.Formatters.NullableInt64Formatter, MessagePack, Version=3.1.4.0, Culture=neutral, PublicKeyToken=b4a0369545f0a1be");
        CodeKeeper.Keep("MessagePack.Formatters.NullableSingleFormatter, MessagePack, Version=3.1.4.0, Culture=neutral, PublicKeyToken=b4a0369545f0a1be");
        CodeKeeper.Keep("MessagePack.GeneratedMessagePackResolver+ActualChat+Chat+AliasKindFormatter, ActualChat.Api.Contracts, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.GeneratedMessagePackResolver+ActualChat+Chat+AliasTargetFormatter, ActualChat.Api.Contracts, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.GeneratedMessagePackResolver+ActualChat+Chat+Authors_ExcludeFormatter, ActualChat.Api.Contracts, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.GeneratedMessagePackResolver+ActualChat+Chat+Authors_InviteFormatter, ActualChat.Api.Contracts, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.GeneratedMessagePackResolver+ActualChat+Chat+Authors_JoinFormatter, ActualChat.Api.Contracts, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.GeneratedMessagePackResolver+ActualChat+Chat+Authors_LeaveFormatter, ActualChat.Api.Contracts, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.GeneratedMessagePackResolver+ActualChat+Chat+Authors_PromoteToOwnerFormatter, ActualChat.Api.Contracts, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.GeneratedMessagePackResolver+ActualChat+Chat+Authors_RestoreFormatter, ActualChat.Api.Contracts, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.GeneratedMessagePackResolver+ActualChat+Chat+Authors_SetAvatarFormatter, ActualChat.Api.Contracts, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.GeneratedMessagePackResolver+ActualChat+Chat+ChatThreads_StartFormatter, ActualChat.Api.Contracts, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.GeneratedMessagePackResolver+ActualChat+Chat+ChatThreads_ToggleThreadFollowStatusFormatter, ActualChat.Api.Contracts, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.GeneratedMessagePackResolver+ActualChat+Chat+Chat_CopyChatFormatter, ActualChat.Api.Contracts, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.GeneratedMessagePackResolver+ActualChat+Chat+Chat_CopyChatResultFormatter, ActualChat.Api.Contracts, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.GeneratedMessagePackResolver+ActualChat+Chat+Chat_PublishCopiedChatFormatter, ActualChat.Api.Contracts, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.GeneratedMessagePackResolver+ActualChat+Chat+Chats_ChangeFormatter, ActualChat.Api.Contracts, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.GeneratedMessagePackResolver+ActualChat+Chat+Chats_ForwardEntriesFormatter, ActualChat.Api.Contracts, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.GeneratedMessagePackResolver+ActualChat+Chat+Chats_GetOrCreateFromTemplateFormatter, ActualChat.Api.Contracts, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.GeneratedMessagePackResolver+ActualChat+Chat+Chats_RemoveEntriesFormatter, ActualChat.Api.Contracts, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.GeneratedMessagePackResolver+ActualChat+Chat+Chats_RemoveEntryFormatter, ActualChat.Api.Contracts, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.GeneratedMessagePackResolver+ActualChat+Chat+Chats_RestoreEntriesFormatter, ActualChat.Api.Contracts, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.GeneratedMessagePackResolver+ActualChat+Chat+Chats_RestoreEntryFormatter, ActualChat.Api.Contracts, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.GeneratedMessagePackResolver+ActualChat+Chat+Chats_UpsertEntryFormatter, ActualChat.Api.Contracts, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.GeneratedMessagePackResolver+ActualChat+Chat+Chats_UpsertTextEntryFormatter, ActualChat.Api.Contracts, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.GeneratedMessagePackResolver+ActualChat+Chat+Conversations_SummarizeFormatter, ActualChat.Api.Contracts, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.GeneratedMessagePackResolver+ActualChat+Chat+MeshDiagInfoFormatter, ActualChat.Api.Contracts, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.GeneratedMessagePackResolver+ActualChat+Chat+MeshRpcPeerRefDiagInfoFormatter, ActualChat.Api.Contracts, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.GeneratedMessagePackResolver+ActualChat+Chat+NodeDiagInfoFormatter, ActualChat.Api.Contracts, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.GeneratedMessagePackResolver+ActualChat+Chat+Places_ChangeFormatter, ActualChat.Api.Contracts, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.GeneratedMessagePackResolver+ActualChat+Chat+Places_ExcludeFormatter, ActualChat.Api.Contracts, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.GeneratedMessagePackResolver+ActualChat+Chat+Places_InviteFormatter, ActualChat.Api.Contracts, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.GeneratedMessagePackResolver+ActualChat+Chat+Places_JoinFormatter, ActualChat.Api.Contracts, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.GeneratedMessagePackResolver+ActualChat+Chat+Places_LeaveFormatter, ActualChat.Api.Contracts, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.GeneratedMessagePackResolver+ActualChat+Chat+Places_PromoteToOwnerFormatter, ActualChat.Api.Contracts, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.GeneratedMessagePackResolver+ActualChat+Chat+Places_RestoreFormatter, ActualChat.Api.Contracts, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.GeneratedMessagePackResolver+ActualChat+Chat+Reactions_ReactFormatter, ActualChat.Api.Contracts, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.GeneratedMessagePackResolver+ActualChat+Chat+Roles_ChangeFormatter, ActualChat.Api.Contracts, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.GeneratedMessagePackResolver+ActualChat+Chat+RpcPeerDiagInfoFormatter, ActualChat.Api.Contracts, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.GeneratedMessagePackResolver+ActualChat+Chat+ThreadStatFormatter, ActualChat.Api.Contracts, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.GeneratedMessagePackResolver+ActualChat+Contacts+Contacts_ChangeFormatter, ActualChat.Api.Contracts, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.GeneratedMessagePackResolver+ActualChat+Contacts+Contacts_TouchFormatter, ActualChat.Api.Contracts, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.GeneratedMessagePackResolver+ActualChat+Contacts+ExternalContactChangeFormatter, ActualChat.Api.Contracts, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.GeneratedMessagePackResolver+ActualChat+Contacts+ExternalContactHashes_ChangeFormatter, ActualChat.Api.Contracts, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.GeneratedMessagePackResolver+ActualChat+Contacts+ExternalContacts_BulkChangeFormatter, ActualChat.Api.Contracts, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.GeneratedMessagePackResolver+ActualChat+Invite+Invites_GenerateFormatter, ActualChat.Api.Contracts, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.GeneratedMessagePackResolver+ActualChat+Invite+Invites_RevokeFormatter, ActualChat.Api.Contracts, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.GeneratedMessagePackResolver+ActualChat+Invite+Invites_UseFormatter, ActualChat.Api.Contracts, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.GeneratedMessagePackResolver+ActualChat+Media+GifItemFormatter, ActualChat.Api.Contracts, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.GeneratedMessagePackResolver+ActualChat+Media+GifSearchResultFormatter, ActualChat.Api.Contracts, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.GeneratedMessagePackResolver+ActualChat+Media+Media_ProcessUploadFormatter, ActualChat.Api.Contracts, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.GeneratedMessagePackResolver+ActualChat+Media+Media_RemoveMediaFormatter, ActualChat.Api.Contracts, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.GeneratedMessagePackResolver+ActualChat+Media+Media_ReserveMediaFormatter, ActualChat.Api.Contracts, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.GeneratedMessagePackResolver+ActualChat+Media+Media_UpdateProgressFormatter, ActualChat.Api.Contracts, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.GeneratedMessagePackResolver+ActualChat+Media+Uploads_AppendFormatter, ActualChat.Api.Contracts, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.GeneratedMessagePackResolver+ActualChat+Media+Uploads_ConvertToMediaRefFormatter, ActualChat.Api.Contracts, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.GeneratedMessagePackResolver+ActualChat+Media+Uploads_CreateFormatter, ActualChat.Api.Contracts, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.GeneratedMessagePackResolver+ActualChat+Media+Uploads_RemoveFormatter, ActualChat.Api.Contracts, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.GeneratedMessagePackResolver+ActualChat+Media+Uploads_StartProcessUploadFormatter, ActualChat.Api.Contracts, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.GeneratedMessagePackResolver+ActualChat+Notification+Notifications_DeregisterDeviceFormatter, ActualChat.Api.Contracts, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.GeneratedMessagePackResolver+ActualChat+Notification+Notifications_HandleFormatter, ActualChat.Api.Contracts, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.GeneratedMessagePackResolver+ActualChat+Notification+Notifications_NotifyMembersFormatter, ActualChat.Api.Contracts, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.GeneratedMessagePackResolver+ActualChat+Notification+Notifications_NotifyMentionedMembersFormatter, ActualChat.Api.Contracts, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.GeneratedMessagePackResolver+ActualChat+Notification+Notifications_RegisterDeviceFormatter, ActualChat.Api.Contracts, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.GeneratedMessagePackResolver+ActualChat+Users+Accounts_CreateApiKeyFormatter, ActualChat.Api.Contracts, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.GeneratedMessagePackResolver+ActualChat+Users+Accounts_DeactivateAllSessionsFormatter, ActualChat.Api.Contracts, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.GeneratedMessagePackResolver+ActualChat+Users+Accounts_DeactivateSessionFormatter, ActualChat.Api.Contracts, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.GeneratedMessagePackResolver+ActualChat+Users+Accounts_DeleteOwnFormatter, ActualChat.Api.Contracts, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.GeneratedMessagePackResolver+ActualChat+Users+Accounts_SignOutFormatter, ActualChat.Api.Contracts, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.GeneratedMessagePackResolver+ActualChat+Users+Accounts_UpdateFormatter, ActualChat.Api.Contracts, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.GeneratedMessagePackResolver+ActualChat+Users+Avatars_ChangeFormatter, ActualChat.Api.Contracts, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.GeneratedMessagePackResolver+ActualChat+Users+Avatars_SetDefaultFormatter, ActualChat.Api.Contracts, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.GeneratedMessagePackResolver+ActualChat+Users+ChatPositions_SetFormatter, ActualChat.Api.Contracts, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.GeneratedMessagePackResolver+ActualChat+Users+ChatUsages_RegisterUsageFormatter, ActualChat.Api.Contracts, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.GeneratedMessagePackResolver+ActualChat+Users+EmailAuth_SendTotpFormatter, ActualChat.Api.Contracts, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.GeneratedMessagePackResolver+ActualChat+Users+EmailAuth_ValidateTotpFormatter, ActualChat.Api.Contracts, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.GeneratedMessagePackResolver+ActualChat+Users+EmailAuth_VerifyEmailFormatter, ActualChat.Api.Contracts, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.GeneratedMessagePackResolver+ActualChat+Users+Emails_SendDigestFormatter, ActualChat.Api.Contracts, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.GeneratedMessagePackResolver+ActualChat+Users+PhoneAuth_SendTotpFormatter, ActualChat.Api.Contracts, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.GeneratedMessagePackResolver+ActualChat+Users+PhoneAuth_ValidateTotpFormatter, ActualChat.Api.Contracts, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.GeneratedMessagePackResolver+ActualChat+Users+PhoneAuth_VerifyPhoneFormatter, ActualChat.Api.Contracts, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.GeneratedMessagePackResolver+ActualChat+Users+RecaptchaValidationResultFormatter, ActualChat.Api.Contracts, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.GeneratedMessagePackResolver+ActualChat+Users+ServerApiInfoFormatter, ActualChat.Api.Contracts, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.GeneratedMessagePackResolver+ActualChat+Users+SessionTemporals_SetFormatter, ActualChat.Api.Contracts, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.GeneratedMessagePackResolver+ActualChat+Users+SystemProperties_InvalidateEverythingFormatter, ActualChat.Api.Contracts, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.GeneratedMessagePackResolver+ActualChat+Users+SystemProperties_PruneComputedGraphFormatter, ActualChat.Api.Contracts, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.GeneratedMessagePackResolver+ActualChat+Users+UserPresences_CheckInFormatter, ActualChat.Api.Contracts, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null");
        CodeKeeper.Keep("MessagePack.GeneratedMessagePackResolver+ActualLab+Collections+Internal+PropertyBagItemFormatter, ActualLab.Core, Version=12.3.25.16053, Culture=neutral, PublicKeyToken=7c239217ec78b545");
        CodeKeeper.Keep("MessagePack.GeneratedMessagePackResolver+ActualLab+Collections+PropertyBagFormatter, ActualLab.Core, Version=12.3.25.16053, Culture=neutral, PublicKeyToken=7c239217ec78b545");
        CodeKeeper.Keep("MessagePack.GeneratedMessagePackResolver+ActualLab+Serialization+TypeDecoratingUniSerializedFormatter`1[[System.Object, System.Private.CoreLib, Version=10.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], ActualLab.Core, Version=12.3.25.16053, Culture=neutral, PublicKeyToken=7c239217ec78b545");
    }

    public (Type, AotTypeKind)[] ListTypes()
        => [
            (typeof(global::ActualChat.Chat.IAliases), AotTypeKind.Api),
            (typeof(global::ActualChat.Chat.IAuthors), AotTypeKind.Api),
            (typeof(global::ActualChat.Chat.IChatThreads), AotTypeKind.Api),
            (typeof(global::ActualChat.Chat.IChats), AotTypeKind.Api),
            (typeof(global::ActualChat.Chat.IConversations), AotTypeKind.Api),
            (typeof(global::ActualChat.Chat.IDiagnostics), AotTypeKind.Api),
            (typeof(global::ActualChat.Chat.ILegacyChats), AotTypeKind.Api),
            (typeof(global::ActualChat.Chat.IMentions), AotTypeKind.Api),
            (typeof(global::ActualChat.Chat.IPlaces), AotTypeKind.Api),
            (typeof(global::ActualChat.Chat.IReactions), AotTypeKind.Api),
            (typeof(global::ActualChat.Chat.IRoles), AotTypeKind.Api),
            (typeof(global::ActualChat.Chat.ITranslations), AotTypeKind.Api),
            (typeof(global::ActualChat.Contacts.IContacts), AotTypeKind.Api),
            (typeof(global::ActualChat.Contacts.IExternalContactHashes), AotTypeKind.Api),
            (typeof(global::ActualChat.Contacts.IExternalContacts), AotTypeKind.Api),
            (typeof(global::ActualChat.Invite.IInvites), AotTypeKind.Api),
            (typeof(global::ActualChat.Media.IMedia), AotTypeKind.Api),
            (typeof(global::ActualChat.Media.IMediaLinkPreviews), AotTypeKind.Api),
            (typeof(global::ActualChat.Media.IUploads), AotTypeKind.Api),
            (typeof(global::ActualChat.Notification.INotifications), AotTypeKind.Api),
            (typeof(global::ActualChat.Search.ISearch), AotTypeKind.Api),
            (typeof(global::ActualChat.Streaming.ILiveAudioStreams), AotTypeKind.Api),
            (typeof(global::ActualChat.Streaming.ILiveVideoStreams), AotTypeKind.Api),
            (typeof(global::ActualChat.Users.IAccounts), AotTypeKind.Api),
            (typeof(global::ActualChat.Users.IAvatars), AotTypeKind.Api),
            (typeof(global::ActualChat.Users.IChatPositions), AotTypeKind.Api),
            (typeof(global::ActualChat.Users.IChatUsages), AotTypeKind.Api),
            (typeof(global::ActualChat.Users.IEmailAuth), AotTypeKind.Api),
            (typeof(global::ActualChat.Users.IEmails), AotTypeKind.Api),
            (typeof(global::ActualChat.Users.IMobileSessions), AotTypeKind.Api),
            (typeof(global::ActualChat.Users.IPhoneAuth), AotTypeKind.Api),
            (typeof(global::ActualChat.Users.IPhones), AotTypeKind.Api),
            (typeof(global::ActualChat.Users.ISessionTemporals), AotTypeKind.Api),
            (typeof(global::ActualChat.Users.ISystemProperties), AotTypeKind.Api),
            (typeof(global::ActualChat.Users.ITimeZones), AotTypeKind.Api),
            (typeof(global::ActualChat.Users.IUserPresences), AotTypeKind.Api),
            (typeof(global::ActualChat.Chat.AliasTarget), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Chat.Authors_Exclude), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Chat.Authors_Invite), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Chat.Authors_Join), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Chat.Authors_Leave), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Chat.Authors_PromoteToOwner), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Chat.Authors_Restore), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Chat.Authors_SetAvatar), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Chat.ChatThreads_Start), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Chat.ChatThreads_ToggleThreadFollowStatus), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Chat.Chat_CopyChat), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Chat.Chat_CopyChatResult), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Chat.Chat_PublishCopiedChat), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Chat.Chats_Change), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Chat.Chats_ForwardEntries), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Chat.Chats_GetOrCreateFromTemplate), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Chat.Chats_RemoveEntries), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Chat.Chats_RemoveEntry), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Chat.Chats_RestoreEntries), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Chat.Chats_RestoreEntry), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Chat.Chats_UpsertEntry), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Chat.Chats_UpsertTextEntry), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Chat.Conversations_Summarize), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Chat.MeshDiagInfo), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Chat.MeshRpcPeerRefDiagInfo), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Chat.NodeDiagInfo), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Chat.Places_Change), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Chat.Places_Exclude), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Chat.Places_Invite), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Chat.Places_Join), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Chat.Places_Leave), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Chat.Places_PromoteToOwner), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Chat.Places_Restore), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Chat.Reactions_React), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Chat.Roles_Change), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Chat.RpcPeerDiagInfo), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Chat.ThreadStat), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Contacts.Contacts_Change), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Contacts.Contacts_Touch), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Contacts.ExternalContactChange), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Contacts.ExternalContactHashes_Change), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Contacts.ExternalContacts_BulkChange), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Invite.Invites_Generate), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Invite.Invites_Revoke), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Invite.Invites_Use), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Media.GifItem), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Media.GifSearchResult), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Media.Media_ProcessUpload), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Media.Media_RemoveMedia), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Media.Media_ReserveMedia), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Media.Media_UpdateProgress), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Media.Uploads_Append), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Media.Uploads_ConvertToMediaRef), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Media.Uploads_Create), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Media.Uploads_Remove), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Media.Uploads_StartProcessUpload), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Notification.Notifications_DeregisterDevice), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Notification.Notifications_Handle), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Notification.Notifications_NotifyMembers), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Notification.Notifications_NotifyMentionedMembers), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Notification.Notifications_RegisterDevice), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Users.Accounts_CreateApiKey), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Users.Accounts_DeactivateAllSessions), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Users.Accounts_DeactivateSession), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Users.Accounts_DeleteOwn), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Users.Accounts_SignOut), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Users.Accounts_Update), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Users.Avatars_Change), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Users.Avatars_SetDefault), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Users.ChatPositions_Set), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Users.ChatUsages_RegisterUsage), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Users.EmailAuth_SendTotp), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Users.EmailAuth_ValidateTotp), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Users.EmailAuth_VerifyEmail), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Users.Emails_SendDigest), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Users.PhoneAuth_SendTotp), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Users.PhoneAuth_ValidateTotp), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Users.PhoneAuth_VerifyPhone), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Users.RecaptchaValidationResult), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Users.ServerApiInfo), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Users.SessionTemporals_Set), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Users.SystemProperties_InvalidateEverything), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Users.SystemProperties_PruneComputedGraph), AotTypeKind.Serializable),
            (typeof(global::ActualChat.Users.UserPresences_CheckIn), AotTypeKind.Serializable),
        ];
}
