// <auto-generated />
using ActualChat.Contacts.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

#nullable disable

namespace ActualChat.Contacts.Migrations
{
    [DbContext(typeof(ContactsDbContext))]
    partial class ContactsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ActualChat.Contacts.Db.DbContact", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id")
                        .UseCollation("C");

                    b.Property<string>("ChatId")
                        .HasColumnType("text")
                        .HasColumnName("chat_id")
                        .UseCollation("C");

                    b.Property<string>("ExternalContactName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("external_contact_name");

                    b.Property<bool>("IsPinned")
                        .HasColumnType("boolean")
                        .HasColumnName("is_pinned");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("owner_id")
                        .UseCollation("C");

                    b.Property<string>("PeerContactName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("peer_contact_name");

                    b.Property<string>("PlaceId")
                        .HasColumnType("text")
                        .HasColumnName("place_id")
                        .UseCollation("C");

                    b.Property<int>("State")
                        .HasColumnType("integer")
                        .HasColumnName("state");

                    b.Property<DateTime>("TouchedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("touched_at");

                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id")
                        .UseCollation("C");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_contacts");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_contacts_owner_id");

                    b.HasIndex("Version", "Id")
                        .HasDatabaseName("ix_contacts_version_id")
                        .HasFilter("user_id IS NOT NULL");

                    b.ToTable("contacts");
                });

            modelBuilder.Entity("ActualChat.Contacts.Db.DbExternalContact", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id")
                        .UseCollation("C");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("FamilyName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("family_name");

                    b.Property<string>("GivenName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("given_name");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hash");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("middle_name");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("NamePrefix")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name_prefix");

                    b.Property<string>("NameSuffix")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name_suffix");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_external_contacts");

                    b.ToTable("external_contacts");
                });

            modelBuilder.Entity("ActualChat.Contacts.Db.DbExternalContactLink", b =>
                {
                    b.Property<string>("DbExternalContactId")
                        .HasColumnType("text")
                        .HasColumnName("external_contact_id")
                        .UseCollation("C");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.Property<bool>("IsChecked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_checked");

                    b.HasKey("DbExternalContactId", "Value")
                        .HasName("pk_external_contact_links");

                    b.HasIndex("IsChecked")
                        .HasDatabaseName("ix_external_contact_links_is_checked");

                    b.HasIndex("Value")
                        .HasDatabaseName("ix_external_contact_links_value");

                    b.ToTable("external_contact_links");
                });

            modelBuilder.Entity("ActualChat.Contacts.Db.DbExternalContactsHash", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id")
                        .UseCollation("C");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hash");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_external_contacts_hashes");

                    b.ToTable("external_contacts_hashes");
                });

            modelBuilder.Entity("ActualChat.Contacts.Db.DbPlaceContact", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id")
                        .UseCollation("C");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("owner_id")
                        .UseCollation("C");

                    b.Property<string>("PlaceId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("place_id")
                        .UseCollation("C");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_place_contacts");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_place_contacts_owner_id");

                    b.HasIndex("Version", "Id")
                        .HasDatabaseName("ix_place_contacts_version_id");

                    b.ToTable("place_contacts");
                });

            modelBuilder.Entity("ActualChat.Contacts.Db.DbThreadContact", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id")
                        .UseCollation("C");

                    b.Property<bool>("IsPinned")
                        .HasColumnType("boolean")
                        .HasColumnName("is_pinned");

                    b.Property<string>("OutermostParentChatId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("outermost_parent_chat_id")
                        .UseCollation("C");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("owner_id")
                        .UseCollation("C");

                    b.Property<string>("ParentChatId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("parent_chat_id")
                        .UseCollation("C");

                    b.Property<string>("PlaceId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("place_id")
                        .UseCollation("C");

                    b.Property<string>("ThreadChatId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("thread_chat_id")
                        .UseCollation("C");

                    b.Property<DateTime>("TouchedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("touched_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_thread_contacts");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_thread_contacts_owner_id");

                    b.ToTable("thread_contacts");
                });

            modelBuilder.Entity("ActualLab.Fusion.EntityFramework.Operations.DbEvent", b =>
                {
                    b.Property<string>("Uuid")
                        .HasColumnType("text")
                        .HasColumnName("uuid")
                        .UseCollation("C");

                    b.Property<DateTime>("DelayUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delay_until");

                    b.Property<DateTime>("LoggedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("logged_at");

                    b.Property<int>("State")
                        .HasColumnType("integer")
                        .HasColumnName("state");

                    b.Property<string>("ValueJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value_json");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Uuid")
                        .HasName("pk_events");

                    b.HasIndex("DelayUntil")
                        .HasDatabaseName("ix_events_pending")
                        .HasFilter("state = 0");

                    b.HasIndex("DelayUntil", "State")
                        .HasDatabaseName("ix_events_delay_until_state_non_new")
                        .HasFilter("state != 0");

                    b.ToTable("_events");
                });

            modelBuilder.Entity("ActualLab.Fusion.EntityFramework.Operations.DbOperation", b =>
                {
                    b.Property<long>("Index")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("index");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Index"));

                    b.Property<string>("CommandJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("command_json");

                    b.Property<string>("HostId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("host_id")
                        .UseCollation("C");

                    b.Property<string>("ItemsJson")
                        .HasColumnType("text")
                        .HasColumnName("items_json");

                    b.Property<DateTime>("LoggedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("logged_at");

                    b.Property<string>("NestedOperations")
                        .HasColumnType("text")
                        .HasColumnName("nested_operations");

                    b.Property<string>("Uuid")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("uuid")
                        .UseCollation("C");

                    b.HasKey("Index")
                        .HasName("pk_operations");

                    b.HasIndex("LoggedAt")
                        .HasDatabaseName("ix_operations_logged_at");

                    b.HasIndex("Uuid")
                        .IsUnique()
                        .HasDatabaseName("ix_operations_uuid");

                    b.ToTable("_operations");
                });

            modelBuilder.Entity("ActualChat.Contacts.Db.DbExternalContactLink", b =>
                {
                    b.HasOne("ActualChat.Contacts.Db.DbExternalContact", null)
                        .WithMany("ExternalContactLinks")
                        .HasForeignKey("DbExternalContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_external_contact_links_external_contacts_external_contact_id");
                });

            modelBuilder.Entity("ActualChat.Contacts.Db.DbExternalContact", b =>
                {
                    b.Navigation("ExternalContactLinks");
                });
#pragma warning restore 612, 618
        }
    }
}
