<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\src\dotnet\Notifications.Service\Notifications.Service.csproj" />
    <ProjectReference Include="..\Testing.Host\Testing.Host.csproj" />
    <ProjectReference Include="..\Testing\Testing.csproj" />
  </ItemGroup>
                                                                                 
</Project>
