<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Chat.ML\Chat.ML.csproj" />
    <ProjectReference Include="..\Db\Db.csproj" />
    <ProjectReference Include="..\Chat.Contracts\Chat.Contracts.csproj" />
    <ProjectReference Include="..\Contacts.Contracts\Contacts.Contracts.csproj" />
    <ProjectReference Include="..\Invite.Contracts\Invite.Contracts.csproj" />
    <ProjectReference Include="..\Media.Contracts\Media.Contracts.csproj" />
    <ProjectReference Include="..\Notification.Contracts\Notification.Contracts.csproj" />
    <ProjectReference Include="..\Streaming.Contracts\Streaming.Contracts.csproj" />
    <ProjectReference Include="..\Users.Contracts\Users.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None
      Include="$(MSBuildThisFileDirectory)..\..\..\tests\Streaming.IntegrationTests\data\**"
      Link="data\%(RecursiveDir)%(Filename)%(Extension)"
      Visible="false"
      CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.SemanticKernel" />
    <PackageReference Include="Microsoft.SemanticKernel.Agents.Abstractions" />
    <PackageReference Include="Microsoft.SemanticKernel.Agents.Core" />
    <PackageReference Include="Microsoft.SemanticKernel.Connectors.Google" />
  </ItemGroup>

</Project>
