<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Api.Contracts\Api.Contracts.csproj" />
    <ProjectReference Include="..\Streaming.Contracts\Streaming.Contracts.csproj" />
  </ItemGroup>

</Project>
