<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>true</IsPackable>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Api\Api.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ActualLab.RestEase" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="RestEase.SourceGenerator" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="$(RootNamespace).Core.UnitTests$(AssemblyPublicKey)" />
  </ItemGroup>

</Project>
