<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Testing.Host\Testing.Host.csproj" />
    <ProjectReference Include="..\..\src\dotnet\Mcp\Mcp.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ModelContextProtocol" />
  </ItemGroup>

</Project>
