// <auto-generated />
using ActualChat.Mjml.Blazor.Enums;
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Components.Rendering;

namespace ActualChat.Mjml.Blazor.Components;

public class MjmlAccordion : ComponentBase
{
    [Parameter] public string? Border { get; set; }
    [Parameter] public string? ContainerBackgroundColor { get; set; }
    [Parameter] public string? CssClass { get; set; }
    [Parameter] public string? FontFamily { get; set; }
    [Parameter] public MjmlAccordionIconAlign? IconAlign { get; set; }
    [Parameter] public string? IconHeight { get; set; }
    [Parameter] public MjmlAccordionIconPosition? IconPosition { get; set; }
    [Parameter] public string? IconUnwrappedAlt { get; set; }
    [Parameter] public string? IconUnwrappedUrl { get; set; }
    [Parameter] public string? IconWidth { get; set; }
    [Parameter] public string? IconWrappedAlt { get; set; }
    [Parameter] public string? IconWrappedUrl { get; set; }
    [Parameter] public string? MjmlClass { get; set; }
    [Parameter] public string? Padding { get; set; }
    [Parameter] public string? PaddingBottom { get; set; }
    [Parameter] public string? PaddingLeft { get; set; }
    [Parameter] public string? PaddingRight { get; set; }
    [Parameter] public string? PaddingTop { get; set; }
    [Parameter] public RenderFragment? ChildContent { get; set; }

    protected override void BuildRenderTree(RenderTreeBuilder builder)
    {
        builder.OpenElement(0, "mj-accordion");
        if (Border is not null)
            builder.AddAttribute(1, "border", Border);
        if (ContainerBackgroundColor is not null)
            builder.AddAttribute(2, "container-background-color", ContainerBackgroundColor);
        if (CssClass is not null)
            builder.AddAttribute(3, "css-class", CssClass);
        if (FontFamily is not null)
            builder.AddAttribute(4, "font-family", FontFamily);
        if (IconAlign is not null)
            builder.AddAttribute(5, "icon-align", IconAlign.Value.ToMjmlValue());
        if (IconHeight is not null)
            builder.AddAttribute(6, "icon-height", IconHeight);
        if (IconPosition is not null)
            builder.AddAttribute(7, "icon-position", IconPosition.Value.ToMjmlValue());
        if (IconUnwrappedAlt is not null)
            builder.AddAttribute(8, "icon-unwrapped-alt", IconUnwrappedAlt);
        if (IconUnwrappedUrl is not null)
            builder.AddAttribute(9, "icon-unwrapped-url", IconUnwrappedUrl);
        if (IconWidth is not null)
            builder.AddAttribute(10, "icon-width", IconWidth);
        if (IconWrappedAlt is not null)
            builder.AddAttribute(11, "icon-wrapped-alt", IconWrappedAlt);
        if (IconWrappedUrl is not null)
            builder.AddAttribute(12, "icon-wrapped-url", IconWrappedUrl);
        if (MjmlClass is not null)
            builder.AddAttribute(13, "mj-class", MjmlClass);
        if (Padding is not null)
            builder.AddAttribute(14, "padding", Padding);
        if (PaddingBottom is not null)
            builder.AddAttribute(15, "padding-bottom", PaddingBottom);
        if (PaddingLeft is not null)
            builder.AddAttribute(16, "padding-left", PaddingLeft);
        if (PaddingRight is not null)
            builder.AddAttribute(17, "padding-right", PaddingRight);
        if (PaddingTop is not null)
            builder.AddAttribute(18, "padding-top", PaddingTop);
        if (ChildContent is not null)
            builder.AddContent(19, ChildContent);
        builder.CloseElement();
    }
}
