// <auto-generated />
using ActualChat.Mjml.Blazor.Enums;
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Components.Rendering;

namespace ActualChat.Mjml.Blazor.Components;

public class MjmlText : ComponentBase
{
    [Parameter] public MjmlTextAlign? Align { get; set; }
    [Parameter] public string? BackgroundColor { get; set; }
    [Parameter] public string? Color { get; set; }
    [Parameter] public string? ContainerBackgroundColor { get; set; }
    [Parameter] public string? CssClass { get; set; }
    [Parameter] public string? FontFamily { get; set; }
    [Parameter] public string? FontSize { get; set; }
    [Parameter] public string? FontStyle { get; set; }
    [Parameter] public string? FontWeight { get; set; }
    [Parameter] public string? Height { get; set; }
    [Parameter] public string? LetterSpacing { get; set; }
    [Parameter] public string? LineHeight { get; set; }
    [Parameter] public string? MjmlClass { get; set; }
    [Parameter] public string? Padding { get; set; }
    [Parameter] public string? PaddingBottom { get; set; }
    [Parameter] public string? PaddingLeft { get; set; }
    [Parameter] public string? PaddingRight { get; set; }
    [Parameter] public string? PaddingTop { get; set; }
    [Parameter] public string? TextDecoration { get; set; }
    [Parameter] public string? TextTransform { get; set; }
    [Parameter] public MjmlTextVerticalAlign? VerticalAlign { get; set; }
    [Parameter] public RenderFragment? ChildContent { get; set; }

    protected override void BuildRenderTree(RenderTreeBuilder builder)
    {
        builder.OpenElement(0, "mj-text");
        if (Align is not null)
            builder.AddAttribute(1, "align", Align.Value.ToMjmlValue());
        if (BackgroundColor is not null)
            builder.AddAttribute(2, "background-color", BackgroundColor);
        if (Color is not null)
            builder.AddAttribute(3, "color", Color);
        if (ContainerBackgroundColor is not null)
            builder.AddAttribute(4, "container-background-color", ContainerBackgroundColor);
        if (CssClass is not null)
            builder.AddAttribute(5, "css-class", CssClass);
        if (FontFamily is not null)
            builder.AddAttribute(6, "font-family", FontFamily);
        if (FontSize is not null)
            builder.AddAttribute(7, "font-size", FontSize);
        if (FontStyle is not null)
            builder.AddAttribute(8, "font-style", FontStyle);
        if (FontWeight is not null)
            builder.AddAttribute(9, "font-weight", FontWeight);
        if (Height is not null)
            builder.AddAttribute(10, "height", Height);
        if (LetterSpacing is not null)
            builder.AddAttribute(11, "letter-spacing", LetterSpacing);
        if (LineHeight is not null)
            builder.AddAttribute(12, "line-height", LineHeight);
        if (MjmlClass is not null)
            builder.AddAttribute(13, "mj-class", MjmlClass);
        if (Padding is not null)
            builder.AddAttribute(14, "padding", Padding);
        if (PaddingBottom is not null)
            builder.AddAttribute(15, "padding-bottom", PaddingBottom);
        if (PaddingLeft is not null)
            builder.AddAttribute(16, "padding-left", PaddingLeft);
        if (PaddingRight is not null)
            builder.AddAttribute(17, "padding-right", PaddingRight);
        if (PaddingTop is not null)
            builder.AddAttribute(18, "padding-top", PaddingTop);
        if (TextDecoration is not null)
            builder.AddAttribute(19, "text-decoration", TextDecoration);
        if (TextTransform is not null)
            builder.AddAttribute(20, "text-transform", TextTransform);
        if (VerticalAlign is not null)
            builder.AddAttribute(21, "vertical-align", VerticalAlign.Value.ToMjmlValue());
        if (ChildContent is not null)
            builder.AddContent(22, ChildContent);
        builder.CloseElement();
    }
}
