// <auto-generated />
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Components.Rendering;

namespace ActualChat.Mjml.Blazor.Components;

public class MjmlSelector : ComponentBase
{
    [Parameter] public string? Path { get; set; }
    [Parameter] public RenderFragment? ChildContent { get; set; }

    protected override void BuildRenderTree(RenderTreeBuilder builder)
    {
        builder.OpenElement(0, "mj-selector");
        if (Path is not null)
            builder.AddAttribute(1, "path", Path);
        if (ChildContent is not null)
            builder.AddContent(2, ChildContent);
        builder.CloseElement();
    }
}
