<!--
Use:
- <Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly"> for regular builds
- <Project Sdk="Microsoft.NET.Sdk.Razor"> for hot reload (only in server mode)
-->
<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <!-- Publish & runtime properties -->
  <PropertyGroup>
    <!-- Required for WASM+Server projects -->
    <StaticWebAssetProjectMode>Default</StaticWebAssetProjectMode>
    <!-- These settings allows to build dotnet.js w/ symbols, but it takes like 1H or so -->
    <!--
    <RunAOTCompilation>true</RunAOTCompilation>
    <RunAOTCompilationAfterBuild>true</RunAOTCompilationAfterBuild>
    <WasmEmitSymbolMap>true</WasmEmitSymbolMap>
    <WasmNativeStrip>false</WasmNativeStrip>
    -->
    <WasmEnableWebcil>true</WasmEnableWebcil>
    <!-- Startup is 50-100ms slower when enabled: -->
    <WasmEnableSIMD>true</WasmEnableSIMD>
    <SuppressTrimAnalysisWarnings>false</SuppressTrimAnalysisWarnings>
    <NoDefaultLaunchSettingsFile>true</NoDefaultLaunchSettingsFile>
  </PropertyGroup>

  <!-- Trimming & feature switches -->
  <PropertyGroup>
    <!-- Reduces WASM size + we assume this mode is used on the client -->
    <InvariantGlobalization>true</InvariantGlobalization>
    <!-- Required with PublishTrimmed=true in our case -->
    <JsonSerializerIsReflectionEnabledByDefault>true</JsonSerializerIsReflectionEnabledByDefault>
    <!-- Slower runtime, but slightly faster startup -->
    <DisableDependencyInjectionDynamicEngine>true</DisableDependencyInjectionDynamicEngine>
  </PropertyGroup>

  <!-- WASM Profiling -->
  <!--
  <PropertyGroup>
    <WasmProfilers>browser;</WasmProfilers>
    <WasmBuildNative>true</WasmBuildNative>
  </PropertyGroup>
  -->

  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <PublishTrimmed>true</PublishTrimmed>
    <TrimMode>full</TrimMode>
    <!-- <TrimMode Condition="$(UseAppPack)">full</TrimMode>-->
    <RunAOTCompilation>false</RunAOTCompilation>
    <WasmStripILAfterAOT>false</WasmStripILAfterAOT>
    <CompressionEnabled>true</CompressionEnabled>
  </PropertyGroup>

  <!-- Trimming -->
  <ItemGroup>
    <!-- <TrimmerRootDescriptor Include="ILLink.Descriptors.xml" />-->
    <TrimmerRootAssembly Include="ActualChat.App.Wasm" RootMode="EntryPoint" />
    <TrimmerRootAssembly Include="ActualChat.Api" RootMode="All" />
    <TrimmerRootAssembly Include="ActualChat.Api.Contracts" RootMode="All" />
    <TrimmerRootAssembly Include="ActualChat.UI.Blazor" RootMode="All" />
    <TrimmerRootAssembly Include="ActualChat.UI.Blazor.App" RootMode="All" />
    <TrimmerRootAssembly Include="ActualChat.UI.Blazor.AppPack" RootMode="All" />
  </ItemGroup>

  <!-- References -->
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" PrivateAssets="all" />
    <!-- Workaround of https://github.com/dotnet/aspnetcore/issues/37141>: -->
    <ProjectCapability Include="AspNetCore" />
  </ItemGroup>

  <!-- UseAppPack == false -->
  <ItemGroup Condition="!$(UseAppPack)">
    <ProjectReference Include="..\UI.Blazor.AppPack\UI.Blazor.AppPack.csproj" />
  </ItemGroup>
  <!-- UseAppPack == true -->
  <ItemGroup Condition="$(UseAppPack)">
    <ProjectReference Include="..\UI.Blazor.AppPack\UI.Blazor.AppPack.csproj" ReferenceOutputAssembly="false" />
    <Reference Include="ActualChat.UI.Blazor.AppPack">
      <HintPath>$(AppPackDir)ActualChat.UI.Blazor.AppPack.dll</HintPath>
    </Reference>
    <!-- A few more packages should be referenced transitively in this case -->
    <PackageReference Include="CommunityToolkit.HighPerformance" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Authorization" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Protocols.MessagePack" />
    <PackageReference Include="Microsoft.Extensions.Http" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Logging" />
    <PackageReference Include="Microsoft.Extensions.Options.DataAnnotations" />
    <PackageReference Include="Microsoft.JSInterop.WebAssembly" />
    <PackageReference Include="OpenTelemetry" />
    <PackageReference Include="OpenTelemetry.Instrumentation.Http" />
    <PackageReference Include="RestEase" />
    <PackageReference Include="SauceControl.Blake2Fast" />
    <PackageReference Include="System.Linq.Async" />
    <PackageReference Include="System.Reactive" />
    <PackageReference Include="Ulid" />
    <PackageReference Include="ZString" />
  </ItemGroup>

  <ItemGroup>
    <_ContentIncludedByDefault Remove="wwwroot\dist\config\firebase.config.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\assets\wasm\codec.wasm" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\assets\wasm\ort-wasm-simd-threaded.wasm" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\assets\wasm\ort-wasm-simd.wasm" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\assets\wasm\ort-wasm-threaded.wasm" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\assets\wasm\ort-wasm.wasm" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\assets\wasm\soxr_wasm.wasm" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\assets\onnx\vad.onnx" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\assets\eot\forkawesome-webfont.eot" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\assets\eot\icon.eot" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\assets\map\codec.debug.wasm.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\assets\mjs\ort-wasm-simd.mjs" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\assets\ort\vad_batched.ort" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\assets\otf\TT-Commons-Pro-DemiBold.otf" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\assets\otf\TT-Commons-Pro-Light.otf" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\assets\otf\TT-Commons-Pro-Medium.otf" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\assets\otf\TT-Commons-Pro-Mono-Regular.otf" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\assets\otf\TT-Commons-Pro-Regular.otf" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\assets\svg\ellipses-mobile.svg" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\assets\svg\forkawesome-webfont.svg" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\assets\svg\icon.svg" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\assets\ttf\forkawesome-webfont.ttf" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\assets\ttf\icon.ttf" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\assets\ttf\TT-Commons-Pro-DemiBold.ttf" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\assets\ttf\TT-Commons-Pro-Light.ttf" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\assets\ttf\TT-Commons-Pro-Medium.ttf" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\assets\ttf\TT-Commons-Pro-Mono-Regular.ttf" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\assets\ttf\TT-Commons-Pro-Regular.ttf" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\assets\wasm\codec.debug.wasm" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\assets\wasm\resampler.wasm" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\assets\wasm\webrtc-vad.wasm" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\assets\woff2\forkawesome-webfont.woff2" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\assets\woff2\icon.woff2" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\assets\woff2\TT-Commons-Pro-DemiBold.woff2" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\assets\woff2\TT-Commons-Pro-Light.woff2" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\assets\woff2\TT-Commons-Pro-Medium.woff2" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\assets\woff2\TT-Commons-Pro-Mono-Regular.woff2" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\assets\woff2\TT-Commons-Pro-Regular.woff2" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\assets\woff\forkawesome-webfont.woff" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\assets\woff\icon.woff" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\ac-black-logo-alpha.svg" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\ac-white-logo-alpha.svg" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\add-reaction.svg" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\attachment.svg" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\bubbles\record-1.mp4" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\bubbles\record-1.webm" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\ellipses-1.svg" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\ellipses-2.svg" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\ellipses-mobile.svg" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\ellipses.svg" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\emails\ac-icon-light.png" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\emails\ac-title-light.png" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\emails\email-cat.png" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\emails\get-android.png" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\emails\get-ios.png" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\emails\github.png" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\emails\voxt-title-white.png" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\emoji-angry.svg" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\emoji-lol.svg" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\emoji-poo.svg" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\emoji-red-heart.svg" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\emoji-sad.svg" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\emoji-surprise.svg" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\emoji-thumbs-up.svg" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\error-barrier-image.svg" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\guide\android-app-01.png" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\guide\android-app-02.png" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\guide\android-app-03.png" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\guide\android-app-04.png" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\guide\android-app-05.png" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\guide\android-app-06.png" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\guide\android-chrome-01.png" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\guide\android-chrome-02.png" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\guide\android-chrome-03.png" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\guide\android-chrome-04.png" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\guide\android-chrome-05.png" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\guide\android-edge-01.png" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\guide\android-edge-02.png" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\guide\android-edge-03.png" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\guide\android-edge-04.png" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\guide\android-edge-05.png" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\guide\android-edge-06.png" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\guide\android-edge-07.png" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\guide\android-edge-08.png" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\guide\ios-app-01.png" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\guide\ios-app-02.png" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\guide\ios-app-03.png" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\guide\ios-safari-01.png" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\guide\ios-safari-02.png" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\guide\ios-safari-03.png" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\guide\mic-access.png" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\guide\web-chrome-01.png" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\guide\web-chrome-02.png" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\guide\web-chrome-03.png" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\guide\web-chrome-04.png" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\guide\web-chrome-05.png" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\guide\web-chrome-06.png" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\guide\web-chrome-07.png" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\guide\web-edge-01.png" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\guide\web-edge-02.png" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\guide\web-edge-03.png" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\guide\web-edge-04.png" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\guide\web-edge-05.png" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\guide\web-safari-01.png" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\guide\web-safari-02.png" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\guide\web-safari-02.webp" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\guide\web-safari-03.png" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\guide\web-safari-03.webp" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\guide\web-safari-04.png" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\guide\web-safari-04.webp" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\landing\ac-alpha-dark.svg" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\landing\ac-alpha-light.svg" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\landing\ac-icon-dark.svg" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\landing\ac-icon-light.svg" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\landing\ac-title-dark.svg" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\landing\ac-title-light.svg" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\landing\android-logo-white.svg" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\landing\android-phone.svg" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\landing\android.svg" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\landing\app-store-qr.svg" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\landing\app-store.svg" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\landing\apple-icon-black.svg" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\landing\apple-icon-blue.svg" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\landing\apple-logo-black.svg" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\landing\apple-logo-white.svg" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\landing\card-classmate-chats.svg" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\landing\card-customer-support.svg" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\landing\card-family-chats.svg" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\landing\card-remote-team.svg" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\landing\card-webinar.svg" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\landing\chat-body-1.svg" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\landing\checkmark-blue.svg" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\landing\checkmark-checked.svg" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\landing\checkmark-unchecked.svg" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\landing\curved-line.svg" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\landing\dialog-01.svg" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\landing\dialog-02.svg" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\landing\dialog-03.svg" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\landing\dialog-04.svg" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\landing\dialog-05.svg" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\landing\dialog-06.svg" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\landing\dialog-07.png" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\landing\dialog-08.svg" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\landing\enjoyable-01.svg" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\landing\enjoyable-02.svg" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\landing\enjoyable-03.svg" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\landing\evolution.svg" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\landing\facebook-gray.svg" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\landing\facebook-icon-blue.svg" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\landing\features-carousel-1.png" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\landing\features-carousel-2.png" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\landing\features-carousel-3.png" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\landing\features-carousel-4.png" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\landing\features-carousel-5.png" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\landing\features-carousel-6.png" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\landing\features-carousel-mobile-1.png" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\landing\features-carousel-mobile-2.png" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\landing\features-carousel-mobile-3.png" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\landing\features-carousel-mobile-4.png" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\landing\features-carousel-mobile-5.png" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\landing\features-carousel-mobile-6.png" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\landing\github-gray.svg" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\landing\google-icon-blue.svg" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\landing\google-icon-color.svg" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\landing\google-play-qr.svg" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\landing\google-play.svg" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\landing\landing-tutorial-plug.png" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\landing\landing-tutorial.mp4" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\landing\landing-tutorial.webm" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\landing\medium-gray.svg" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\landing\microsoft-store-qr.svg" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\landing\microsoft-store.svg" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\landing\person-01.svg" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\landing\person-02.svg" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\landing\person-03.svg" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\landing\person-04.svg" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\landing\premium-features-1.svg" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\landing\premium-features-2.svg" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\landing\productive.svg" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\landing\stressless.svg" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\landing\synchronous.svg" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\landing\team-friendly.svg" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\landing\telegram-gray.svg" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\landing\timeline-computer.svg" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\landing\timeline-fire.svg" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\landing\timeline-mobile.svg" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\landing\timeline-penicillin.svg" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\landing\timeline-satellite.svg" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\landing\timeline-talking.svg" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\landing\timeline-telegraph.svg" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\landing\timeline-telephone.svg" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\landing\timeline-wheel.svg" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\landing\timeline-written.svg" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\landing\voice-and-text.svg" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\landing\voxt-landing-background-ellipse.svg" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\landing\voxt-landing-background-logo.svg" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\landing\web-logo-white.svg" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\landing\windows-logo-white.svg" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\loading-spinner.svg" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\logo-white.svg" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\onboarding\alumni.svg" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\onboarding\bell.svg" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\onboarding\contacts.svg" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\onboarding\coworkers.svg" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\onboarding\family.svg" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\onboarding\friends.svg" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\onboarding\mic.svg" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\onboarding\notes.svg" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\onboarding\tutorial-1.svg" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\onboarding\tutorial-2.svg" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\onboarding\tutorial-3.svg" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\onboarding\tutorial-4.svg" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\signin-arrow.svg" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\splashscreen-voxt.svg" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\voxt-black-horizontal.svg" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\voxt-galaxy-horizontal.svg" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\voxt-galaxy-vertical.svg" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\voxt-icon-color.svg" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\voxt-icon-white.svg" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\voxt-rounded.svg" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\voxt-white-horizontal.svg" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\voxt.svg" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\webonly\elevate-conversations.mp4" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\webonly\elevate-conversations.webm" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\webonly\embrace-inclusivity.mp4" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\webonly\embrace-inclusivity.webm" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\webonly\landing-tutorial.mp4" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\webonly\landing-tutorial.webm" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\webonly\unmatched-flexibility.mp4" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\images\webonly\unmatched-flexibility.webm" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Properties\" />
    <Folder Include="wwwroot\dist" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Properties\launchSettings.json" />
  </ItemGroup>

</Project>
