<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RuntimeIdentifier>linux-x64</RuntimeIdentifier>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Chat.Service\Chat.Service.csproj" />
    <ProjectReference Include="..\Media.Service\Media.Service.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" PrivateAssets="all" />
  </ItemGroup>

</Project>
