// <auto-generated />
using System;
using ActualChat.Search.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ActualChat.Search.Migrations
{
    [DbContext(typeof(SearchDbContext))]
    [Migration("20240503071451_AddCollationToIds")]
    partial class AddCollationToIds
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ActualChat.Search.Db.DbContactIndexState", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id")
                        .UseCollation("C");

                    b.Property<string>("LastUpdatedId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_updated_id")
                        .UseCollation("C");

                    b.Property<long>("LastUpdatedVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("last_updated_version");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_contact_index_state");

                    b.ToTable("contact_index_state");
                });

            modelBuilder.Entity("ActualChat.Search.Db.DbIndexedChat", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id")
                        .UseCollation("C");

                    b.Property<DateTime>("ChatCreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("chat_created_at");

                    b.Property<long>("LastEntryLocalId")
                        .HasColumnType("bigint")
                        .HasColumnName("last_entry_local_id");

                    b.Property<long>("LastEntryVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("last_entry_version");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_indexed_chat");

                    b.HasIndex("ChatCreatedAt")
                        .HasDatabaseName("ix_indexed_chat_chat_created_at");

                    b.ToTable("indexed_chat");
                });

            modelBuilder.Entity("ActualLab.Fusion.EntityFramework.Operations.DbEvent", b =>
                {
                    b.Property<string>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("uuid")
                        .UseCollation("C");

                    b.Property<DateTime>("DelayUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delay_until");

                    b.Property<DateTime>("LoggedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("logged_at");

                    b.Property<int>("State")
                        .HasColumnType("integer")
                        .HasColumnName("state");

                    b.Property<string>("ValueJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value_json");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Uuid")
                        .HasName("pk_events");

                    b.HasIndex("DelayUntil")
                        .HasDatabaseName("ix_events_delay_until");

                    b.HasIndex("Uuid")
                        .IsUnique()
                        .HasDatabaseName("ix_events_uuid");

                    b.HasIndex("State", "DelayUntil")
                        .HasDatabaseName("ix_events_state_delay_until");

                    b.ToTable("_events");
                });

            modelBuilder.Entity("ActualLab.Fusion.EntityFramework.Operations.DbOperation", b =>
                {
                    b.Property<long>("Index")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("index");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Index"));

                    b.Property<string>("CommandJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("command_json");

                    b.Property<string>("HostId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("host_id")
                        .UseCollation("C");

                    b.Property<string>("ItemsJson")
                        .HasColumnType("text")
                        .HasColumnName("items_json");

                    b.Property<DateTime>("LoggedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("logged_at");

                    b.Property<string>("NestedOperations")
                        .HasColumnType("text")
                        .HasColumnName("nested_operations");

                    b.Property<string>("Uuid")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("uuid")
                        .UseCollation("C");

                    b.HasKey("Index")
                        .HasName("pk_operations");

                    b.HasIndex("LoggedAt")
                        .HasDatabaseName("ix_operations_logged_at");

                    b.HasIndex("Uuid")
                        .IsUnique()
                        .HasDatabaseName("ix_operations_uuid");

                    b.ToTable("_operations");
                });
#pragma warning restore 612, 618
        }
    }
}
