<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsServerSideProject>true</IsServerSideProject>
    <RootNamespace>ActualChat.OAuth</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Db\Db.csproj" />
    <ProjectReference Include="..\Api.Contracts\Api.Contracts.csproj" />
    <ProjectReference Include="..\Users.Contracts\Users.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="OpenIddict.AspNetCore" />
    <PackageReference Include="OpenIddict.EntityFrameworkCore" />
  </ItemGroup>

</Project>
