<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="bunit" />
    <PackageReference Include="SixLabors.ImageSharp" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\dotnet\UI.Blazor.App\UI.Blazor.App.csproj" />
    <ProjectReference Include="..\Testing\Testing.csproj" />
  </ItemGroup>

</Project>
