<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <InternalsVisibleTo Include="ActualChat.Chat.IntegrationTests$(AssemblyPublicKey)" />
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\Api\Api.csproj" />
    <ProjectReference Include="..\Chat.Contracts\Chat.Contracts.csproj" />
    <ProjectReference Include="..\Core\Core.csproj" />
    <ProjectReference Include="..\Redis\Redis.csproj" />
    <ProjectReference Include="..\Transcription.Contracts\Transcription.Contracts.csproj" />
  </ItemGroup>
  
  <ItemGroup>
    <PackageReference Include="Microsoft.SemanticKernel" />
    <PackageReference Include="Microsoft.SemanticKernel.Agents.Abstractions" />
    <PackageReference Include="Microsoft.SemanticKernel.Agents.Core" />
    <PackageReference Include="Microsoft.SemanticKernel.Connectors.Google" />
  </ItemGroup>

</Project>
