// <auto-generated />
namespace ActualChat.Mjml.Blazor.Enums;

public static class MjmlSectionTextAlignExt
{
    public static string ToMjmlValue(this MjmlSectionTextAlign value)
        => value switch {
            MjmlSectionTextAlign.Left => "left",
            MjmlSectionTextAlign.Center => "center",
            MjmlSectionTextAlign.Right => "right",
            _ => throw new ArgumentOutOfRangeException(nameof(value), value, null),
        };
}
