// <auto-generated />
namespace ActualChat.Mjml.Blazor.Enums;

public static class MjmlRawPositionExt
{
    public static string ToMjmlValue(this MjmlRawPosition value)
        => value switch {
            MjmlRawPosition.FileStart => "file-start",
            _ => throw new ArgumentOutOfRangeException(nameof(value), value, null),
        };
}
