// <auto-generated />
namespace ActualChat.Mjml.Blazor.Enums;

public static class MjmlAccordionElementIconPositionExt
{
    public static string ToMjmlValue(this MjmlAccordionElementIconPosition value)
        => value switch {
            MjmlAccordionElementIconPosition.Left => "left",
            MjmlAccordionElementIconPosition.Right => "right",
            _ => throw new ArgumentOutOfRangeException(nameof(value), value, null),
        };
}
