// <auto-generated />
namespace ActualChat.Mjml.Blazor.Enums;

public static class MjmlButtonTextAlignExt
{
    public static string ToMjmlValue(this MjmlButtonTextAlign value)
        => value switch {
            MjmlButtonTextAlign.Left => "left",
            MjmlButtonTextAlign.Right => "right",
            MjmlButtonTextAlign.Center => "center",
            _ => throw new ArgumentOutOfRangeException(nameof(value), value, null),
        };
}
