// <auto-generated />
namespace ActualChat.Mjml.Blazor.Enums;

public static class MjmlSectionDirectionExt
{
    public static string ToMjmlValue(this MjmlSectionDirection value)
        => value switch {
            MjmlSectionDirection.Ltr => "ltr",
            MjmlSectionDirection.Rtl => "rtl",
            _ => throw new ArgumentOutOfRangeException(nameof(value), value, null),
        };
}
