// <auto-generated />
namespace ActualChat.Mjml.Blazor.Enums;

public static class MjmlCarouselThumbnailsExt
{
    public static string ToMjmlValue(this MjmlCarouselThumbnails value)
        => value switch {
            MjmlCarouselThumbnails.Visible => "visible",
            MjmlCarouselThumbnails.Hidden => "hidden",
            _ => throw new ArgumentOutOfRangeException(nameof(value), value, null),
        };
}
