// <auto-generated />
namespace ActualChat.Mjml.Blazor.Enums;

public static class MjmlGroupVerticalAlignExt
{
    public static string ToMjmlValue(this MjmlGroupVerticalAlign value)
        => value switch {
            MjmlGroupVerticalAlign.Top => "top",
            MjmlGroupVerticalAlign.Bottom => "bottom",
            MjmlGroupVerticalAlign.Middle => "middle",
            _ => throw new ArgumentOutOfRangeException(nameof(value), value, null),
        };
}
