// <auto-generated />
namespace ActualChat.Mjml.Blazor.Enums;

public static class MjmlAccordionElementIconAlignExt
{
    public static string ToMjmlValue(this MjmlAccordionElementIconAlign value)
        => value switch {
            MjmlAccordionElementIconAlign.Top => "top",
            MjmlAccordionElementIconAlign.Middle => "middle",
            MjmlAccordionElementIconAlign.Bottom => "bottom",
            _ => throw new ArgumentOutOfRangeException(nameof(value), value, null),
        };
}
