// <auto-generated />
namespace ActualChat.Mjml.Blazor.Enums;

public static class MjmlSocialVerticalAlignExt
{
    public static string ToMjmlValue(this MjmlSocialVerticalAlign value)
        => value switch {
            MjmlSocialVerticalAlign.Top => "top",
            MjmlSocialVerticalAlign.Bottom => "bottom",
            MjmlSocialVerticalAlign.Middle => "middle",
            _ => throw new ArgumentOutOfRangeException(nameof(value), value, null),
        };
}
