// <auto-generated />
namespace ActualChat.Mjml.Blazor.Enums;

public static class MjmlSectionFullWidthExt
{
    public static string ToMjmlValue(this MjmlSectionFullWidth value)
        => value switch {
            MjmlSectionFullWidth.FullWidth => "full-width",
            _ => throw new ArgumentOutOfRangeException(nameof(value), value, null),
        };
}
