// <auto-generated />
namespace ActualChat.Mjml.Blazor.Enums;

public static class MjmlColumnVerticalAlignExt
{
    public static string ToMjmlValue(this MjmlColumnVerticalAlign value)
        => value switch {
            MjmlColumnVerticalAlign.Top => "top",
            MjmlColumnVerticalAlign.Bottom => "bottom",
            MjmlColumnVerticalAlign.Middle => "middle",
            _ => throw new ArgumentOutOfRangeException(nameof(value), value, null),
        };
}
