// <auto-generated />
namespace ActualChat.Mjml.Blazor.Enums;

public static class MjmlTextVerticalAlignExt
{
    public static string ToMjmlValue(this MjmlTextVerticalAlign value)
        => value switch {
            MjmlTextVerticalAlign.Top => "top",
            MjmlTextVerticalAlign.Bottom => "bottom",
            MjmlTextVerticalAlign.Middle => "middle",
            _ => throw new ArgumentOutOfRangeException(nameof(value), value, null),
        };
}
