name: 'Setup dotnet environment for ActualChat build'
description: 'Install apple provisioning profile on Mac'
inputs:
  restore:
    default: "true"
    description: Whether restore packages or not required by build
  restore-tools:
    default: "true"
    description: Whether restore tools or not required by build
  restore-workloads:
    default: "true"
    description: Whether restore workloads or not required by build
runs:
  using: "composite"
  steps:
    - name: Install dotnet 8.0 SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-quality: 'ga'
        dotnet-version: '8.0.303' # NOTE: keep it in sync with global.json file

    - name: Use cached dependencies
      uses: actions/cache@v4
      with:
        path: ${{ github.workspace }}/.nuget/packages
        key: "${{ runner.os }}-nuget-${{ hashFiles('Directory.Packages.props') }}"
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: Restore tools
      shell: bash
      if: ${{ inputs.restore-tools == 'true' }}
      run: ./run-build.cmd restore-tools

    - name: Install workloads
      shell: bash
      if: ${{ inputs.restore-workloads == 'true' }}
      run: dotnet workload restore --from-rollback-file https://github.com/dotnet/maui/releases/download/8.0.82/8.0.82.json

    - name: Restore nuget packages
      shell: bash
      if: ${{ inputs.restore == 'true' }}
      # wasm-tools is required by restore, but restore-workloads is too heavy for that
      run: |
        dotnet workload install wasm-tools --from-rollback-file https://github.com/dotnet/maui/releases/download/8.0.82/8.0.82.json \
          && ./run-build.cmd restore && ./run-build.cmd restore
