name: Build nats docker image
concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"

on:
  workflow_dispatch:
    inputs:
      deployToDev:
        description: Push image to dev GAR
        type: boolean

permissions:
  contents: read
  id-token: write
  packages: write
  issues: read
  checks: write
  statuses: write

env:
  IMAGE_TAG: "2.10.10-alpine3.19"
  TARGET_IMAGE_NAME: "nats-jetstream"

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Avoid shallow clone for Nerdbank.GitVersioning
          fetch-depth: 0
          lfs: true

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image 'nats-jetstream:${{ env.IMAGE_TAG }}'
        uses: docker/build-push-action@v4
        with:
          context: .
          file: nats.Dockerfile
          tags: |
            ghcr.io/actual-chat/${{ env.TARGET_IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          push: true
          build-args: |
            IMAGE_TAG=${{ env.IMAGE_TAG }}
