name: Deploy prod

on: workflow_dispatch

permissions:
  contents: 'read'
  id-token: 'write'

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v3
        with:
          # Avoid shallow clone for Nerdbank.GitVersioning
          fetch-depth: 0
          lfs: true
      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0.7.2
        with:
          token_format: access_token
          workload_identity_provider: projects/224609592665/locations/global/workloadIdentityPools/actual-bootstrap/providers/actual-bootstrap-github-actual
          service_account: sa-deploy-bot@actual-infrastructure.iam.gserviceaccount.com
      - name: Login to GAR
        uses: docker/login-action@v2
        with:
          registry: us-central1-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}
      - name: Generate version variables
        id: nbgv
        uses: dotnet/nbgv@master
        with:
          setAllVars: true
      - name: Print version
        run: echo "SemVer2 ${{ steps.nbgv.outputs.SemVer2 }}"
      - name: Verify tag matches version.json
        if: endsWith(github.ref, steps.nbgv.outputs.MajorMinorVersion) != true
        run: |
          echo "The tag ${{ github.ref }} does not match version.json: ${{ steps.nbgv.outputs.MajorMinorVersion }}"
          exit 1
      - name: Pull non-prod docker image
        run: docker pull us-central1-docker.pkg.dev/actual-chat-dev-330512/dev/actualchat-app:${{ steps.nbgv.outputs.SemVer2 }}
      - name: Tag docker image
        run: |
          docker tag us-central1-docker.pkg.dev/actual-chat-dev-330512/dev/actualchat-app:${{ steps.nbgv.outputs.SemVer2 }} \
            us-central1-docker.pkg.dev/actual-infrastructure/docker/actual-chat-app:${{ steps.nbgv.outputs.SimpleVersion }}
      - name: Push prod docker image
        run: docker push us-central1-docker.pkg.dev/actual-chat-dev-330512/dev/actualchat-app:${{ steps.nbgv.outputs.SemVer2 }}
