name: Run slow tests
concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

on:
  workflow_dispatch:
  create:
  push:
    branches:
      - "**"
      - master
      - dev
      - release/v*
    paths-ignore:
      - "**.md"
  pull_request:
    branches:
      - master
      - dev
      - release/v*

permissions:
  contents: read
  id-token: write
  packages: write
  issues: read
  checks: write
  statuses: write

jobs:
  check-tested:
    name: Check for tested flag
    runs-on: ubuntu-latest
    outputs:
      skip-tests: ${{ steps.check.outputs.skip-tests }}
    steps:
      - name: Check commit message for #tested
        id: check
        run: |
          message="${{ github.event.head_commit.message }}"
          if echo "$message" | grep -qiw '#tested'; then
            echo "skip-tests=true" | tee -a $GITHUB_OUTPUT
          else
            echo "skip-tests=false" | tee -a $GITHUB_OUTPUT
          fi

  slow-tests:
    name: Run Slow tests
    needs: [check-tested]
    if: needs.check-tested.outputs.skip-tests != 'true'
    uses: ./.github/workflows/_run-tests.yml
    with:
      build-target: slow-tests
      report-name: Slow tests results
      opensearch-java-opts: '-Xms4096m -Xmx4096m'
    secrets: inherit
