name: Unit tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
env:
  DOCKER_BUILDKIT: 1
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # Avoid shallow clone for Nerdbank.GitVersioning
          fetch-depth: 0
          lfs: true
      - name: Replace git+ssh://git@ to https://
        run: sed -i 's/git+ssh:\/\/git@/https:\/\//g' src/nodejs/package-lock.json
      - name: Generate Nerdbank.GitVersioning files
        run: dotnet run --project build -- generate-version
      - name: Run unit tests
        run: docker-compose -f docker-compose.unit-tests.yml up --build --abort-on-container-exit --exit-code-from tests
