name: Unit tests
#concurrency:
#  group: ${{ github.workflow }}-${{ github.ref }}
#  cancel-in-progress: true
on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["master", "release/v*"]
env:
  DOCKER_BUILDKIT: 1
jobs:
  build-and-test:
    name: Build and Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # Avoid shallow clone for Nerdbank.GitVersioning
          fetch-depth: 0
          lfs: true
      - name: Replace git+ssh://git@ to https://
        run: sed -i 's/git+ssh:\/\/git@/https:\/\//g' src/nodejs/package-lock.json
      - name: Generate Nerdbank.GitVersioning files
        run: dotnet run --project build -- generate-version
      - name: Build and Run unit tests
        run: docker-compose -f docker-compose.unit-tests.yml up --build --abort-on-container-exit --exit-code-from tests
      - name: Report test results
        uses: dorny/test-reporter@v1
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: Unit tests results            # Name of the check run which will be created
          path: ./artifacts/tests/docker-output/*.trx    # Path to test results
          reporter: dotnet-trx        # Format of test results
