name: Unit tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        # Avoid shallow clone for Nerdbank.GitVersioning
        fetch-depth: 0
    - uses: dotnet/nbgv@master
      id: nbgv
      with:
        setAllVars: true
        setCommonVars: true
    - run: "echo 'SemVer2: ${{ steps.nbgv.outputs.SemVer2 }}'"
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: "6.0.x"
        include-prerelease: true
    - name: Build
      run: dotnet run --project build -c Release --no-launch-profile -- --configuration Debug build
    - name: Run unit tests
      run: dotnet run --project build -c Release --no-launch-profile -- --configuration Debug unit-coverage
